PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Duplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the creation of a duplicate Opportunity.</description>
    <inlineHelpText>Allows the creation of a duplicate Opportunity.</inlineHelpText>
    <label>Duplicate</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/recordTypes/PFG.recordType-meta.xml
<RecordType>
    <fullName>PFG</fullName>
    <active>true</active>
    <businessProcess>PFG</businessProcess>
    <description>Private Funds Default Opportunity Type</description>
    <label>PFG</label>
</RecordType>

PROD-12-18-19/force-app/main/default/classes/Test_OpportunityEvent.cls
@isTest private class Test_OpportunityEvent {

public static testMethod void testRunAs() {
        // Test Run as a PFG User
        Profile p = [SELECT Id FROM Profile WHERE Name='PFG_General']; 
        User u = new User(Alias = 'TESTABS', Email='ABS@Brownfield.com', 
            EmailEncodingKey='UTF-8', LastName='TestABS', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='ABS@Brownfield.com');
            System.assertequals(u.UserName,'ABS@Brownfield.com');
        System.runAs(u) {
            // The following code runs as user 'u' 
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Current Profile: ' + UserInfo.getProfileId()); 
            }
    }

    testMethod private static void testNewEventOpp() {

// Query for Event record types
List<RecordType> rtypes = [Select Name, Id From RecordType where sObjectType='Event' and isActive=true];

//Create a map between the Record Type Name and Id for easy retrieval
    Map<String,String> eventRecordTypes = new Map<String,String>{};
    for(RecordType rt: rtypes)
    eventRecordTypes.put(rt.Name,rt.Id);

    
// Query for Opportunity record types
List<RecordType> Opprtypes = [Select Name, Id From RecordType where sObjectType='Opportunity' and isActive=true];

//Create a map between the Record Type Name and Id for easy retrieval
    Map<String,String> opportunityRecordTypes = new Map<String,String>{};
    for(RecordType rt: Opprtypes)
    opportunityRecordTypes.put(rt.Name,rt.Id);
    
    List<Opportunity> Opps = new List<Opportunity>();
    List<Event> Ev = new List<Event>();

    // BF-9: Create a test account
    Account acct = TestFactory.buildTestAcc(1, UserInfo.getUserId());
    insert acct;

    // BF-33: Added an investment vehicles to opportunities
    Investment_Vehicle__c iv = TestFactory.buildInvestmentVehicle('test');
    insert iv;
    
    for (Integer i = 0; i < 5; i++) {
        Opportunity TestOpp = new Opportunity();
        TestOpp.ownerId = UserInfo.getUserId();
        TestOpp.RecordTypeId = opportunityRecordTypes.get('PFG');
        TestOpp.Name = i + 'test' + Math.round(Math.random()*1000);
        TestOpp.StageName = '1 - Identified as Prospect';
        TestOpp.CloseDate = Date.today().addDays(i);
        TestOpp.Amount = 1 + i;
        TestOpp.Duplicate__c = true;
        TestOpp.AccountId = acct.Id;
        TestOpp.Investment_Vehicle__c = iv.Id;
        Opps.add(TestOpp);
    }

    // BF-25: Updated to ignore duplicates
    Database.DMLOptions dml = new Database.DMLOptions();
    dml.DuplicateRuleHeader.allowSave = true;
    dml.DuplicateRuleHeader.runAsCurrentUser = true;
    Database.insert(Opps, dml);
    
    for (Opportunity o :    Opps) {
        Event TestEvent = new Event();
        TestEvent.ownerId = UserInfo.getUserId();
        //TestEvent.RecordTypeId = eventRecordTypes.get('BIM_PFG');
        TestEvent.whatId = o.Id;
        TestEvent.Subject = 'This is a test event';
        TestEvent.IsAllDayEvent = true;
        TestEvent.ActivityDate = Date.today();
        TestEvent.Interaction_Type__c = '';
        Ev.add(TestEvent);
    }
    insert Ev;
    
    }
}