PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/Investor_Position__c.object-meta.xml
<CustomObject>
    <label>Investor Position</label>
    <nameField>
        <label>Investor Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investor Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>DO NOT USE New Investor Account record</description>
    <inlineHelpText>DO NOT USE New Investor Account record</inlineHelpText>
    <label>xAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investor Positions (Account)</relationshipLabel>
    <relationshipName>Investor_Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Investor_Position_Account__c.field-meta.xml
<CustomField>
    <fullName>Investor_Position_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Investor Account record</description>
    <inlineHelpText>New Investor Account record</inlineHelpText>
    <label>Investor Position Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investor Positions (All)</relationshipLabel>
    <relationshipName>Investor_Positions2</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/classes/UtilityBatch.cls
global class UtilityBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    
    private String batchToRun = '';
    
    
    
    global UtilityBatch(String batchToRun){
        this.batchToRun = batchToRun;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = '';
        
        if(batchToRun == 'rollupFields'){
        	query = 'Select Id, Investor_Position_Account__c from Investor_Position__c Where Investor_Position_Account__c != null';
        }else if(batchToRun == 'populateInvestorPositionAccount'){ 
        	query = 'Select Id, Investor_Position_Account__c, Investor__c from Investor_Position__c Where Investor__c != null';
        }
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> records) {
        try{
        	if(batchToRun == 'rollupFields'){
        		ConfigurableRollup.rollup((List<Investor_Position__c>) records);
        	}else if(batchToRun == 'populateInvestorPositionAccount'){
        		List<Investor_Position__c> investorPositionToUpdate  = new List<Investor_Position__c>();
        		for(Investor_Position__c investor: (List<Investor_Position__c>) records){
        			investor.Investor_Position_Account__c = investor.Investor__c;
        			investorPositionToUpdate.add(investor);
        		}
        		if(!investorPositionToUpdate.isEmpty()){
        			update investorPositionToUpdate;
        		}
        	}
                 
        }catch(Exception e){
            System.debug('-->Error in UtilityBatch, batchToRun : ' + batchToRun + e.getMessage());
        }
    }
     
    global void finish(Database.BatchableContext BC){
        
    }
}