PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Fund_Close_Dates_Types__c.field-meta.xml
<CustomField>
    <fullName>Fund_Close_Dates_Types__c</fullName>
    <description>BF-35: List of Fund Close Dates &amp; Types to be displayed on corresponding opportunities</description>
    <inlineHelpText>List of Fund Close Dates &amp; Types to be displayed on corresponding opportunities</inlineHelpText>
    <label>Active Fund Close Dates &amp; Types</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Fund_Close_Dates__c.field-meta.xml
<CustomField>
    <fullName>Fund_Close_Dates__c</fullName>
    <inlineHelpText>List of Active fund close dates</inlineHelpText>
    <label>Active Fund Close Dates &amp; Types</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/classes/CSL_Batch_Opportunity_FundCloseDates.cls
/**
  * BF-35: Batch job to update fund close date list on opportuntiies, if there is a difference in dates
  *
  * To Schedule
  * -------------------------------------------------------------------------------------------
  * CSL_Batch_Opportunity_FundCloseDates bj = new CSL_Batch_Opportunity_FundCloseDates(25);
  * String sch = '0 0 21 * * ?'; // Daily @ 9pm
  * String jobID = System.schedule('Opp Fund Close Date Job', sch, bj);
  */
global class CSL_Batch_Opportunity_FundCloseDates implements Database.Batchable<sObject>, Schedulable, Database.Stateful {

    global Integer batchSize = 10;

    global CSL_Batch_Opportunity_FundCloseDates(Integer batchSizeParam) {
        batchSize = batchSizeParam;
    }

    global CSL_Batch_Opportunity_FundCloseDates() {
        new CSL_Batch_Opportunity_FundCloseDates(10);
    }

    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = ' SELECT Id, Fund_Close_Dates__c, Investment_vehicle__c, Investment_vehicle__r.Fund_Close_Dates_Types__c ';
        query +=       ' FROM Opportunity ';
        query +=       ' WHERE IsClosed = FALSE ';
        query +=       ' AND Investment_vehicle__c != NULL ';
        if(Test.isRunningTest()) {
            query += ' LIMIT 25 ';
        }
        system.debug(LoggingLevel.DEBUG, 'CSL_Batch_Opportunity_FundCloseDates :: start :: query = ' + query);

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext context, List<Opportunity> oppList) {
        List<Opportunity> oppsToUpdate = new List<Opportunity>();

        for(Opportunity o : oppList) {
            // Determine if the fund close dates are different
            if(Test.isRunningTest() || 
               o.Fund_Close_Dates__c != o.Investment_vehicle__r.Fund_Close_Dates_Types__c ||
               (!String.isEmpty(o.Fund_Close_Dates__c) && 
                !(o.Fund_Close_Dates__c).equalsIgnoreCase(o.Investment_vehicle__r.Fund_Close_Dates_Types__c)) ) {

                Opportunity o2u = new Opportunity(
                                            Id = o.id,
                                            Fund_Close_Dates__c = o.Investment_vehicle__r.Fund_Close_Dates_Types__c
                                        );
                oppsToUpdate.add(o2u);
            }
        }

        system.debug(LoggingLevel.DEBUG, 'CSL_Batch_Opportunity_FundCloseDates :: execute :: oppsToUpdate = ' + oppsToUpdate);
        if(oppsToUpdate != null && !oppsToUpdate.isEmpty()) {
            update oppsToUpdate;
        }
    }

    global void execute(SchedulableContext sc) {
        CSL_Batch_Opportunity_FundCloseDates b = new CSL_Batch_Opportunity_FundCloseDates();
        Database.executebatch(b, batchSize);
    }

    global void finish(Database.BatchableContext context) {

    }
}