PROD-12-18-19/force-app/main/default/objects/Account/fields/Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Business_Group__c</fullName>
    <description>Co-Investment Business vertical</description>
    <inlineHelpText>Co-Investment Business vertical</inlineHelpText>
    <label>Business Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Account/fields/Relationship_Importance__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Importance__c</fullName>
    <description>Account Level Relationship Importance</description>
    <inlineHelpText>Account Level Relationship Importance</inlineHelpText>
    <label>Relationship Importance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High (1)</fullName>
            </value>
            <value>
                <fullName>Medium (2)</fullName>
            </value>
            <value>
                <fullName>Low (3)</fullName>
            </value>
            <value>
                <fullName>Research Required</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Not Interested in Private Funds</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
                <isActive>false</isActive>
                <label>Neutral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Coverage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Investing_Interest_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Coverage__c/fields/Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Business_Group__c</fullName>
    <label>Business Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Real Asset / Infra</fullName>
            </value>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
                <isActive>false</isActive>
                <label>Infrastructure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Coverage__c/fields/Relationship_Importance__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Importance__c</fullName>
    <label>Relationship Importance</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High (1)</fullName>
            </value>
            <value>
                <fullName>Medium (2)</fullName>
            </value>
            <value>
                <fullName>Low (3)</fullName>
            </value>
            <value>
                <fullName>Research Required</fullName>
            </value>
            <value>
                <fullName>Not Currently Investing</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
                <isActive>false</isActive>
                <label>Neutral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Coverage__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12120/force-app/main/default/classes/Test_Coverage_Handler.cls
@isTest
private class Test_Coverage_Handler {
@testSetup
     static void setupTestData(){
          Account accobj = new Account(Name ='TestAccount' );
      		insert accobj;
         Account acc = [select name from Account limit 1];
         Coverage__c testCov1 = new Coverage__c(Role__c='Primary', Business_Group__c='Real Asset / Infra',Relationship_Importance__c='Low (3)',Account__c = acc.Id);
        	insert testCov1; 
         Coverage__c testCov2 = new Coverage__c(Role__c='Primary', Business_Group__c='Private Equity',Relationship_Importance__c='Low (3)',Account__c = acc.Id);
        	insert testCov2; 
         Coverage__c testCov3 = new Coverage__c(Role__c='Primary', Business_Group__c='Real Estate',Relationship_Importance__c='Low (3)',Account__c = acc.Id);
        	insert testCov3; 
         
     }
    static testMethod void test_Coverage_Handler_UseCase(){
        List<Coverage__c> covToDel = new List<Coverage__c>(); 
        for(Coverage__c cov: [Select id,Role__c,Business_Group__c from Coverage__c])
        {
            covToDel.add(cov);
        }
        test.startTest(); 
        	delete covToDel;
        test.stopTest();
    }
}