PROD-12-18-19/force-app/main/default/objects/Account/fields/Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Business_Group__c</fullName>
    <description>Co-Investment Business vertical</description>
    <inlineHelpText>Co-Investment Business vertical</inlineHelpText>
    <label>Business Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Account/fields/Relationship_Importance__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Importance__c</fullName>
    <description>Account Level Relationship Importance</description>
    <inlineHelpText>Account Level Relationship Importance</inlineHelpText>
    <label>Relationship Importance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High (1)</fullName>
            </value>
            <value>
                <fullName>Medium (2)</fullName>
            </value>
            <value>
                <fullName>Low (3)</fullName>
            </value>
            <value>
                <fullName>Research Required</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Not Interested in Private Funds</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
                <isActive>false</isActive>
                <label>Neutral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Coverage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Investing_Interest_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Coverage__c/fields/Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Business_Group__c</fullName>
    <label>Business Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Real Asset / Infra</fullName>
            </value>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
                <isActive>false</isActive>
                <label>Infrastructure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Coverage__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Coverage</relationshipLabel>
    <relationshipName>Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Coverage__c/fields/Relationship_Importance__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Importance__c</fullName>
    <label>Relationship Importance</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High (1)</fullName>
            </value>
            <value>
                <fullName>Medium (2)</fullName>
            </value>
            <value>
                <fullName>Low (3)</fullName>
            </value>
            <value>
                <fullName>Research Required</fullName>
            </value>
            <value>
                <fullName>Not Currently Investing</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
                <isActive>false</isActive>
                <label>Neutral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Coverage__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Current_Commitments_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Commitments_USD__c</fullName>
    <inlineHelpText>Roll up from most recent Investor Position records totalling the Current Commitments in the Fund in USD.

Current commitment is how much has been currently invested + available for drawndown left.</inlineHelpText>
    <label>Current Commitments - USD</label>
    <summarizedField>Investor_Position__c.Current_Commitments_USD__c</summarizedField>
    <summaryFilterItems>
        <field>Investor_Position__c.Is_Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Investor_Position__c.Investment_Vehicle__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/Investor_Position__c.object-meta.xml
<CustomObject>
    <label>Investor Position</label>
    <nameField>
        <label>Investor Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investor Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Current_Commitments_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Commitments_USD__c</fullName>
    <inlineHelpText>Imported field of Current Commitments in the Fund in USD. 

Current commitment is how much has been currently invested + available for drawdown.</inlineHelpText>
    <label>Current Commitments - USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investor_Position__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle</value>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please DO NOT Create Investor Position for Inactive, Discontinued, Closed Vehicles</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Investor_Position_Account__c.field-meta.xml
<CustomField>
    <fullName>Investor_Position_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Investor Account record</description>
    <inlineHelpText>New Investor Account record</inlineHelpText>
    <label>Investor Position Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investor Positions (All)</relationshipLabel>
    <relationshipName>Investor_Positions2</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copied from originating opportunity. Populates automatically.</inlineHelpText>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Office__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Office</relationshipLabel>
    <relationshipName>Office</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/TEST_Triggers.cls
@isTest(SeeAllData=false)
private with sharing class TEST_Triggers {
    private static testMethod void Test_Account() {
        Account a = new Account(Name='Test Account');

        insert a;
        update a;
        delete a;
    }
    private static testMethod void Test_Office() {
        Account a = new Account(Name='Test Account');
        insert a;

        Office__c o = new Office__c(Name='Test Office', Account__c=a.Id);

        insert o;
        update o;
        delete o;
    }
    private static testMethod void Test_Commitment() {
        Investment_Vehicle__c iv = new Investment_Vehicle__c();
        insert iv;
        Finaccount__c c = new Finaccount__c();
        c.Investment_Vehicle__c = iv.Id;
        insert c;
        update c;
        delete c;
    }
    private static testMethod void Test_InvestorPosition() {
        Account a = new Account(Name='Test Account');
        insert a;

        Investment_Vehicle__c inv = new Investment_Vehicle__c(Name='Test Invesment Vehicle');
        insert inv;

        Opportunity o = new Opportunity(Name='Test Opp', StageName='test', CloseDate=system.today(), Investment_Vehicle__c=inv.Id, AccountId=a.Id);
        insert o;

        Investor_Position__c invPos = new Investor_Position__c(Name='Test Investor Position', Current_Commitments_USD__c=10, Investment_Vehicle__c=inv.Id, Investor_Position_Account__c=a.Id, Opportunity_Name__c=o.Id);

        insert invPos;
        update invPos;
        delete invPos;
    }
    private static testMethod void Test_Coverage() {
        Coverage__c c = new Coverage__c(Role__c='Primary', Business_Group__c='Real Estate', Relationship_Importance__c='Do Not Call');

        insert c;
        update c;
        delete c;
    }

    private static testMethod void Test_Opportunity() {
        Account a = new Account(Name='Test Account');
        insert a;

        Investment_Vehicle__c inv = new Investment_Vehicle__c(Name='Test Invesment Vehicle');
        insert inv;

        Opportunity o = new Opportunity(Name='Test Opp', StageName='test', CloseDate=system.today(), Investment_Vehicle__c=inv.Id, AccountId=a.Id);

        insert o;
        update o;
        delete o;
    }
}