PROD-12-18-19/force-app/main/default/objects/Account/fields/Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Business_Group__c</fullName>
    <description>Co-Investment Business vertical</description>
    <inlineHelpText>Co-Investment Business vertical</inlineHelpText>
    <label>Business Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/PFG_CRM_Primary_Lead__c.field-meta.xml
<CustomField>
    <fullName>PFG_CRM_Primary_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PFG Primary Lead or in the case of split coverage, this would indicate Real Estate coverage.</description>
    <inlineHelpText>Primary Lead or in the case of split coverage, this would indicate Real Estate coverage.</inlineHelpText>
    <label>Real Estate Lead</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PFG_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account/fields/PFG_CRM_Real_Asset_Lead__c.field-meta.xml
<CustomField>
    <fullName>PFG_CRM_Real_Asset_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>In the case of split coverage, this would indicate Real Asset (except Real Estate) coverage.</description>
    <inlineHelpText>In the case of split coverage, this would indicate Real Asset (except Real Estate) coverage.</inlineHelpText>
    <label>Real Asset/Infra Lead</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsUser3</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account/fields/PFG_CRM_Secondary__c.field-meta.xml
<CustomField>
    <fullName>PFG_CRM_Secondary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Secondary CRM when it comes to a Co-coverage model</description>
    <inlineHelpText>Secondary CRM when it comes to a Co-coverage model</inlineHelpText>
    <label>Private Equity Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts8</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Coverage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Investing_Interest_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Coverage__c/fields/Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Business_Group__c</fullName>
    <label>Business Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Real Asset / Infra</fullName>
            </value>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
                <isActive>false</isActive>
                <label>Infrastructure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/Coverage_Handler.cls
//This class is a helper class for Coverage Trigger
//It set the Coverage fields on Accounts to NUll on the deletaion of any Coverage data from Coverage form	
public class Coverage_Handler {
    public void updateCoverageOnAccount(List<Coverage__c> lstCoverage) {    
        Set<Id> infrastructurelst = new Set<Id>();
        Set<Id> realEstatelst = new Set<Id>();
        Set<Id> privateEquitylst = new Set<Id>();		
        Set<Id> accIdLst = new Set<Id>();
        for(Coverage__c c : lstCoverage)
        {
            accIdLst.add(c.Account__c);
            if(c.Business_Group__c == 'Real Asset / Infra'){
				infrastructurelst.Add(c.Account__c);                
            }
            if(c.Business_Group__c == 'Private Equity'){
                privateEquitylst.Add(c.Account__c);
            }  
            if(c.Business_Group__c == 'Real Estate'){            
				realEstatelst.Add(c.Account__c);  
            }
        }
       
        List<Account> accToUpdate = new List<Account>(); 
        for(Account acc : [Select PFG_CRM_Real_Asset_Lead__c,PFG_CRM_Primary_Lead__c,PFG_CRM_Secondary__c from Account where id In : accIdLst])
        {                    
            if(infrastructurelst.size() > 0 && infrastructurelst.contains(acc.id)){                
                acc.PFG_CRM_Real_Asset_Lead__c = null;                
            }
            if(privateEquitylst.size() > 0 && privateEquitylst.contains(acc.id)){
                acc.PFG_CRM_Secondary__c = null;                
            }
            if(realEstatelst.size() > 0 && realEstatelst.contains(acc.id)){
                acc.PFG_CRM_Primary_Lead__c = null;                
            }
            accToUpdate.add(acc);
        }
        try
        {
        	update accToUpdate;
        }
        catch(exception ex)
    	{     
       		system.debug('#### Exception caught: ' + ex.getMessage());
     	}
    }   
}