PROD-12-18-19/force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>Canada - BC</fullName>
                <isActive>false</isActive>
                <label>Canada - BC</label>
            </value>
            <value>
                <fullName>Canada - Federal</fullName>
                <isActive>false</isActive>
                <label>Canada - Federal</label>
            </value>
            <value>
                <fullName>Canada - ON</fullName>
                <isActive>false</isActive>
                <label>Canada - ON</label>
            </value>
            <value>
                <fullName>Canada - QC</fullName>
                <isActive>false</isActive>
                <label>Canada - QC</label>
            </value>
            <value>
                <fullName>MISO/PJM/Louisianna/TVA</fullName>
                <isActive>false</isActive>
                <label>MISO/PJM/Louisianna/TVA</label>
            </value>
            <value>
                <fullName>US - California/Arizona</fullName>
                <isActive>false</isActive>
                <label>US - California/Arizona</label>
            </value>
            <value>
                <fullName>US - Connecticut</fullName>
                <isActive>false</isActive>
                <label>US - Connecticut</label>
            </value>
            <value>
                <fullName>US - Federal</fullName>
                <isActive>false</isActive>
                <label>US - Federal</label>
            </value>
            <value>
                <fullName>US - Maine</fullName>
                <isActive>false</isActive>
                <label>US - Maine</label>
            </value>
            <value>
                <fullName>US - Massachusetts</fullName>
                <isActive>false</isActive>
                <label>US - Massachusetts</label>
            </value>
            <value>
                <fullName>US - New England</fullName>
                <isActive>false</isActive>
                <label>US - New England</label>
            </value>
            <value>
                <fullName>US - New York</fullName>
                <isActive>false</isActive>
                <label>US - New York</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Long_Name__c</fullName>
    <label>Long Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Corporate Credit</fullName>
            </value>
            <value>
                <fullName>Corporate High Yield</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Opportunities</fullName>
            </value>
            <value>
                <fullName>Energy Infrastructure</fullName>
            </value>
            <value>
                <fullName>Equity Opportunities</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
            <value>
                <fullName>Investments</fullName>
            </value>
            <value>
                <fullName>Opportunistic MBS</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Real Asset Debt</fullName>
            </value>
            <value>
                <fullName>Real Asset Solutions</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Securitized Credit</fullName>
            </value>
            <value>
                <fullName>Specialty Funds</fullName>
            </value>
            <value>
                <fullName>Strategic Income</fullName>
            </value>
            <value>
                <fullName>Timberland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Short Listed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>General Interest</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Pre-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Fully Divested</fullName>
            </value>
            <value>
                <fullName>Wound Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canadian Pooled Fund</fullName>
            </value>
            <value>
                <fullName>Closed End Fund</fullName>
            </value>
            <value>
                <fullName>General Overview</fullName>
            </value>
            <value>
                <fullName>Hedge Fund</fullName>
            </value>
            <value>
                <fullName>Listed Issuers</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Private Fund - Open Ended</fullName>
            </value>
            <value>
                <fullName>Private Fund</fullName>
            </value>
            <value>
                <fullName>Separate Accounts</fullName>
            </value>
            <value>
                <fullName>Separately Managed Account</fullName>
            </value>
            <value>
                <fullName>UCITS</fullName>
            </value>
            <value>
                <fullName>Co-Invest</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Sale of Asset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Duplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the creation of a duplicate Opportunity.</description>
    <inlineHelpText>Allows the creation of a duplicate Opportunity.</inlineHelpText>
    <label>Duplicate</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/classes/TestNewAccountNameTrigger.cls
@isTest
public class TestNewAccountNameTrigger {
  static testMethod void testBulkInsert() {
        List<Opportunity> opps = new List<Opportunity>();
        integer iterations = 10;
        
        string accName = 'Test Account';
        List<Account> accs = new List<Account>();
        //User u  = [Select id, name from User]
        for (integer i = 0; i < iterations; i++)
        {
            Account acc = new Account(
                name = accName + ' ' + i,
                RecordTypeId = '0120b000000B0QUAA0',
                BillingCountry = 'United States',
                OwnerId = '0050b000005fjSN'
            );
            accs.add(acc);
        }
        
        insert accs;

        // BF-33: Added to fix code coverage
        accs = [SELECT Id
                FROM Account
                WHERE OwnerId = '0050b000005fjSN'
                AND Name LIKE 'Test Account%'
                AND RecordTypeId = '0120b000000B0QUAA0'
                AND CreatedDate = TODAY
                LIMIT 10];
        system.debug('TestNewAccountNameTrigger :: accs = ' + accs);
        
        string ivName = 'BIF II';
        Investment_Vehicle__c iv = new Investment_Vehicle__c(
            Name = ivName,
            RecordTypeId = '01233000000MIBHAA4',
            Vehicle_Type__c = 'Private Fund',
            Long_Name__c = 'BIF',
            Status__c = 'Marketing',
            Platform__c = 'Infrastructure'
        );
        
        insert iv;
        
        iv = [Select Id, Name from Investment_Vehicle__c where Name = :ivName];
        
        // BF-33: This was causing an index out of bound error
        // accs = [select Id, Name from Account where name = :accName];
        
        for (Integer i=0;i<iterations;i++) {

            Opportunity a = new Opportunity(
                Name = 'Test Opportunity ' + i,
                AccountId = accs[i].Id,
                Investment_Vehicle__c = iv.Id,
                RecordTypeId = '01240000000MHIDAA4',
                CloseDate = System.today().addMonths(1),
                CurrencyIsoCode = 'USD',
                StageName = '1: Prospect identified',
                ForecastCategoryName = 'Pipeline',
                Duplicate__c = true,
                Amount = 1000,
                OwnerId = '0050b000005fjSN'
                //,  ForecastCategory = 'Pipeline'
            );
            
            System.debug(a.AccountId);
            System.debug(a.Investment_Vehicle__c);
            opps.add(a);

        }
        
        Test.startTest();  

        insert opps;
        update opps;
        
        Test.stopTest();     

        // query for all accounts created and assert that the color was added correctly
        for (Opportunity opp : [Select Name from Opportunity])
            System.debug(opp.Name);
            
        for (Account acc : [Select Id,Name from Account])
            System.debug(acc.Id + ' ' + acc.Name);
        
        for (Investment_Vehicle__c inV : [Select Id,Name from Investment_Vehicle__c])
            System.debug(inV.Id + ' ' + inV.Name);
    }
}