WMG112519/force-app/main/default/objects/Contact_Keyword__c/Contact_Keyword__c.object-meta.xml
<CustomObject>
    <label>Contact Keyword</label>
    <nameField>
        <displayFormat>CK-{00000000}</displayFormat>
        <label>Contact Keyword</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Value_Currency__c</fullName>
    <label>Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Value_Text__c</fullName>
    <label>Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/recordTypes/Currency.recordType-meta.xml
<RecordType>
    <fullName>Currency</fullName>
    <active>true</active>
    <description>Store keywords with a currency value (e.g. Net Worth = $10,000,000)</description>
    <label>Currency</label>
</RecordType>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/recordTypes/Text.recordType-meta.xml
<RecordType>
    <fullName>Text</fullName>
    <active>true</active>
    <description>Store keywords with a text value (e.g. Hobbies = Golf) or no associated value (e.g. Receives Newsletter)</description>
    <label>Text</label>
</RecordType>

WMG112519/force-app/main/default/classes/testMethod_ManageKeywordExtension.cls
@isTest(SeeAllData=False)
private class testMethod_ManageKeywordExtension {
  static testMethod void ManageKeywordExtension_Test () 
    {
      Contact ct = new Contact();
      ct.FirstName = 'Test';
      ct.LastName = 'Method';
      insert ct;
      PageReference pageRef = Page.ManageKeywords;
    Test.setCurrentPageReference(pageref);
    ApexPages.currentPage().getParameters().put('id',ct.id);
    
      test.startTest();
      ManageKeywordExtension myCon = new ManageKeywordExtension();
      myCon.Init();
      myCon.keywordObj.Type__c = 'Text';
      myCon.keywordObj.Name = 'Test Me';
      myCon.contactKeyword.Value_Text__c= '1234';
      myCon.ClearData() ;
      myCon.keywordObj.Type__c = 'Currency';
      myCon.keywordObj.Name = 'Test Me';
      myCon.contactKeyword.Value_Currency__c = 111;
      myCon.OverrideSave();
      List<Contact_Keyword__c> ctKey = [select id, name from Contact_Keyword__c ];
      System.assertEquals(1, ctKey.size());
      //List<Apexpages.Message> msgs = ApexPages.getMessages();
      //System.assertNotEquals(0, msgs.size() );
      myCon.ClearValues();
      myCon.keywordObj.Type__c = 'Text';
      myCon.contactKeyword.Value_Text__c = 'aaaa';
      myCon.OverrideSave();
      ctKey = [select id, name from Contact_Keyword__c ];
      System.assertEquals(2, ctKey.size());
      //Get the Keyword List 
      List<Contact_Keyword__c > kwList = myCon.getContactKeywords () ;
      myCon.SelectedRec = ctKey[0].id;
      myCon.EditContactKeyWord();
      myCon.contactKeyword.Value_Text__c = '12345';
      myCon.OverrideSave();
      ctKey = [select id, name from Contact_Keyword__c ];
      System.assertEquals(2, ctKey.size());
      myCon.SelectedRec = ctKey[0].id;
      myCon.DeleteContactKeyWord();
      ctKey = [select id, name from Contact_Keyword__c ];
      System.assertEquals(1, ctKey.size());
      myCon.Cancel();
      test.stopTest();
    }
}