WMG112519/force-app/main/default/objects/Contact_Keyword__c/Contact_Keyword__c.object-meta.xml
<CustomObject>
    <label>Contact Keyword</label>
    <nameField>
        <displayFormat>CK-{00000000}</displayFormat>
        <label>Contact Keyword</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Keywords</relationshipLabel>
    <relationshipName>Contact_Keywords</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <label>Keyword</label>
    <referenceTo>Keyword__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contact_Keywords</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Updated by Workflow, show the value regardless of the type.  Too big to put in a formula.</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Value_Currency__c</fullName>
    <label>Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Value_Date__c.field-meta.xml
<CustomField>
    <fullName>Value_Date__c</fullName>
    <label>Value (Date)</label>
    <type>Date</type>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Value_Number__c</fullName>
    <label>Value (Number)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/fields/Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Value_Text__c</fullName>
    <label>Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/recordTypes/Currency.recordType-meta.xml
<RecordType>
    <fullName>Currency</fullName>
    <active>true</active>
    <description>Store keywords with a currency value (e.g. Net Worth = $10,000,000)</description>
    <label>Currency</label>
</RecordType>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/recordTypes/Date.recordType-meta.xml
<RecordType>
    <fullName>Date</fullName>
    <active>true</active>
    <description>Store keywords with a date value (e.g. Dog&#39;s Birthday = 8/4/2010)</description>
    <label>Date</label>
</RecordType>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/recordTypes/Number.recordType-meta.xml
<RecordType>
    <fullName>Number</fullName>
    <active>true</active>
    <description>Store keywords with a numeric value, but not a currency (e.g. Favorite Number = 42)</description>
    <label>Number</label>
</RecordType>

WMG112519/force-app/main/default/objects/Contact_Keyword__c/recordTypes/Text.recordType-meta.xml
<RecordType>
    <fullName>Text</fullName>
    <active>true</active>
    <description>Store keywords with a text value (e.g. Hobbies = Golf) or no associated value (e.g. Receives Newsletter)</description>
    <label>Text</label>
</RecordType>

WMG112519/force-app/main/default/objects/Keyword__c/Keyword__c.object-meta.xml
<CustomObject>
    <label>Keyword</label>
    <nameField>
        <label>Keyword Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Keywords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WMG112519/force-app/main/default/objects/Keyword__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WMG112519/force-app/main/default/objects/Keyword_Contact__c/Keyword_Contact__c.object-meta.xml
<CustomObject>
    <label>Keyword Contact</label>
    <nameField>
        <displayFormat>KEY-{0000}</displayFormat>
        <label>Keyword Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Keyword Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WMG112519/force-app/main/default/objects/Keyword_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Keywords</relationshipLabel>
    <relationshipName>Keyword</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

WMG112519/force-app/main/default/classes/ManageKeywordExtension.cls
public with sharing class ManageKeywordExtension {
  
  public Keyword__c keywordObj {get;set;}
  public Contact_Keyword__c contactKeyword  {get;set;}
  //public string Value {get;set;}
  //public string Comments {get;set;}
  public string SelectedRec {get;set;}
  public string ContactName {get;set;}
  //public List<Contact_Keyword__c> contactKeywords {get;set;}
  public string ContactID {get;set;}
  public boolean isEditMode  {get;set;}
  
    
  public ManageKeywordExtension ()
  {
    
  }
  public PageReference Init ()
  {
    //Get the Contact ID
    ContactID = ApexPages.currentPage().getParameters().get('Id');
    if (ContactID == null)
      return new PageReference('/');
    
    isEditMode = false ;  
    ContactName = [select id, name from contact where id = :ContactID].Name;
    if (isEditMode == false)
    {
      keywordObj = new Keyword__c();
      //keywordObj.Type__c = 'Text';
      contactKeyword = new Contact_Keyword__c() ;
    }
    return null;
    
  }
  public Pagereference Cancel ()
  {
    return new PageReference('/' + ContactID);
  }
  public void OverrideSave ()
  {
    if (keywordObj.type__c == null)
    {
      ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'The type needs to be selected' );
          ApexPages.addMessage(myMsg);
          return;
    }
      
    List<Keyword__c> kw = [select name, type__c from Keyword__c where name = :keywordObj.Name and type__c = :keywordObj.Type__c ];
    if (kw.isEmpty())
    {
      if (isEditMode)
        keywordObj.id = null;
      insert keywordObj;
    }
    else
      keywordObj = kw[0];
    
    if (!isEditMode)
    {
      Contact_Keyword__c ck = contactKeyword;
      //ck.Comments__c = this.Comments;
      ck.Contact__c = ContactID;
      ck.Keyword__c = keywordObj.id ;
      ck.RecordTypeId = [select id , name from RecordType where sObjectType = 'Contact_Keyword__c' and Name = :keywordObj.Type__c].id;
      /*
      if (kw[0].Type__c == 'Currency')
        ck.Value_Currency__c  = this.Value;
      if (kw[0].Type__c == 'Date')
        ck.Value_Date__c  = this.Value;
      if (kw[0].Type__c == 'Number')
        ck.Value_Number__c = this.Value ;
      if (kw[0].Type__c == 'Text')
        ck.Value_Text__c = this.value;
      */
      insert ck;
    }
    else
      update contactKeyword;
      
    
    keywordObj = new Keyword__c();
    keywordObj.Type__c = null;
    contactKeyword = new Contact_Keyword__c() ;
    isEditMode = false;
    
  }
  public void ClearValues ()
  {
    
    contactKeyword.Value_Currency__c = null;
    contactKeyword.Value_Date__c = null;
    contactKeyword.Value_Text__c = null;
    contactKeyword.Value_Number__c = null;
  }
  
  public void ClearData ()
  {
    keywordObj = new Keyword__c();
    //keywordObj.Type__c = 'Text';
    contactKeyword = new Contact_Keyword__c() ;
    isEditMode = false;
  }
  public void EditContactKeyWord ()
  {
    List<Contact_Keyword__c>  ck = [select id, Comments__c, Contact__c, Keyword__r.Name , Value_Text__c , Value_Date__c , Value_Number__c , Value_Currency__c  from Contact_Keyword__c where id = :this.SelectedRec ] ;
    if (ck.size() > 0 )
    {
      isEditMode = true;
      //keywordObj = new Keyword__c();
      keywordObj = [select id,name, Type__c from Keyword__c where id = :ck[0].keyword__c] ;
      contactKeyword = ck[0];
      System.Debug(contactKeyword);
    }
  }
  public void DeleteContactKeyWord ()
  {
    System.debug(this.SelectedRec );
    List<Contact_Keyword__c> ck = [select id from Contact_Keyword__c where id = :this.SelectedRec ];
    if (ck.size() > 0 )
      delete ck;
  }
  public List<Contact_Keyword__c > getContactKeywords ()
  {
    List<Contact_Keyword__c > results=  [select id, Keyword__r.Name, Value__c ,Comments__c , Contact__c, CreatedBy.Name, CreatedDate  from Contact_Keyword__c where Contact__c  = :ContactID Order By CreatedDate desc  ];
    return results;
  }
  //Need to be the related list object 
  
}