WMG112519/force-app/main/default/objects/Task_Updates__c/Task_Updates__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Task Update</label>
</CustomObject>

WMG112519/force-app/main/default/objects/Task_Updates__c/fields/Child_Field__c.field-meta.xml
<CustomField>
    <fullName>Child_Field__c</fullName>
    <label>Child Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/Task_Updates__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/Task_Updates__c/fields/Task_Field__c.field-meta.xml
<CustomField>
    <fullName>Task_Field__c</fullName>
    <label>Task Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/Task_Updates__c/fields/Task_Value__c.field-meta.xml
<CustomField>
    <fullName>Task_Value__c</fullName>
    <label>Task Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

WM-FULL_12219/force-app/main/default/classes/testMethod_ManageTaskUpdateExtension.cls
@isTest
private class testMethod_ManageTaskUpdateExtension 
{

    static testMethod void test_ManageTaskUpdateExtension_Test() 
    {
        Task_Updates__c tu = new Task_Updates__c();
        tu.Name = 'TEST';
        tu.Task_Field__c = 'Type';
         tu.Task_Value__c = 'Call';
         tu.Object_To_Update__c = 'Account';
         tu.Field_To_Update__c = 'testField';
        
      test.startTest();
      ApexPages.StandardController sc =  new ApexPages.StandardController(tu) ;
      ManageTaskUpdateExtension myCon = new ManageTaskUpdateExtension(sc);
      myCon.getTaskFields() ;
      myCon.getTasksPickListValues();
      myCon.getObjectList();
      myCon.getObjectFieldList();
      myCon.OverRideSave () ;
    
      List<Apexpages.Message> msgs = ApexPages.getMessages();
      System.assertEquals(0, msgs.size() );
      myCon.CloneRec();
      
      test.stopTest();
      
    }
    static testMethod void test_ManageTaskUpdateExtension_Test_Validation() 
    {
        Task_Updates__c tu = new Task_Updates__c();
        tu.Name = 'TEST';
           
      test.startTest();
      ApexPages.StandardController sc =  new ApexPages.StandardController(tu) ;
      ManageTaskUpdateExtension myCon = new ManageTaskUpdateExtension(sc);
      
      myCon.OverRideSave () ;
      List<Apexpages.Message> msgs = ApexPages.getMessages();
      System.assertNotEquals(0, msgs.size() );
      myCon.ResetChildValues () ;
    }
     static testMethod void test_ManageTaskUpdateExtension_Test_WithChild() 
    {
        Task_Updates__c tu = new Task_Updates__c();
        tu.Name = 'TEST';
        tu.Task_Field__c = 'Type';
         tu.Task_Value__c = 'Call';
         tu.Object_To_Update__c = 'Account';
         tu.Field_To_Update__c = 'testField';
         tu.Child_Object__c = 'Contact';
         tu.Child_Field__c = 'AccountID';
        
      test.startTest();
      ApexPages.StandardController sc =  new ApexPages.StandardController(tu) ;
      ManageTaskUpdateExtension myCon = new ManageTaskUpdateExtension(sc);
      myCon.getTaskFields() ;
      myCon.getTasksPickListValues();
      myCon.getObjectList();
      myCon.getObjectFieldList();
      myCon.getRelationshipObjects();
      myCon.getRelationshipfields();
      myCon.OverRideSave () ;
    
      List<Apexpages.Message> msgs = ApexPages.getMessages();
      System.assertEquals(0, msgs.size() );
      myCon.CloneRec();
      
      test.stopTest();
      
    }
}