PROD_10-24-19/force-app/main/default/objects/Campaign/fields/Deal_Team__c.field-meta.xml
<CustomField>
    <fullName>Deal_Team__c</fullName>
    <formula>Original_Deal_Opportunity__r.Deal_Team__c</formula>
    <label>Deal Team</label>
    <type>Text</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Campaign/fields/Original_Deal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Original_Deal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Deal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Deal_Team__c.field-meta.xml
<CustomField>
    <fullName>Deal_Team__c</fullName>
    <inlineHelpText>To modify the Deal Team, scroll to the Opportunity Team section on the Opportunity record.  This field is read only.</inlineHelpText>
    <label>Deal Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used when splitting an opportunity</inlineHelpText>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Child Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Secondary_CRM__c.field-meta.xml
<CustomField>
    <fullName>Secondary_CRM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary CRM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Sharing_History__c/Sharing_History__c.object-meta.xml
<CustomObject>
    <label>Sharing History</label>
    <nameField>
        <displayFormat>SH-{00000000}</displayFormat>
        <label>Sharing History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sharing Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Sharing_History__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Write</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Sharing_History__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Sharing_History__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Sharing_History__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sharing Histories</relationshipLabel>
    <relationshipName>Sharing_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Sharing_History__c/fields/User_or_Group__c.field-meta.xml
<CustomField>
    <fullName>User_or_Group__c</fullName>
    <label>User or Group</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Sharing_History__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <label>User Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Lead Qualifier</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/classes/CommonUtility.cls
global class CommonUtility
{
     public static set<Id> IsTriggerUpdate = null;

  // This method is used by trigger AddRemoveApexSharing on insert operation
  // This methods create sharing records for existing campaign records
  @future(callout=true)
  public static void processSharing(set<id> setids)
  {    
        OpportunityTeamMember obj2 = new OpportunityTeamMember(); 
        //This to track the changes on sharing object
        list<Sharing_History__c> lstSharingHistory = new list<Sharing_History__c>();
        //set for opportunity ids
        set<Id> setOppIds= new set<Id>();
        //get all required fields info of new Opportunity team member 
        map<id,list<OpportunityTeamMember>>  mapOppwithNoCampaignlistTeam = new  map<id,list<OpportunityTeamMember>>();
        map<id,list<Opportunity>>  mapOppwithPartId = new  map<id,list<Opportunity>>();
        list<OpportunityTeamMember>  lstAlTeam = [select id, UserId,OpportunityId,TeamMemberRole,Opportunity.Ownerid, OpportunityAccessLevel from OpportunityTeamMember where Id in:setids];
        for(OpportunityTeamMember objOppTeamMember: lstAlTeam)
        {  
           list<OpportunityTeamMember> lstTempTeam = new list<OpportunityTeamMember>(); 
           if(mapOppwithNoCampaignlistTeam.containskey(objOppTeamMember.OpportunityId))
           {
             lstTempTeam  = mapOppwithNoCampaignlistTeam.get(objOppTeamMember.OpportunityId);
           }      
           lstTempTeam.add(objOppTeamMember);
           mapOppwithNoCampaignlistTeam.put(objOppTeamMember.OpportunityId, lstTempTeam);         
           //To check if Opportunity owner not included in Opportunity Team members
       // if(objOppTeamMember.UserId != objOppTeamMember.Opportunity.Ownerid) - comented out - we need to track deal team for the owner too        
           setOppIds.add(objOppTeamMember.OpportunityId);
                      
        }
        
        list<Opportunity> lstOppDealTeam = [Select Id,(Select Id,ownerid,Name From Opportunities__r),(Select  Name,User.Alias From OpportunityTeamMembers) From Opportunity where id In: setOppIds];
        for(Opportunity objOpportunity :lstOppDealTeam)
        {
            //Populate all Opportunity Team member name on Opportunity Deal team
            string usrName = '';
            for(OpportunityTeamMember objOpportunityTeamMember: objOpportunity.OpportunityTeamMembers)
            {
             usrName = usrName+ objOpportunityTeamMember.User.Alias +', ';
            }
            if(usrName.contains(','))
                usrName = usrName.removeEnd(', ');
            objOpportunity.Deal_Team__c = usrName;
            mapOppwithPartId.put(objOpportunity.Id,objOpportunity.Opportunities__r);
        
        }
        //Get all campaigns associated with opportunity Team member opportunity
        list<Campaign> lstCampaign = [select id,Original_Deal_Opportunity__c from Campaign where Original_Deal_Opportunity__c In:setOppIds];
        list<CampaignShare> lstCampaignShare = new list<CampaignShare>();
         
        // list<OpportunityShare> lstOpportunityShare = new list<OpportunityShare>();
        for(OpportunityTeamMember objOppTeamMember: lstAlTeam )
        {
               system.debug(objOppTeamMember+'----objOppTeamMember---');
               for(Campaign objCamp: lstCampaign )
               {
                if(mapOppwithNoCampaignlistTeam.containskey(objCamp.Original_Deal_Opportunity__c))
                  mapOppwithNoCampaignlistTeam.remove(objCamp.Original_Deal_Opportunity__c);
                    //Create object of sharing history to insert sharing details
                   
                    Sharing_History__c objShareHis = new Sharing_History__c();
                    objShareHis.Access_Level__c = objOppTeamMember.OpportunityAccessLevel;
                    objShareHis.Opportunity__c = objOppTeamMember.OpportunityId;
                    objShareHis.User_or_Group__c = objOppTeamMember.UserId;
                    objShareHis.Action__c = 'Created';
                    objShareHis.Campaign__c = objCamp.Id;
                    objShareHis.User_Role__c = objOppTeamMember.TeamMemberRole;             
                    lstSharingHistory.add(objShareHis);
                    
                   //New sharing records will be created for each campaign as per opportunity Team member   
                    system.debug(objOppTeamMember.OpportunityAccessLevel+'-----objOppTeamMember.OpportunityAccessLevel---'+objCamp);
                    CampaignShare obj = new CampaignShare();
                    obj.UserOrGroupId = objOppTeamMember.UserId;
                    obj.CampaignAccessLevel = objOppTeamMember.OpportunityAccessLevel;
                    obj.CampaignId = objCamp.Id;
                    lstCampaignShare.add(obj);
              }
        }
         if(mapOppwithNoCampaignlistTeam.size()>0)
        {
            
             for(Id OppId : mapOppwithNoCampaignlistTeam.keyset())
            {
                for(OpportunityTeamMember objTeam : mapOppwithNoCampaignlistTeam.get(OppId))
                {
                    Sharing_History__c objShareHis = new Sharing_History__c();
                    objShareHis.Access_Level__c = objTeam.OpportunityAccessLevel;
                    objShareHis.Opportunity__c = objTeam.OpportunityId;
                    objShareHis.User_or_Group__c = objTeam.UserId;
                    objShareHis.Action__c = 'Created';                  
                    objShareHis.User_Role__c = objTeam.TeamMemberRole;              
                    lstSharingHistory.add(objShareHis);
                }
        
            }
        }
         if(lstOppDealTeam.size()>0)
          update lstOppDealTeam;
         if(lstCampaignShare.size()>0)
          insert lstCampaignShare;
         if(lstSharingHistory.size()>0)
          insert lstSharingHistory;
  
  }
  // This method is used by trigger AddRemoveApexSharing on Update operation
  // This methods create sharing records for existing campaign records and exiting Oppotunity Team members which are being updated
   @future(callout=true)
   public static void UpdateprocessSharing(set<id> setids)
  {
       //This to track the changes on sharing object
        list<Sharing_History__c> lstSharingHistory = new list<Sharing_History__c>();
         //get all required fields info of updated Opportunity team member 
        list<OpportunityTeamMember>  lstAlTeam = [select id, UserId ,OpportunityId,TeamMemberRole, OpportunityAccessLevel from OpportunityTeamMember where Id in:setids];
        map<Id,list<OpportunityTeamMember>> mapOpplistTeam = new map<Id,list<OpportunityTeamMember>>();
        map<Id,list<OpportunityTeamMember>> mapOppwithNoCampaignlistTeam = new map<Id,list<OpportunityTeamMember>>();
        list<CampaignShare> lstUpdateCampaignShare = new list<CampaignShare >();
        
        //Create a map to associate all Opportunity Team member with key with Opportunity Id
        for(OpportunityTeamMember objOppTeamMember: lstAlTeam )
        {   
           list<OpportunityTeamMember> lstTempTeam = new list<OpportunityTeamMember>(); 
           if(mapOpplistTeam.containskey(objOppTeamMember.OpportunityId))
           {
             lstTempTeam  = mapOpplistTeam.get(objOppTeamMember.OpportunityId);
           }      
           lstTempTeam.add(objOppTeamMember);
           mapOpplistTeam.put(objOppTeamMember.OpportunityId, lstTempTeam);
        }  
        mapOppwithNoCampaignlistTeam = mapOpplistTeam;
        map<id,list<OpportunityShare>> mapOppwithPartId = new map<id,list<OpportunityShare>>();
         for(OpportunityShare objOpportunity :[Select o.UserOrGroupId, o.Opportunity.Parent_Opportunity__c, o.OpportunityId, o.OpportunityAccessLevel,  o.Id From OpportunityShare o where o.Opportunity.Parent_Opportunity__c In: mapOpplistTeam.keyset() and o.RowCause!='Rule'])
        {
            list<OpportunityShare> lstTemp = new list<OpportunityShare>();
            if(mapOppwithPartId.containskey(objOpportunity.Opportunity.Parent_Opportunity__c))
            {
             lstTemp = mapOppwithPartId.get(objOpportunity.Opportunity.Parent_Opportunity__c);
            }
            lstTemp.add(objOpportunity);
            mapOppwithPartId.put(objOpportunity.Opportunity.Parent_Opportunity__c,lstTemp);
        
        }
        system.debug(mapOppwithPartId+'---mapOppwithPartId--'+mapOppwithPartId.size());
        //Get all campaign share and Campaign associated with opportunity
        for(Campaign objCamp: [select id,Original_Deal_Opportunity__c,  (Select Id, CampaignId, UserOrGroupId From Shares) from Campaign where Original_Deal_Opportunity__c In:mapOpplistTeam.keyset()])
        {
            if(mapOppwithNoCampaignlistTeam.containskey(objCamp.Original_Deal_Opportunity__c))
              mapOppwithNoCampaignlistTeam.remove(objCamp.Original_Deal_Opportunity__c);
          //for loop on share records 
          for(CampaignShare objShare :objCamp.Shares)
          {
            if(mapOpplistTeam.containskey(objCamp.Original_Deal_Opportunity__c))
            //Get opporutnity Team member by opportunity ids
            for(OpportunityTeamMember objTeam : mapOpplistTeam.get(objCamp.Original_Deal_Opportunity__c))
            {
                
               //only update campaign share records which was created for given Opporunity Team member
               if(objShare.UserOrGroupId == objTeam.UserId)
               {
                    Sharing_History__c objShareHis = new Sharing_History__c();
                    objShareHis.Access_Level__c = objTeam.OpportunityAccessLevel;
                    objShareHis.Opportunity__c = objTeam.OpportunityId;
                    objShareHis.User_or_Group__c = objTeam.UserId;
                    objShareHis.Action__c = 'Updated';
                    objShareHis.Campaign__c = objCamp.Id;
                    objShareHis.User_Role__c = objTeam.TeamMemberRole;              
                    lstSharingHistory.add(objShareHis);
                    
                    objShare.CampaignAccessLevel = objTeam.OpportunityAccessLevel ;
                   lstUpdateCampaignShare.add(objShare);
               }
            }
          
          }
        }
       // list<OpportunityShare> listOppShareUpdate = new list<OpportunityShare>();
        if(mapOppwithNoCampaignlistTeam.size()>0)
        {
            for(Id OppId : mapOppwithNoCampaignlistTeam.keyset())
            {
                for(OpportunityTeamMember objTeam : mapOppwithNoCampaignlistTeam.get(OppId))
                {
                
                    Sharing_History__c objShareHis = new Sharing_History__c();
                    objShareHis.Access_Level__c = objTeam.OpportunityAccessLevel;
                    objShareHis.Opportunity__c = OppId;
                    objShareHis.User_or_Group__c = objTeam.UserId;
                    objShareHis.Action__c = 'Updated';                  
                    objShareHis.User_Role__c = objTeam.TeamMemberRole;              
                    lstSharingHistory.add(objShareHis);
                }
            }
          }        
           
      /*  for(OpportunityTeamMember objTeam : lstAlTeam)
        {
            if(mapOppwithPartId.containsKey(objTeam.OpportunityId))
            {
              list<OpportunityShare> listOppShare = mapOppwithPartId.get(objTeam.OpportunityId);
              system.debug(listOppShare.size()+'----listOppShare---'+listOppShare);
              for(OpportunityShare objOpportunityShare: listOppShare)
              {
                system.debug(objTeam.UserId+'-1---listOppShare---'+objOpportunityShare.UserOrGroupId);
                if(objTeam.UserId == objOpportunityShare.UserOrGroupId)
                {
                  objOpportunityShare.OpportunityAccessLevel  = objTeam.OpportunityAccessLevel;
                  listOppShareUpdate.add(objOpportunityShare);
                }
              }
            
            }                   
        }
            */
      //system.debug(listOppShareUpdate+'---listOppShareUpdate--'+listOppShareUpdate.size());
        
        //Update campaign share records
        if(lstUpdateCampaignShare.size()>0)
         update lstUpdateCampaignShare;
        if(lstSharingHistory.size()>0)
          insert lstSharingHistory;
  
        //if(listOppShareUpdate.size()>0)
       // update listOppShareUpdate;
     }
     //Its part of method to get role subordinate
      public  set<Id> getSubordinateRoles(Id roleId) {
        map<Id, set<Id>> parentAndChildren = new map<Id, set<Id>>();
        set<Id> children;
        for(UserRole ur : [select Id, ParentRoleId from UserRole]) {
            children = parentAndChildren.containsKey(ur.ParentRoleId) ? parentAndChildren.get(ur.ParentRoleId) : new set<Id>();
            children.add(ur.Id);
            parentAndChildren.put(ur.ParentRoleId, children);
        }
        return getSubordinateRoles(roleId, parentAndChildren);
      }
      
    
    //This method convert set into string for dynamic query
     public String quoteKeySet(Set<Id> KeySet)
     {
        String newSetStr = '' ;
        for(Id str : KeySet)
            newSetStr += '\'' + str + '\',';

        newSetStr = newSetStr.lastIndexOf(',') > 0 ? '(' + newSetStr.substring(0,newSetStr.lastIndexOf(',')) + ')' : newSetStr ;
       System.debug('quoteKeySet() :  newSetStr ============ ' + newSetStr);   

        return newSetStr;

     }
     //This method used to create a set of role subordinate  
      public  set<Id> getSubordinateRoles(Id roleId, map<Id, set<Id>> parentAndChildren) 
      {
            set<Id> subordinateRoles = new set<Id>();
            set<Id> remainingSubordinateRoles = new set<Id>();
           if(parentAndChildren.containsKey(roleId)) 
           {
              subordinateRoles.addAll(parentAndChildren.get(roleId));
                for(Id subRoleId : subordinateRoles) 
                {
                   remainingSubordinateRoles.addAll(getSubordinateRoles(subRoleId, parentAndChildren));
                }
             }
            subordinateRoles.addAll(remainingSubordinateRoles);
            return subordinateRoles;
       }
      
       //Get all the role
      public static List<SelectOption> Roles() 
      {
        List<SelectOption> lsrRole = new List<SelectOption>();
        lsrRole.add(new SelectOption('','All'));
        for(UserRole obj: [Select Id, Name from UserRole])       
        {
          lsrRole.add(new SelectOption(obj.Id,obj.Name));
        }
        return lsrRole;
     }
}