PROD_10-24-19/force-app/main/default/objects/Campaign/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Campaign/fields/Original_Deal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Original_Deal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Deal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Campaign/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Similar to the opportunity custom Private checkbox. This will hidden from the users &amp; populated by a trigger. If a campaign is Private then the Bid and Campaign Members are also private.</description>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Campaign/recordTypes/BFIN.recordType-meta.xml
<RecordType>
    <fullName>BFIN</fullName>
    <active>true</active>
    <description>BFIN Campaigns used for Deal Listings and Marketing</description>
    <label>BFIN</label>
</RecordType>

PROD-9-26-19/force-app/main/default/objects/Campaign/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Fund Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Office_Country__c.field-meta.xml
<CustomField>
    <fullName>Office_Country__c</fullName>
    <label>Office Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the Opportunity as Private making it visible to only the Opportunity Owner and Opportunity Team Members</description>
    <inlineHelpText>Check this box to make it private to all users except the Opportunity Owner and the Opportunity Team Members</inlineHelpText>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD-12120/force-app/main/default/classes/Test_PopulateCampaignStatus.cls
@isTest(SeeAllData=true)
private class Test_PopulateCampaignStatus{
  static testMethod void CreateCampaign(){     

    // Set up the Account record.    

    Account objAcc = TestFactory.buildTestAcc(1, UserInfo.getUserId());
    insert objAcc;
    system.debug('----+Test objAcc ****' + objAcc);
    Opportunity  objOpp = new Opportunity (Name='Test Opp', private__c=false, AccountId=objAcc.Id,Office_Country__c='India',StageName='New', CloseDate=system.today());
    //SS: 9/9/19 inserted IV record as it is become required by NewOpportunityName class.(next 3 lines including sytem debug.)
    Investment_Vehicle__c iv = TestFactory.buildInvestmentVehicle('test');
    insert iv;
     system.debug('----+Test IV record %%%%%' + iv);
    objOpp.Investment_Vehicle__c = iv.id;
    system.debug('----+Test Opportunity ****' + objOpp);
    insert objOpp;
    
    list<user> lstUser= [select id from user where  Profile.Name like :'%BFIN%' and Id !=: userinfo.getuserid() and IsActive = true limit 2];
    
    list<OpportunityTeamMember> lstOpportunityTeamMember  = new list<OpportunityTeamMember>();
    
    OpportunityTeamMember otm = new OpportunityTeamMember(TeamMemberRole = 'Account Manager', OpportunityId = objOpp.Id, UserId = lstUser[0].id );
    lstOpportunityTeamMember.add(otm);
    OpportunityTeamMember otm1 = new OpportunityTeamMember(TeamMemberRole = 'Account Manager', OpportunityId = objOpp.Id, UserId = lstUser[1].id );
    lstOpportunityTeamMember.add(otm1);
    insert lstOpportunityTeamMember;
    //SS: 9/9/19 added debugline
    system.debug('----+Test lstOpportunityTeamMember *-*-*-*' + lstOpportunityTeamMember);
 
      /* BF-25: Share is no longer writeable due to sharing updates

      List<OpportunityShare> oppShareList = [SELECT id, UserOrGroupId, OpportunityAccessLevel, RowCause FROM OpportunityShare
                                              WHERE OpportunityId = : objOpp.id and RowCause =: 'Team'];
      for(OpportunityShare oppShare : oppShareList)
      {
          oppShare.OpportunityAccessLevel = 'Edit';
      }
      
      update oppShareList;
      system.debug('----+Test oppShareList---' + oppShareList); 
     */  
    list<Campaign> lstCampaign = new list<Campaign>();
    
    Campaign objcam = new Campaign(Name='Test Campaign',Original_Deal_Opportunity__c=objOpp.id,Status ='Active',IsActive=true);
    //--SS: 9/9/19 comented out due to isolate "cannot specify ID on insert exception  
    //Campaign objcam1 = new Campaign(Name='new Campaign',Original_Deal_Opportunity__c=objOpp.id,Status ='Active',IsActive=true);
    system.debug('----+Test Campaign1---' + objcam);
    
    lstCampaign.add(objcam);
   //-- SS: 9/9/19 comented out due to isolate "cannot specify ID on insert exception
   //lstCampaign.add(objcam1);
    insert lstCampaign;
    lstCampaign = new list<Campaign>();
    objcam.name = 'Campaign';
   //-- SS: 9/9/19 comented out due to isolate "cannot specify ID on insert exception
   //objcam1.name = 'campaign test';
    lstCampaign.add(objcam);
   //-- SS: 9/9/19 comented out due to isolate "cannot specify ID on insert exception
   //lstCampaign.add(objcam1);
    update lstCampaign;
    objOpp.private__c = true;
    update objOpp;    
   
  }
}