PROD_10-24-19/force-app/main/default/objects/Campaign/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Campaign/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect Specific</fullName>
            </value>
            <value>
                <fullName>Sleeve</fullName>
            </value>
            <value>
                <fullName>Fund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Campaign/recordTypes/Brookfield_Diligence_Portal.recordType-meta.xml
<RecordType>
    <fullName>Brookfield_Diligence_Portal</fullName>
    <active>true</active>
    <label>Brookfield Diligence Portal</label>
</RecordType>

PROD-12-18-19/force-app/main/default/objects/Campaign/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/CampaignMember/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/Case/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Contact/fields/DX_Email__c.field-meta.xml
<CustomField>
    <fullName>DX_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>DX Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canadian Pooled Fund</fullName>
            </value>
            <value>
                <fullName>Closed End Fund</fullName>
            </value>
            <value>
                <fullName>General Overview</fullName>
            </value>
            <value>
                <fullName>Hedge Fund</fullName>
            </value>
            <value>
                <fullName>Listed Issuers</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Private Fund - Open Ended</fullName>
            </value>
            <value>
                <fullName>Private Fund</fullName>
            </value>
            <value>
                <fullName>Separate Accounts</fullName>
            </value>
            <value>
                <fullName>Separately Managed Account</fullName>
            </value>
            <value>
                <fullName>UCITS</fullName>
            </value>
            <value>
                <fullName>Co-Invest</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Sale of Asset</fullName>
            </value>
            <value>
                <fullName>Private Fund - Closed Ended</fullName>
            </value>
            <value>
                <fullName>SMA</fullName>
            </value>
            <value>
                <fullName>Direct Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/Test_Campaign_Handler.cls
@isTest
private  class Test_Campaign_Handler {
  
  @testSetup
  static void setupTestData(){
      Contact testContact = new Contact(FirstName='Test', LastName='TestlastName',Email='test@test.com',DX_Email__c ='test@test21.com');
        insert testContact;    
      
      Investment_Vehicle__c testInvestmentVehicle = new Investment_Vehicle__c(Vehicle_Type__c = 'Co-Invest');
      insert testInvestmentVehicle;
      Account accobj = new Account(Name ='TestAccount' );
      insert accobj;
      Investment_Vehicle__c testInvestmentVehicleobj = [select id from Investment_Vehicle__c limit 1];
      Fund_Vehicle__c Sleeveobj = new Fund_Vehicle__c(Name='Test',Investment_Vehicle__c=testInvestmentVehicleobj.id);
      insert Sleeveobj;
     
  }
    
  	static testMethod void test_CreateFundraisingCampaignEvents(){
      Contact contact_Obj =[Select id from Contact limit 1];    
      Account acc = [select name from Account limit 1];
      RecordType rt = [select Id from RecordType where SobjectType='Campaign' and DeveloperName like '%Brookfield_Diligence_Portal%' limit 1];
      List<Campaign> campaign_Objlst = new List<Campaign>();   
      Fund_Vehicle__c objSleeve =  [select name from Fund_Vehicle__c limit 1];
      campaign_Objlst.add(new Campaign(Name = 'Test',Status='Deactivated',Room_Type__c ='Fund',RecordTypeId=rt.Id,Account__c = acc.Id)); 
      campaign_Objlst.add(new Campaign(Name = 'Test1',Status='Planned',Room_Type__c ='Prospect Specific',RecordTypeId=rt.Id,Account__c = acc.Id));     
      List<CampaignMember> campaignmember_Obj = new List<CampaignMember>();
      test.startTest();       
      insert campaign_Objlst;       
      List<Campaign> campaign_Obj1  =  [SELECT Name,RecordTypeId,Status,Room_Type__c from Campaign ];            
      System.assertEquals(true,campaign_Obj1.size()>0);
        for(Campaign c:campaign_Obj1)
        {
            campaignmember_Obj.add(new CampaignMember(CampaignId = c.id,ContactId =contact_Obj.id));
            c.Status = 'Active';
        }      	
      Insert campaignmember_Obj;       
      update campaign_Obj1;	
      test.stopTest();
    
  }
    //Test case to check functionality for duplicate entry for same Fund
    static testMethod void test_checkDuplicateCampaignForFund(){
        Investment_Vehicle__c testInvestmentVehicleobj = [select id from Investment_Vehicle__c limit 1];
        Account acc = [select name from Account limit 1];
        RecordType rt = [select Id from RecordType where SobjectType='Campaign' and DeveloperName like '%Brookfield_Diligence_Portal%' limit 1];
        Campaign campaign_Obj1 = new Campaign(Name = 'Test',Status='Active',Room_Type__c ='Fund',RecordTypeId=rt.Id,Account__c = acc.Id, Investment_Vehicle__c=testInvestmentVehicleobj.Id);
        insert campaign_Obj1;
        test.startTest();        
      	Campaign campaign_ObjDuplicate = new Campaign(Name = 'Test',Status='Active',Room_Type__c ='Fund',RecordTypeId=rt.Id,Account__c = acc.Id, Investment_Vehicle__c=testInvestmentVehicleobj.Id);
        try {
        insert campaign_ObjDuplicate;
        }
        catch(Exception duplicate){
            System.assert(duplicate.getMessage().contains('Duplicate Error:Campaign with Investment Vehilcle alredy exist'), duplicate.getMessage());        
        }         
        test.stopTest();
    }
    static testMethod void test_DeleteFundraisingCampaignEvents(){
      Contact contact_Obj =[Select id from Contact limit 1];    
      Account acc = [select name from Account limit 1];
      RecordType rt = [select Id from RecordType where SobjectType='Campaign' and DeveloperName like '%Brookfield_Diligence_Portal%' limit 1];
      List<Campaign> campaign_Objlst = new List<Campaign>();   
      Fund_Vehicle__c objSleeve =  [select name from Fund_Vehicle__c limit 1];
      campaign_Objlst.add(new Campaign(Name = 'Test',Status='Active',Room_Type__c ='Fund',RecordTypeId=rt.Id,Account__c = acc.Id)); 
      campaign_Objlst.add(new Campaign(Name = 'Test1',Status='Active',Room_Type__c ='Prospect Specific',RecordTypeId=rt.Id,Account__c = acc.Id));     
      List<CampaignMember> campaignmember_Obj = new List<CampaignMember>();
      test.startTest();       
      insert campaign_Objlst;       
      List<Campaign> campaign_Obj1  =  [SELECT Name,RecordTypeId,Status,Room_Type__c from Campaign limit 1]; 
        List<Campaign> cmLst = new List<Campaign>();
      System.assertEquals(true,campaign_Obj1.size()>0);
        for(Campaign c:campaign_Obj1)
        {
            campaignmember_Obj.add(new CampaignMember(CampaignId = c.id,ContactId =contact_Obj.id));
            //c.Status = 'Active';
            cmLst.add(c);
        }     
        
        update cmLst;
      Insert campaignmember_Obj;
       delete campaignmember_Obj;      
      test.stopTest();
    
  }
}