PROD-9-26-19/force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If &quot;To Be Deleted&quot; is selected, all related Activities, Contacts, etc. will also be deleted.  If &quot;To Be Merged&quot; is selected, Activities, Contacts, etc. will reside under the merged Account.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To Be Merged</fullName>
            </value>
            <value>
                <fullName>Out of Business</fullName>
            </value>
            <value>
                <fullName>To be discussed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>Canada - BC</fullName>
                <isActive>false</isActive>
                <label>Canada - BC</label>
            </value>
            <value>
                <fullName>Canada - Federal</fullName>
                <isActive>false</isActive>
                <label>Canada - Federal</label>
            </value>
            <value>
                <fullName>Canada - ON</fullName>
                <isActive>false</isActive>
                <label>Canada - ON</label>
            </value>
            <value>
                <fullName>Canada - QC</fullName>
                <isActive>false</isActive>
                <label>Canada - QC</label>
            </value>
            <value>
                <fullName>MISO/PJM/Louisianna/TVA</fullName>
                <isActive>false</isActive>
                <label>MISO/PJM/Louisianna/TVA</label>
            </value>
            <value>
                <fullName>US - California/Arizona</fullName>
                <isActive>false</isActive>
                <label>US - California/Arizona</label>
            </value>
            <value>
                <fullName>US - Connecticut</fullName>
                <isActive>false</isActive>
                <label>US - Connecticut</label>
            </value>
            <value>
                <fullName>US - Federal</fullName>
                <isActive>false</isActive>
                <label>US - Federal</label>
            </value>
            <value>
                <fullName>US - Maine</fullName>
                <isActive>false</isActive>
                <label>US - Maine</label>
            </value>
            <value>
                <fullName>US - Massachusetts</fullName>
                <isActive>false</isActive>
                <label>US - Massachusetts</label>
            </value>
            <value>
                <fullName>US - New England</fullName>
                <isActive>false</isActive>
                <label>US - New England</label>
            </value>
            <value>
                <fullName>US - New York</fullName>
                <isActive>false</isActive>
                <label>US - New York</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Fund Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Long_Name__c</fullName>
    <label>Fund Long Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Corporate Credit</fullName>
            </value>
            <value>
                <fullName>Corporate High Yield</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Opportunities</fullName>
            </value>
            <value>
                <fullName>Energy Infrastructure</fullName>
            </value>
            <value>
                <fullName>Equity Opportunities</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
            <value>
                <fullName>Investments</fullName>
            </value>
            <value>
                <fullName>Opportunistic MBS</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Real Asset Debt</fullName>
            </value>
            <value>
                <fullName>Real Asset Solutions</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Securitized Credit</fullName>
            </value>
            <value>
                <fullName>Specialty Funds</fullName>
            </value>
            <value>
                <fullName>Strategic Income</fullName>
            </value>
            <value>
                <fullName>Timberland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Short Listed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>General Interest</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Pre-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Fully Divested</fullName>
            </value>
            <value>
                <fullName>Wound Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canadian Pooled Fund</fullName>
            </value>
            <value>
                <fullName>Closed End Fund</fullName>
            </value>
            <value>
                <fullName>General Overview</fullName>
            </value>
            <value>
                <fullName>Hedge Fund</fullName>
            </value>
            <value>
                <fullName>Listed Issuers</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Private Fund - Open Ended</fullName>
            </value>
            <value>
                <fullName>Private Fund</fullName>
            </value>
            <value>
                <fullName>Separate Accounts</fullName>
            </value>
            <value>
                <fullName>Separately Managed Account</fullName>
            </value>
            <value>
                <fullName>UCITS</fullName>
            </value>
            <value>
                <fullName>Co-Invest</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Sale of Asset</fullName>
            </value>
            <value>
                <fullName>Private Fund - Closed Ended</fullName>
            </value>
            <value>
                <fullName>SMA</fullName>
            </value>
            <value>
                <fullName>Direct Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle_Close_Date__c/Investment_Vehicle_Close_Date__c.object-meta.xml
<CustomObject>
    <description>BF-26: Investment Vehicle Close Dates</description>
    <label>Investment Vehicle Close Date</label>
    <nameField>
        <label>Close Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicle Close Dates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle_Close_Date__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>BF-26: Related Investment Vehicle</description>
    <inlineHelpText>Related Investment Vehicle</inlineHelpText>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Investment Vehicle Close Dates</relationshipLabel>
    <relationshipName>Investment_Vehicle_Close_Dates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/classes/CSL_Test_InvestmentVehicle.cls
@isTest(SeeAllData=false)
public class CSL_Test_InvestmentVehicle  {

    /**
      * Ensure that an investment vehicle close date linked to an opp. cannot be deleted
      */
    public static testMethod void testInvestCloseDates() {
        // Insert Account
        Account acct = new Account(
                            RecordTypeId = '0120b000000B0QUAA0',
                            Name = 'TestCo',
                            Account_Status__c = 'Active',
                            BillingCountry = 'Canada',
                            BillingCity = 'Toronto'
                       );
        insert acct;

        // Add Investment Vehicle
        Investment_Vehicle__c iv = new Investment_Vehicle__c(
                                        Name = 'test vehicle',
                                        Long_Name__c = 'test vehicle',
                                        Vehicle_Type__c = 'Private Fund',
                                        Status__c = 'Marketing',
                                        Platform__c = 'Agriculture',
                                        RecordTypeId = '01233000000MIBHAA4'
                                   );
        insert iv;

        // Add Investment Vehicle Close Dates 
        Investment_Vehicle_Close_Date__c ivCloseDateFirst = new Investment_Vehicle_Close_Date__c(
                                                                Active__c = true,
                                                                Name = 'x',
                                                                Close_Date__c = Date.today() + 30,
                                                                Close_Type__c = 'First',
                                                                Investment_Vehicle__c = iv.Id
                                                           );
        Investment_Vehicle_Close_Date__c ivCloseDateLast  = new Investment_Vehicle_Close_Date__c(
                                                                Active__c = true,
                                                                Name = 'x',
                                                                Close_Date__c = Date.today() + 300,
                                                                Close_Type__c = 'Final',
                                                                Investment_Vehicle__c = iv.Id
                                                            );
        List<Investment_Vehicle_Close_Date__c> closeDateList = new List<Investment_Vehicle_Close_Date__c>{ivCloseDateFirst,ivCloseDateLast};
        insert closeDateList;

        // Add Opportunity
        Opportunity opp = new Opportunity(
                                RecordTypeId = '01240000000MHIDAA4',
                                AccountId = acct.Id,
                                Name = 'test opp',
                                Investment_Vehicle__c = iv.Id,
                                CloseDate = (Date.today() + 15),
                                Amount = 50000000,
                                StageName = '1: Prospect identified',
                                Investment_Vehicle_Close_Date__c = ivCloseDateFirst.Id
                          );
        insert opp;

        // Update Close Date
        Investment_Vehicle_Close_Date__c ivCloseDateUpdate = new Investment_Vehicle_Close_Date__c(
                                                                    Id = ivCloseDateFirst.Id,
                                                                    Close_Date__c = Date.today() + 35
                                                             );
        update ivCloseDateUpdate;

        opp = [SELECT Id, CloseDate
               FROM Opportunity
               WHERE Id = :opp.Id];
        system.assertEquals((Date.today() + 35), opp.CloseDate);

        // Delete fund close date
        try {
            delete ivCloseDateFirst;
        }   catch (Exception ex) {
            system.debug('CSL_Test_InvestmentVehicle :: testIvCloseDateDeleteValidation :: ex=' + ex.getMessage());
        }

    }

    public static testMethod void testBatchOppCloseDates() {
        // Insert Account
        Account acct = new Account(
                            RecordTypeId = '0120b000000B0QUAA0',
                            Name = 'TestCo',
                            Account_Status__c = 'Active',
                            BillingCountry = 'Canada',
                            BillingCity = 'Toronto'
                       );
        insert acct;

        // Add Investment Vehicle
        Investment_Vehicle__c iv = new Investment_Vehicle__c(
                                        Name = 'test vehicle',
                                        Long_Name__c = 'test vehicle',
                                        Vehicle_Type__c = 'Private Fund',
                                        Status__c = 'Marketing',
                                        Platform__c = 'Agriculture',
                                        RecordTypeId = '01233000000MIBHAA4'
                                   );
        insert iv;

        // Add Opportunity (before close dates so list will be blank)
        Opportunity opp = new Opportunity(
                                RecordTypeId = '01240000000MHIDAA4',
                                AccountId = acct.Id,
                                Name = 'test opp',
                                Investment_Vehicle__c = iv.Id,
                                CloseDate = (Date.today() + 15),
                                Amount = 50000000,
                                StageName = '1: Prospect identified'/*,
                                Investment_Vehicle_Close_Date__c = ivCloseDateFirst.Id*/
                          );
        insert opp;

        // Add Investment Vehicle Close Dates 
        Investment_Vehicle_Close_Date__c ivCloseDateFirst = new Investment_Vehicle_Close_Date__c(
                                                                Active__c = true,
                                                                Name = 'x',
                                                                Close_Date__c = Date.today() + 30,
                                                                Close_Type__c = 'First',
                                                                Investment_Vehicle__c = iv.Id
                                                           );
        Investment_Vehicle_Close_Date__c ivCloseDateLast  = new Investment_Vehicle_Close_Date__c(
                                                                Active__c = true,
                                                                Name = 'x',
                                                                Close_Date__c = Date.today() + 300,
                                                                Close_Type__c = 'Final',
                                                                Investment_Vehicle__c = iv.Id
                                                            );
        List<Investment_Vehicle_Close_Date__c> closeDateList = new List<Investment_Vehicle_Close_Date__c>{ivCloseDateFirst,ivCloseDateLast};
        insert closeDateList;

        // Schedule and run batch job
        CSL_Batch_Opportunity_FundCloseDates bj = new CSL_Batch_Opportunity_FundCloseDates(25);
        String sch = '0 0 21 * * ?'; // Daily @ 9pm
        String jobID = System.schedule('Test - Opp Fund Close Date Job', sch, bj);

        Test.startTest();
        Database.executeBatch(bj);
        Test.stopTest();
        
    }

}