PROD-9-26-19/force-app/main/default/objects/Account/fields/BIM_Primary_Mktg_Rep__c.field-meta.xml
<CustomField>
    <fullName>BIM_Primary_Mktg_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSG Primary Mktg Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/Company_Background__c.field-meta.xml
<CustomField>
    <fullName>Company_Background__c</fullName>
    <description>Historical information about the account</description>
    <inlineHelpText>Historical information about the account</inlineHelpText>
    <label>Firm Background</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/ERISA__c.field-meta.xml
<CustomField>
    <fullName>ERISA__c</fullName>
    <description>Identify if an Account falls under the Employee Retirement Income Security Act..</description>
    <inlineHelpText>Identify if an Account falls under the Employee Retirement Income Security Act..</inlineHelpText>
    <label>ERISA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>To be Determined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/Investor_Type__c.field-meta.xml
<CustomField>
    <fullName>Investor_Type__c</fullName>
    <description>Inventory Type field has been referred on following places:
Opportunity: 
Field Name: Reporting_Investor_Type__c, Investor_Type__c, Account_Type__c
-----
Investor Position: 
Field Name: Investor_Type__c
                       Reporting_Investor_Type__c
-----
Compliance: 
Field Name: Investor_Type__c
---
Object: Investor Position
Field: Classification 
Action: Optimized formula which was fixed by Pal yesterday. 
https://na57.salesforce.com/00N33000002QBXu?setupid=CustomObjects</description>
    <inlineHelpText>Type of investor of the Account</inlineHelpText>
    <label>Investor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Asset Manager</fullName>
            </value>
            <value>
                <fullName>Bank / Financial Institution</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Endowment / Foundation</fullName>
            </value>
            <value>
                <fullName>Government / Sovereign Wealth</fullName>
            </value>
            <value>
                <fullName>Hospitals / Health Care</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Labor Organization</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Multi Family Office</fullName>
            </value>
            <value>
                <fullName>Non-Investor</fullName>
            </value>
            <value>
                <fullName>OCIO</fullName>
            </value>
            <value>
                <fullName>Private Bank / Wirehouse</fullName>
            </value>
            <value>
                <fullName>Private Pension</fullName>
            </value>
            <value>
                <fullName>Public Pension</fullName>
            </value>
            <value>
                <fullName>RIA / Wealth Manager</fullName>
            </value>
            <value>
                <fullName>Single Family Office</fullName>
            </value>
            <value>
                <fullName>UHNW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/PFG_CRM_Primary_Lead__c.field-meta.xml
<CustomField>
    <fullName>PFG_CRM_Primary_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PFG Primary Lead or in the case of split coverage, this would indicate Real Estate coverage.</description>
    <inlineHelpText>Primary Lead or in the case of split coverage, this would indicate Real Estate coverage.</inlineHelpText>
    <label>Real Estate Lead</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PFG_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>Canada - BC</fullName>
                <isActive>false</isActive>
                <label>Canada - BC</label>
            </value>
            <value>
                <fullName>Canada - Federal</fullName>
                <isActive>false</isActive>
                <label>Canada - Federal</label>
            </value>
            <value>
                <fullName>Canada - ON</fullName>
                <isActive>false</isActive>
                <label>Canada - ON</label>
            </value>
            <value>
                <fullName>Canada - QC</fullName>
                <isActive>false</isActive>
                <label>Canada - QC</label>
            </value>
            <value>
                <fullName>MISO/PJM/Louisianna/TVA</fullName>
                <isActive>false</isActive>
                <label>MISO/PJM/Louisianna/TVA</label>
            </value>
            <value>
                <fullName>US - California/Arizona</fullName>
                <isActive>false</isActive>
                <label>US - California/Arizona</label>
            </value>
            <value>
                <fullName>US - Connecticut</fullName>
                <isActive>false</isActive>
                <label>US - Connecticut</label>
            </value>
            <value>
                <fullName>US - Federal</fullName>
                <isActive>false</isActive>
                <label>US - Federal</label>
            </value>
            <value>
                <fullName>US - Maine</fullName>
                <isActive>false</isActive>
                <label>US - Maine</label>
            </value>
            <value>
                <fullName>US - Massachusetts</fullName>
                <isActive>false</isActive>
                <label>US - Massachusetts</label>
            </value>
            <value>
                <fullName>US - New England</fullName>
                <isActive>false</isActive>
                <label>US - New England</label>
            </value>
            <value>
                <fullName>US - New York</fullName>
                <isActive>false</isActive>
                <label>US - New York</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/QI_Status_Notes__c.field-meta.xml
<CustomField>
    <fullName>QI_Status_Notes__c</fullName>
    <label>QI Status Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/recordTypes/Consultant.recordType-meta.xml
<RecordType>
    <fullName>Consultant</fullName>
    <active>true</active>
    <label>Consultant</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/Campaign/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Campaign/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

PROD-9-26-19/force-app/main/default/objects/Contact/fields/PFG_CRM_Lead__c.field-meta.xml
<CustomField>
    <fullName>PFG_CRM_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PFG_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Fund Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Long_Name__c</fullName>
    <label>Fund Long Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canadian Pooled Fund</fullName>
            </value>
            <value>
                <fullName>Closed End Fund</fullName>
            </value>
            <value>
                <fullName>General Overview</fullName>
            </value>
            <value>
                <fullName>Hedge Fund</fullName>
            </value>
            <value>
                <fullName>Listed Issuers</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Private Fund - Open Ended</fullName>
            </value>
            <value>
                <fullName>Private Fund</fullName>
            </value>
            <value>
                <fullName>Separate Accounts</fullName>
            </value>
            <value>
                <fullName>Separately Managed Account</fullName>
            </value>
            <value>
                <fullName>UCITS</fullName>
            </value>
            <value>
                <fullName>Co-Invest</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Sale of Asset</fullName>
            </value>
            <value>
                <fullName>Private Fund - Closed Ended</fullName>
            </value>
            <value>
                <fullName>SMA</fullName>
            </value>
            <value>
                <fullName>Direct Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Erisa__c.field-meta.xml
<CustomField>
    <fullName>Erisa__c</fullName>
    <label>ERISA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>To be Determined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Investor_Type__c.field-meta.xml
<CustomField>
    <fullName>Investor_Type__c</fullName>
    <formula>TEXT( Account.Investor_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Investor Type</label>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/classes/TestFactory.cls
/*****************************************************************************************************************
ss: 6/11/19 Modified to update the account method to accomodate the City and Country exception/validation. (Appended line # 26)

*****************************************************************************************************************/
@isTest public class TestFactory {

    public static User buildTestUser(Integer i, String profilename) {
   
    User u = new User();
    u.Alias = 'TESTABS';
    u.Email='ABS@Brownfield.com';
    u.EmailEncodingKey='UTF-8';
    u.LastName='TestABS' + i;
    u.LanguageLocaleKey='en_US';
    u.LocaleSidKey='en_US';
    u.ProfileId = [SELECT Id FROM profile where name =:profilename].id; 
    u.TimeZoneSidKey='America/Los_Angeles';
    u.UserName='ABS@Brownfield.com' + i;
    return u;
    }

    public static Account buildTestAcc(Integer i, Id testUserId) {  
        Account TestAccount = new Account();
        TestAccount.Name = 'Test ' + Math.round(Math.random()*1000) + ' Account ' + Math.round(Math.random()*1000);
        TestAccount.BillingCity = Math.round(Math.random()*1000) + ' city ' + Math.round(Math.random()*1000);
        TestAccount.BillingCountry = 'United States'; 
        TestAccount.Company_Background__c = 'Initial Company background';
        TestAccount.Investor_Type__c = 'Consultant';
        TestAccount.QI_Status_Notes__c = 'Initial QI Status Note'; 
        TestAccount.ERISA__c = 'No'; 
        TestAccount.RecordTypeId = '0120b000000B0QU';
        if(null != testUserId) {
            Id userId = [SELECT Id FROM User where Id =:testUserId].id;
            TestAccount.PFG_CRM_Primary_lead__c = userId;
            TestAccount.BIM_Primary_Mktg_Rep__c = userId;
        }
    
        return TestAccount;
    }
    
    public static Contact buildTestCon(Integer i, Id testUserId, Account Acc) {
           
    Contact TestContact = new Contact();
    TestContact.FirstName = 'Test Contact FirstName';
    TestContact.LastName = 'Test Contact LastName' + i;
    TestContact.Account = Acc;
    TestContact.AccountId = Acc.Id;
    TestContact.PFG_CRM_Lead__c = [SELECT Id FROM User where Id =:testUserId].id;
   
    return TestContact;
    
    }

    public static Opportunity buildTestOpp(Integer i, Id testUserId, String RecordType, Account testAccId) {
    
    // Query for Opportunity record types
    List<RecordType> Opprtypes = [Select Name, Id From RecordType where sObjectType='Opportunity' and isActive=true];

    //Create a map between the Record Type Name and Id for easy retrieval
    Map<String,String> opportunityRecordTypes = new Map<String,String>{};
    for(RecordType rt: Opprtypes)
    opportunityRecordTypes.put(rt.Name,rt.Id);
       
    Opportunity TestOpp = new Opportunity();
    TestOpp.ownerId = testUserId;
    TestOpp.RecordTypeId = opportunityRecordTypes.get(RecordType);
    TestOpp.Name = 'testOpp' + i;
    TestOpp.StageName = '1 - Identified as Prospect';
    TestOpp.CloseDate = Date.today();
    TestOpp.Amount = 1;
    //Item added to increase coverage and avoid Process Builder failures on Created Opportunities.
    TestOpp.AccountID= testAccId.ID;

    Investment_Vehicle__c iv = TestFactory.buildInvestmentVehicle('test');
    insert iv;
    TestOpp.Investment_Vehicle__c = iv.id;
   
    return TestOpp;
    
    }
    
    public static Task buildTestTasks(Integer i, Id testUserId, Id RelatedId) {
       
    Task TestTask = new Task();
    TestTask.ownerId = testUserId;
    TestTask.whatId = RelatedId;
    TestTask.Subject = 'This is test task # ' + i;
    TestTask.ActivityDate = Date.today();
  
    return TestTask;
    
    }
    
    public static Event buildTestEvents(Integer i, Id testUserId, Id RelatedId) {
       
    Event TestEvent = new Event();
    TestEvent.ownerId = testUserId;
    TestEvent.whatId = RelatedId;
    TestEvent.Subject = 'This is test Event # ' + i;
    TestEvent.ActivityDate = Date.today();
    TestEvent.ActivityDateTime = Date.today();
    TestEvent.DurationInMinutes = 50;
   
    return TestEvent;
    
    }

    public static Campaign createCampaign(String campaignName, boolean isPSG) {
        Campaign c = new Campaign(Name = campaignName, IsActive = true);
        if(isPSG) {
            c.RecordTypeId = '0120b0000001IsF';
        }
        return c;
    }

    public static Account queryAccount(Id accountId) {
        return [SELECT Id
                FROM Account
                WHERE Id = :accountId];
    }

    public static Investment_Vehicle__c buildInvestmentVehicle(String invVehicleName) {
        return new Investment_Vehicle__c(Name = invVehicleName, Long_Name__c = invVehicleName, 
                                         Vehicle_Type__c = 'General Overview', Platform__c = 'Infrastructure');
    }

}