PROD-9-26-19/force-app/main/default/objects/Account/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <label>Consultant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/recordTypes/Consultant.recordType-meta.xml
<RecordType>
    <fullName>Consultant</fullName>
    <active>true</active>
    <label>Consultant</label>
</RecordType>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant Relationship</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Consultant Rel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultant Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Consultant_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Fund Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Fund_Series__c.field-meta.xml
<CustomField>
    <fullName>Fund_Series__c</fullName>
    <description>Replaced &quot;Mandate - Series Family&quot; Field Type Change from Txt to Picklist 7/25/19</description>
    <inlineHelpText>Fund Family Series Previously &quot;Mandate - Series Family&quot;</inlineHelpText>
    <label>Fund Series</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>BBCP</fullName>
            </value>
            <value>
                <fullName>BBRF</fullName>
            </value>
            <value>
                <fullName>BBTF</fullName>
            </value>
            <value>
                <fullName>BCOF</fullName>
            </value>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>BGTF</fullName>
            </value>
            <value>
                <fullName>BID (EURO)</fullName>
            </value>
            <value>
                <fullName>BID (USD)</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BOZ</fullName>
            </value>
            <value>
                <fullName>BPREP</fullName>
            </value>
            <value>
                <fullName>BPREPA</fullName>
            </value>
            <value>
                <fullName>BREF</fullName>
            </value>
            <value>
                <fullName>BREOF</fullName>
            </value>
            <value>
                <fullName>Bridge</fullName>
            </value>
            <value>
                <fullName>BSIP</fullName>
            </value>
            <value>
                <fullName>BSREF</fullName>
            </value>
            <value>
                <fullName>BSREP</fullName>
            </value>
            <value>
                <fullName>CDN Office</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>DTLA</fullName>
            </value>
            <value>
                <fullName>GGP</fullName>
            </value>
            <value>
                <fullName>India RE</fullName>
            </value>
            <value>
                <fullName>Kotak</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Peninsula</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>RETIP</fullName>
            </value>
            <value>
                <fullName>Spec Opps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canadian Pooled Fund</fullName>
            </value>
            <value>
                <fullName>Closed End Fund</fullName>
            </value>
            <value>
                <fullName>General Overview</fullName>
            </value>
            <value>
                <fullName>Hedge Fund</fullName>
            </value>
            <value>
                <fullName>Listed Issuers</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Private Fund - Open Ended</fullName>
            </value>
            <value>
                <fullName>Private Fund</fullName>
            </value>
            <value>
                <fullName>Separate Accounts</fullName>
            </value>
            <value>
                <fullName>Separately Managed Account</fullName>
            </value>
            <value>
                <fullName>UCITS</fullName>
            </value>
            <value>
                <fullName>Co-Invest</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Sale of Asset</fullName>
            </value>
            <value>
                <fullName>Private Fund - Closed Ended</fullName>
            </value>
            <value>
                <fullName>SMA</fullName>
            </value>
            <value>
                <fullName>Direct Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Office__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Office</relationshipLabel>
    <relationshipName>Office</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</description>
    <inlineHelpText>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</inlineHelpText>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advised Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Field_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Field_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Consultant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Consultant__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Field Consultant)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Research_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Research_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Consultant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Research Consultant)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/recordTypes/PFG.recordType-meta.xml
<RecordType>
    <fullName>PFG</fullName>
    <active>true</active>
    <businessProcess>PFG</businessProcess>
    <description>Private Funds Default Opportunity Type</description>
    <label>PFG</label>
</RecordType>

PROD-9-26-19/force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Relationship__c/fields/Field_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Field_Consultant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Field Consultant</label>
    <type>Checkbox</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Relationship__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Relationship__c/recordTypes/Consultant.recordType-meta.xml
<RecordType>
    <fullName>Consultant</fullName>
    <active>true</active>
    <description>Account to Account relationships between Consultant Accounts and Client Accounts</description>
    <label>Consultant</label>
</RecordType>

PROD_10-24-19/force-app/main/default/classes/TEST_Opportunity_Handler.cls
@isTest (SeeAllData=false)
private with sharing class TEST_Opportunity_Handler {
    @TestSetup
    private static void setup() {
        Account testAccount = new Account(Name='Test Account');
        insert testAccount;

        Account testConsultant = new Account(Name='Test Consultant');
        insert testConsultant;

        Contact testContact = new Contact(FirstName='Test', LastName='Consultant');
        insert testContact;

        Investment_Vehicle__c testInvestmentVehicle = new Investment_Vehicle__c(Vehicle_Type__c = 'Co-Invest');
        insert testInvestmentVehicle;
    }

    private static testMethod void TEST_createConsultantRelationship() {
        Account testAccount = [select Id from Account where Name='Test Account' limit 1];
        Account testConsultant = [select Id from Account where Name='Test Consultant' limit 1];
        Investment_Vehicle__c testInvestmentVehicle = [select Id from Investment_Vehicle__c limit 1];
        RecordType rt = [select Id from RecordType where SobjectType='Opportunity' and DeveloperName like '%PSG%' limit 1];

        Opportunity o = new Opportunity(Name='Test Opportunity', AccountId=testAccount.Id, Consultant__c=testConsultant.Id, Investment_Vehicle__c=testInvestmentVehicle.Id, StageName='Test Stage Name', CloseDate=System.today(), RecordTypeId=rt.Id);
        insert o;

        system.assertEquals(1, [select Id from Consultant__c].size());

        update o;

        system.assertEquals(1, [select Id from Consultant__c].size());
    }

    private static testMethod void TEST_createFieldConsultantRelationship() {
        Account testAccount = [select Id from Account where Name='Test Account' limit 1];
        Contact testContact = [select Id from Contact limit 1];
        Investment_Vehicle__c testInvestmentVehicle = [select Id from Investment_Vehicle__c limit 1];
        RecordType rt = [select Id from RecordType where SobjectType='Opportunity' and DeveloperName like '%PSG%' limit 1];

        Opportunity o = new Opportunity(Name='Test Opportunity', AccountId=testAccount.Id, Field_Consultant__c=testContact.Id, Investment_Vehicle__c=testInvestmentVehicle.Id, StageName='Test Stage Name', CloseDate=System.today(), RecordTypeId=rt.Id);
        insert o;

        system.assertEquals(1, [select Id from Relationship__c].size());

        update o;

        system.assertEquals(1, [select Id from Relationship__c].size());
    }

    private static testMethod void TEST_createResearchConsultantRelationship() {
        Account testAccount = [select Id from Account where Name='Test Account' limit 1];
        Contact testContact = [select Id from Contact limit 1];
        Investment_Vehicle__c testInvestmentVehicle = [select Id from Investment_Vehicle__c limit 1];
        RecordType rt = [select Id from RecordType where SobjectType='Opportunity' and DeveloperName like '%PSG%' limit 1];

        Opportunity o = new Opportunity(Name='Test Opportunity', AccountId=testAccount.Id, Research_Consultant__c=testContact.Id, Investment_Vehicle__c=testInvestmentVehicle.Id, StageName='Test Stage Name', CloseDate=System.today(), RecordTypeId=rt.Id);
        insert o;

        system.assertEquals(1, [select Id from Relationship__c].size());

        update o;

        system.assertEquals(1, [select Id from Relationship__c].size());
    }

    private static testMethod void TEST_NewOpportunityName() {
        Account testAccount = [select Id from Account where Name='Test Account' limit 1];
        Contact testContact = [select Id from Contact limit 1];
        Investment_Vehicle__c testInvestmentVehicle = [select Id from Investment_Vehicle__c limit 1];
        RecordType rt = [select Id from RecordType where SobjectType='Opportunity' and Name like '%PFG%' limit 1];

        Office__c testOffice = new Office__c(Name='Test Office', Account__c=testAccount.Id);
        insert testOffice;

        Investment_Vehicle__c testInvestmentVehicle2 = new Investment_Vehicle__c(Vehicle_Type__c = 'Separate Accounts');
        insert testInvestmentVehicle2;

        Investment_Vehicle__c testInvestmentVehicle3 = new Investment_Vehicle__c();
        insert testInvestmentVehicle3;

        Opportunity o = new Opportunity(Name='Test Opportunity', AccountId=testAccount.Id, Research_Consultant__c=testContact.Id, Investment_Vehicle__c=testInvestmentVehicle.Id, Office__c=testOffice.Id, StageName='Closed Won', CloseDate=System.today(), RecordTypeId=rt.Id);
        Opportunity o2 = new Opportunity(Name='Test Opportunity 2' , AccountId=testAccount.Id, Research_Consultant__c=testContact.Id, Investment_Vehicle__c=testInvestmentVehicle2.Id, Office__c=testOffice.Id, StageName='Closed Won', CloseDate=System.today(), RecordTypeId=rt.Id);
        Opportunity o3 = new Opportunity(Name='Test Opportunity 3' , AccountId=testAccount.Id, Research_Consultant__c=testContact.Id, Investment_Vehicle__c=testInvestmentVehicle3.Id, StageName='Closed Won', CloseDate=System.today(), RecordTypeId=rt.Id);
        insert new List<Opportunity>{o,o2,o3};

        Account a = new Account(Name='Test Account 2');
        insert a;

        testOffice.Account__c = a.Id;
        update testOffice;

        o.AccountId=a.Id;
        update o;

        Test.startTest();
        Investment_Vehicle__c testInvestmentVehicle4 = new Investment_Vehicle__c(Fund_Series__c='AG');
        insert testInvestmentVehicle4;

        o3.Investment_Vehicle__c = testInvestmentVehicle2.Id;
        update o3;
        Test.stopTest();


    }
}