PROD-9-26-19/force-app/main/default/objects/Account/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <label>Consultant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant Relationship</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Consultant Rel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultant Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Consultant_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Current_Commitments_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Commitments_USD__c</fullName>
    <inlineHelpText>Roll up from most recent Investor Position records totalling the Current Commitments in the Fund in USD.

Current commitment is how much has been currently invested + available for drawndown left.</inlineHelpText>
    <label>Current Commitments - USD</label>
    <summarizedField>Investor_Position__c.Current_Commitments_USD__c</summarizedField>
    <summaryFilterItems>
        <field>Investor_Position__c.Is_Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Investor_Position__c.Investment_Vehicle__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Number_of_Current_Investors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Current_Investors__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Roll up from most recent 3rd Party Investor Position records totalling the unique Investors in the Fund.</inlineHelpText>
    <label>Number of Current Investors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Number_of_Historical_Investors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Historical_Investors__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Roll up from most recent 3rd Party Investor Position records totaling the original unique investors of the Fund.</inlineHelpText>
    <label>Number of Historical Investors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/Investor_Position__c.object-meta.xml
<CustomObject>
    <label>Investor Position</label>
    <nameField>
        <label>Investor Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investor Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/As_of__c.field-meta.xml
<CustomField>
    <fullName>As_of__c</fullName>
    <label>As of</label>
    <type>Date</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/As_of_Is_last_quater__c.field-meta.xml
<CustomField>
    <fullName>As_of_Is_last_quater__c</fullName>
    <formula>If(AND(
CEILING( MONTH(  As_of__c  ) / 3 ) =  CASE(CEILING( MONTH( TODAY() ) / 3), 1,4,2,1,3,2,4,1,0) ,
Today() - As_of__c &lt; 184,
Today() - As_of__c &gt; 0
), &quot;Yes&quot;, &quot;No&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>As of Is last  quater</label>
    <type>Text</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/As_of_Last_quater_text__c.field-meta.xml
<CustomField>
    <fullName>As_of_Last_quater_text__c</fullName>
    <label>As of Last quater text</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advised Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions_Consultant</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/Current_Commitments_Functional__c.field-meta.xml
<CustomField>
    <fullName>Current_Commitments_Functional__c</fullName>
    <inlineHelpText>Imported field of Current Commitments in the Fund in Functional Currency.

Current commitment is how much has been currently invested + available for drawndown.</inlineHelpText>
    <label>Current Commitments - Func. Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Current_Commitments_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Commitments_USD__c</fullName>
    <inlineHelpText>Imported field of Current Commitments in the Fund in USD. 

Current commitment is how much has been currently invested + available for drawdown.</inlineHelpText>
    <label>Current Commitments - USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investor_Position__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle</value>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please DO NOT Create Investor Position for Inactive, Discontinued, Closed Vehicles</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Investor_Position_Account__c.field-meta.xml
<CustomField>
    <fullName>Investor_Position_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Investor Account record</description>
    <inlineHelpText>New Investor Account record</inlineHelpText>
    <label>Investor Position Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investor Positions (All)</relationshipLabel>
    <relationshipName>Investor_Positions2</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copied from originating opportunity. Populates automatically.</inlineHelpText>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/Source_of_Capital__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Capital__c</fullName>
    <label>Source of Capital</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Limited Partners</fullName>
            </value>
            <value>
                <fullName>Sponsors</fullName>
            </value>
            <value>
                <fullName>Principals</fullName>
            </value>
            <value>
                <fullName>Cross Commitment</fullName>
            </value>
            <value>
                <fullName>Sub-Investor</fullName>
            </value>
            <value>
                <fullName>Operating Partner</fullName>
            </value>
            <value>
                <fullName>Seed</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>BAM Employees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</description>
    <inlineHelpText>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</inlineHelpText>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advised Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Source_of_Capital__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Capital__c</fullName>
    <label>Source of Capital</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Limited Partners</fullName>
            </value>
            <value>
                <fullName>Sponsors</fullName>
            </value>
            <value>
                <fullName>Principals</fullName>
            </value>
            <value>
                <fullName>Cross Commitment</fullName>
            </value>
            <value>
                <fullName>Sub-Investor</fullName>
            </value>
            <value>
                <fullName>Operating Partner</fullName>
            </value>
            <value>
                <fullName>BAM Employees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/Test_InvestorPositionTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=false)
private class Test_InvestorPositionTrigger {
        
    static testMethod void myUnitTest() {
    	
    	
      
       		Account account = new Account(Name='Test' );
    		insert account;
    		Account account1 = new Account(Name='Test1' );
    		insert account1;
    		Investment_Vehicle__c invvehicle = new Investment_Vehicle__c(Name='TestInvestmentVehicle');
    		insert invvehicle;
        //SS: 7/18/18 added following line of code for code coverage
        Opportunity opt = new Opportunity(Name = 'NewTestOpportunity', StageName ='2 - Initiated General Contact', CloseDate = system.today() , Investment_Vehicle__c = invvehicle.id, AccountId = account.id,  Consultant__c = account.id  );
        insert opt;
        //Opportunity opt1 = new Opportunity(Name = 'NewTestOpportunity1', StageName ='2 - Initiated General Contact', CloseDate = system.today() , Investment_Vehicle__c = invvehicle.id, AccountId = account.id,  Consultant__c = account.id  );
        //insert opt1;
    		Investor_Position__c invposition = new Investor_Position__c(As_of__c= System.Today() - 89 , Current_Commitments_Functional__c = 100000, Investor_Position_Account__c = account.Id, Investment_Vehicle__c = invvehicle.Id, Name='TestInvestorPosition', Source_of_Capital__c = 'Operating Partner', Is_Active__c=true, Opportunity_Name__c = opt.id, Current_Commitments_USD__c = 0);
    		insert invposition;
    		Investor_Position__c invposition1 = new Investor_Position__c(As_of__c= System.Today() -89 , Investor_Position_Account__c = account1.Id, Investment_Vehicle__c = invvehicle.Id, Name='TestInvestorPosition', Source_of_Capital__c = 'Operating Partner', Is_Active__c=true, Opportunity_Name__c = opt.id, Current_Commitments_USD__c = 0);
    		insert invposition1;
        //SS: 7/18/18 end of the change.
        test.startTest();
        
        //SS: 7/18/18 updated following line of code : From: As_of_Last_quater_text__c TO: As_of_Is_last_quater__c
        List<Investor_Position__c> InvPositionlst = [Select Id,As_of_Is_last_quater__c,As_of__c from Investor_Position__c where Investment_Vehicle__c =: invvehicle.Id];
        for(Investor_Position__c inv : InvPositionlst)
        {
        	 System.debug( 'test2323' + inv.As_of_Is_last_quater__c);
        	 System.debug('test2323' + inv.As_of__c);
       }
       system.debug('Test Investment Positions: ' + InvPositionlst.size());
        // SS: 7/18/18 end of change. 
        System.assertequals(InvPositionlst.size(),2);
      
       List<Investment_Vehicle__c> TestInvestmentVehicle = [Select Number_of_Historical_Investors__c, Number_of_Current_Investors__c from Investment_Vehicle__c where Id =: invvehicle.Id];
      System.assertequals(TestInvestmentVehicle.size(),1);
      //
      System.debug('....Historical Investor -1 .......'+TestInvestmentVehicle[0].Number_of_Historical_Investors__c);
      System.debug('....Current Investor -1 .......'+TestInvestmentVehicle[0].Number_of_Current_Investors__c);
       //
     	System.assertequals(TestInvestmentVehicle[0].Number_of_Historical_Investors__c,2);
       System.assertequals(TestInvestmentVehicle[0].Number_of_Current_Investors__c,1); 
       
       delete invposition;
       
         List<Investment_Vehicle__c> TestInvestmentVehicle1 = [Select Number_of_Historical_Investors__c, Number_of_Current_Investors__c from Investment_Vehicle__c where Id =: invvehicle.Id];
      System.assertequals(TestInvestmentVehicle1.size(),1);
      System.debug('....Historical Investor -2 .......'+TestInvestmentVehicle1[0].Number_of_Historical_Investors__c);
      System.debug('....Current Investor -2 .......'+TestInvestmentVehicle1[0].Number_of_Current_Investors__c);
     	System.assertequals(TestInvestmentVehicle1[0].Number_of_Historical_Investors__c,1);
      System.assertequals(TestInvestmentVehicle1[0].Number_of_Current_Investors__c,0);
       
       
        
        test.stopTest();

    }
   
    
}