PROD-12-18-19/force-app/main/default/objects/Account_Summary__c/Account_Summary__c.object-meta.xml
<CustomObject>
    <label>Property Enquiries</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Property Inquiries ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Account_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Account_Summary__c/fields/Account_Summary__c.field-meta.xml
<CustomField>
    <fullName>Account_Summary__c</fullName>
    <label>Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account_Summary__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>IF(ISBLANK(IDIG_Region__c), Text(Country__c) ,IDIG_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account_Summary__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Account_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status (Text)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Pre-Acquisition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/GroupByAccountsController.cls
Public Class GroupByAccountsController {
     transient List<Account_Summary__c > lstKeyAccountsWithSummary = new List<Account_Summary__c >();
     // public List<Account> lstKeyAccounts = new List<Account>();
    public Map<String,list<Account_Summary__c>> objectMap {get; set;}
    
    public void loadKeyAccounts() {
        
        Date d = system.today().addDays(-31);
        
                          
        lstKeyAccountsWithSummary = [SELECT Id,Account_Summary__c,Account__r.Name,Country__c,Name,Property__c,Property__r.name,Status__c,lastModifiedDate,Location__c 
                                        FROM Account_Summary__c 
                                        WHERE LastModifiedDate > :d  order by  Status__c, Location__c , Property__r.name ];
                                        //WHERE Account__c IN :lstKeyAccounts  order by  Status__c, Location__c , Property__r.name ];
                                        
        objectMap  = new Map<String,list<Account_Summary__c>>();
        for(Account_Summary__c a : lstKeyAccountsWithSummary ){
           if(objectMap.keySet().contains(a.Account__r.Name) ){
               objectMap.get(a.Account__r.Name).add(a);
           }
           else{
               objectMap.put(a.Account__r.Name,new list<Account_Summary__c >());
               objectMap.get(a.Account__r.Name).add(a);
           } 
        }
        
        System.debug('++++++++++++++objectMap+++++++++++++ :'+objectMap);
    }
    
    public pageReference renderAsPdf(){
        PageReference pageRef = new PageReference('/apex/GroupByAccountReportPdf');
            pageRef .setRedirect(true);
            return pageRef;
    }
}