PROD-9-26-19/force-app/main/default/objects/Campaign/fields/Original_Deal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Original_Deal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Deal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Campaign/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Similar to the opportunity custom Private checkbox. This will hidden from the users &amp; populated by a trigger. If a campaign is Private then the Bid and Campaign Members are also private.</description>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Campaign/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/CampaignMember/fields/Bid_Probability__c.field-meta.xml
<CustomField>
    <fullName>Bid_Probability__c</fullName>
    <label>Bid Probability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/CampaignMember/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

PROD-9-26-19/force-app/main/default/objects/Lead/fields/Office_Country__c.field-meta.xml
<CustomField>
    <fullName>Office_Country__c</fullName>
    <label>Office Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Kazakhstan</fullName>
            </value>
            <value>
                <fullName>Kosovo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Office_Country__c.field-meta.xml
<CustomField>
    <fullName>Office_Country__c</fullName>
    <label>Office Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the Opportunity as Private making it visible to only the Opportunity Owner and Opportunity Team Members</description>
    <inlineHelpText>Check this box to make it private to all users except the Opportunity Owner and the Opportunity Team Members</inlineHelpText>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD-9-26-19/force-app/main/default/classes/Test_CampaignMemberFollowUpTestData.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
public class Test_CampaignMemberFollowUpTestData {

    public static testMethod void createTestData() {
            
        // Create Campaign, Account and Group Test Records
       
        Account testAccount = new Account(name='test_account', NumberOfEmployees=190);
        //Group testQueueName = new Group(name='test_queue', Type='Queue');
        
        insert testAccount;
        Opportunity  objOpp = new Opportunity (Name='Test Opp', private__c=false, AccountId=testAccount.Id,Office_Country__c='India',StageName='New', CloseDate=system.today());
        insert objOpp;
         Campaign testCampaign = new Campaign(name='test_campaign', Original_Deal_Opportunity__c=objOpp.id,Status ='Active',IsActive=true); 
         insert testCampaign;           
        // Define Lists for Contact Lead and Campaign Member Test Records
        Contact[] testContactList = new Contact[]{};
        
        CampaignMember[] testCampaignMemberList = new CampaignMember[]{};   
            
        // Query for newly created Test Campaign and Account
        testCampaign = [select id, name, status, ownerId from campaign where name = 'test_campaign' order by name desc limit 1];
        testAccount = [select id, name from account where name = 'test_account'];
        //testQueue = [Select SobjectType, QueueId, Id From QueueSobject where QueueId =:testQueueName.Id limit 1];
        
        // Create 30 Test Contacts
        for(Integer i = 0; i < 30; i++){
            testContactList.add(new Contact(FirstName='New',lastname='test_contact_' + i, Title='Chef', MailingPostalCode='806'+i, accountId = testAccount.Id));
        }
        insert testContactList;
            
        
       
         //  string  filterTitle ='  Contact.Name LIKE \'Title+%\'';
        // Query for newly created Test Contacts and Leads
        testContactList = [select id, name from contact where name like '%test_contact_%' order by name];
        
            
        // Assign Test Contacts to Test Campaign
        for(Integer x = 0; x < testContactList.size(); x++){
            testCampaignMemberList.add(new CampaignMember(
                campaignId = testCampaign.Id,
                contactId = testContactList[x].Id, 
                status = 'Prospect',
                Bid_Probability__c = 'Medium'));
        }
            
            
            
        // Insert List of Test Campaign Members
        insert testCampaignMemberList;
        testCampaignMemberList[0].Status = 'Passed';
        update testCampaignMemberList;
        testCampaignMemberList[1].Status = null;
        update testCampaignMemberList;
        
        delete testCampaignMemberList[0];
    }
}