PROD-9-26-19/force-app/main/default/objects/Campaign/fields/Original_Deal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Original_Deal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Deal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Campaign/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Similar to the opportunity custom Private checkbox. This will hidden from the users &amp; populated by a trigger. If a campaign is Private then the Bid and Campaign Members are also private.</description>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Campaign/recordTypes/BFIN.recordType-meta.xml
<RecordType>
    <fullName>BFIN</fullName>
    <active>true</active>
    <description>BFIN Campaigns used for Deal Listings and Marketing</description>
    <label>BFIN</label>
</RecordType>

PROD-9-26-19/force-app/main/default/objects/Campaign/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Office_Country__c.field-meta.xml
<CustomField>
    <fullName>Office_Country__c</fullName>
    <label>Office Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used when splitting an opportunity</inlineHelpText>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Child Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the Opportunity as Private making it visible to only the Opportunity Owner and Opportunity Team Members</description>
    <inlineHelpText>Check this box to make it private to all users except the Opportunity Owner and the Opportunity Team Members</inlineHelpText>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD-12120/force-app/main/default/classes/Test_AddRemoveApexSharing.cls
@isTest(SeeAllData=true)
private class Test_AddRemoveApexSharing 
{
 static testMethod void apexSharing()
 {
    Test.startTest();

    Datetime dt = Datetime.now();
    Account objAcc = TestFactory.buildTestAcc(1, UserInfo.getUserId());
    insert objAcc;
    
    Opportunity  objOpp = new Opportunity (Name='Test Opp', private__c=false, AccountId=objAcc.Id,Office_Country__c='India',StageName='New', CloseDate=system.today(),RecordTypeId='01240000000MFYYAA4');
    insert objOpp;

    Opportunity  objOppNoCampaign = new Opportunity (Name='Test Opp - No Campaign', private__c=false, AccountId=objAcc.Id,Office_Country__c='India',StageName='New', CloseDate=system.today(),RecordTypeId='01240000000MFYYAA4');
    insert objOppNoCampaign;
    
     list<user> lstUser= [select id from user where  Profile.Name like :'%BFIN%' and Id !=: userinfo.getuserid() and IsActive = true limit 2];
    list<OpportunityTeamMember> lstOpportunityTeamMember  = new list<OpportunityTeamMember>();
    OpportunityTeamMember otm = new OpportunityTeamMember(TeamMemberRole = 'Account Manager', OpportunityId = objOpp.Id, UserId = lstUser[0].id );
    OpportunityTeamMember otmnc = new OpportunityTeamMember(TeamMemberRole = 'Account Manager', OpportunityId = objOppNoCampaign.Id, UserId = lstUser[0].id );
    lstOpportunityTeamMember.add(otm);
    lstOpportunityTeamMember.add(otmnc);
    
    insert lstOpportunityTeamMember;
     List<OpportunityShare> oppShareList = [SELECT id, UserOrGroupId, OpportunityAccessLevel, RowCause FROM OpportunityShare
                                               WHERE OpportunityId = : objOpp.id and RowCause =: 'Team'];
    /*
        BF-25: Share is no longer writeable due to sharing updates

        for(OpportunityShare oppShare : oppShareList) {
            oppShare.OpportunityAccessLevel = 'Edit';
        }       
        update oppShareList;
    */
       
       otm.TeamMemberRole = 'Contact Manager';
    update otm;
    list<Campaign> lstCampaign = new list<Campaign>();
    Campaign objcam = new Campaign(Name='Test Campaign',Original_Deal_Opportunity__c=objOpp.id,Status ='Active',IsActive=true,RecordTypeId='01240000000MFaUAAW');
    Campaign objcam1 = new Campaign(Name='new Campaign',Original_Deal_Opportunity__c=objOpp.id,Status ='Active',IsActive=true,RecordTypeId='01240000000MFaUAAW');
    lstCampaign.add(objcam);
 //   lstCampaign.add(objcam1);
    insert lstCampaign;
    lstOpportunityTeamMember = new list<OpportunityTeamMember>();
    OpportunityTeamMember otm1 = new OpportunityTeamMember(TeamMemberRole = 'Account Manager', OpportunityId = objOpp.Id, UserId = lstUser[0].id );
    OpportunityTeamMember otm1nc = new OpportunityTeamMember(TeamMemberRole = 'Account Manager', OpportunityId = objOppNoCampaign.Id, UserId = lstUser[0].id );
    lstOpportunityTeamMember.add(otm1);
    lstOpportunityTeamMember.add(otm1nc);
    
     Opportunity  objchildOpp = new Opportunity (Name='child Opp', Parent_Opportunity__c =objOpp.Id, AccountId=objAcc.Id,Office_Country__c='India',StageName='New', CloseDate=system.today());
    insert objchildOpp;
    insert lstOpportunityTeamMember;
    oppShareList = new List<OpportunityShare>();
    oppShareList  = [select id from OpportunityShare  WHERE OpportunityId = : objOpp.id and RowCause =: 'Team' and UserOrGroupId =:lstUser[0].id];

    
    /*
        BF-25: Share is no longer writeable due to sharing updates

        for(OpportunityShare oppShare : oppShareList ) {
            oppShare.OpportunityAccessLevel = 'Read';
        }       
        update oppShareList;
    */

    Test.stopTest();
       //otm.TeamMemberRole = 'Contact Manager';
       //update otm;
       try
       {
       delete lstOpportunityTeamMember;
       }catch(exception ex)
       {
        system.debug(ex);
       }
      // oppShareList = new List<OpportunityShare>();
     // oppShareList  = [select id from OpportunityShare  WHERE OpportunityId = : objOpp.id and RowCause =: 'Team' and UserOrGroupId =:lstUser[0].id];
     // for(OpportunityShare oppShare : oppShareList )
      // {
       //   oppShare.OpportunityAccessLevel = 'Read';
      // }       
      // update oppShareList;
      // delete otm1;
 }


}