WMG112519/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Fund Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission__c/Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <displayFormat>PM-{000000000}</displayFormat>
        <label>Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Permission__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Permission__c/fields/Account_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Account_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Account_Vehicle__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Permission__c/fields/Finaccount__c.field-meta.xml
<CustomField>
    <fullName>Finaccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commitment</label>
    <referenceTo>Finaccount__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Permission__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission__c/fields/Permission_Type__c.field-meta.xml
<CustomField>
    <fullName>Permission_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Type</label>
    <referenceTo>Permission_Type__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/Permission_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Permission Configuration</label>
    <pluralLabel>Permission Configurations</pluralLabel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Columns__c.field-meta.xml
<CustomField>
    <fullName>Columns__c</fullName>
    <label>Columns</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Contact_Security_Field__c.field-meta.xml
<CustomField>
    <fullName>Contact_Security_Field__c</fullName>
    <inlineHelpText>A field on the Contact of the current user, that allows the system to determine if the user has permission to make updates to a permission record.</inlineHelpText>
    <label>Contact Security Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Display_Alert_Icons__c.field-meta.xml
<CustomField>
    <fullName>Display_Alert_Icons__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Alert Icons</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Header_Angle__c.field-meta.xml
<CustomField>
    <fullName>Header_Angle__c</fullName>
    <label>Header Angle</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Parent_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Field__c</fullName>
    <defaultValue>&quot;Account__c&quot;</defaultValue>
    <label>Parent Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Permission_Security_Field__c.field-meta.xml
<CustomField>
    <fullName>Permission_Security_Field__c</fullName>
    <label>Permission Security Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Primary_Junction_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Junction_Object_Type__c</fullName>
    <defaultValue>&quot;Contact&quot;</defaultValue>
    <description>The primary object that will be used for all permission records created</description>
    <label>Primary Junction Object Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Related_Object_Widgets__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Widgets__c</fullName>
    <label>Related Object Widgets</label>
    <type>TextArea</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Configuration__mdt/fields/Save_Mode__c.field-meta.xml
<CustomField>
    <fullName>Save_Mode__c</fullName>
    <label>Save Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Active Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission_Type__c/Permission_Type__c.object-meta.xml
<CustomObject>
    <label>Permission Type</label>
    <nameField>
        <label>Permission Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Permission_Type__c/fields/Default_Active__c.field-meta.xml
<CustomField>
    <fullName>Default_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Active</label>
    <type>Checkbox</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission_Type__c/fields/Default_Alert__c.field-meta.xml
<CustomField>
    <fullName>Default_Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Alert</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/SmartWidget__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SmartWidget</label>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Related_Field__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Related_Field__c</fullName>
    <label>AutoComplete Related Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Search_Filter__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Search_Filter__c</fullName>
    <label>AutoComplete Search Filter</label>
    <type>TextArea</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Search_Object__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Search_Object__c</fullName>
    <label>AutoComplete Search Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Target_Field__c</fullName>
    <label>AutoComplete Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Target_Object__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Target_Object__c</fullName>
    <label>AutoComplete Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Target_Parent_Field__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Target_Parent_Field__c</fullName>
    <label>AutoComplete Target Parent Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12120/force-app/main/default/classes/TEST_RelatedMultiSelect.cls
@isTest(SeeAllData=false)
public with sharing class TEST_RelatedMultiSelect {
    private static final String NAMESPACE = '';

    @testSetup
    static void setupTest(){
        //Create PermissionConfig
        //Create SmartWidgets
        List<SmartWidget__c> smartWidgets = new List<SmartWidget__c>();

        SmartWidget__c relatedContacts = new SmartWidget__c();
        relatedContacts.Name = 'PermissionExample_RelatedContacts';
        relatedContacts.AutoComplete_Target_Field__c = 'Name,Email';
        relatedContacts.AutoComplete_Target_Object__c = NAMESPACE+'Permission__c';
        relatedContacts.AutoComplete_Search_Object__c = 'Contact';
        relatedContacts.AutoComplete_Search_Filter__c = 'Id IN (\'securityGroups\')';
        relatedContacts.AutoComplete_Target_Parent_Field__c = 'AccountId';
        relatedContacts.Field__c = NAMESPACE+'Contact__c';
        relatedContacts.Filter__c = 'AccountId = \'parentId\'';
        relatedContacts.Label__c = 'Contacts';
        relatedContacts.Object__c = 'Contact';
        relatedContacts.Type__c = 'Multipicklist';
        smartWidgets.add(relatedContacts);
        insert relatedContacts;
        SmartWidget__c relatedInvestments = new SmartWidget__c();
        relatedInvestments.Name = 'PermissionExample_RelatedInvestment';
        relatedInvestments.AutoComplete_Search_Object__c = NAMESPACE+'Finaccount__c';
        relatedInvestments.AutoComplete_Search_Filter__c = 'Id != \'securityGroups\'';
        relatedInvestments.AutoComplete_Related_Field__c = NAMESPACE+'Account_Vehicle__r.Name,'+NAMESPACE+'Fund__r.Name,'+NAMESPACE+'Fund__r.Migration_Source__c';
        relatedInvestments.AutoComplete_Target_Object__c = NAMESPACE+'Permission__c';
        relatedInvestments.AutoComplete_Target_Parent_Field__c = NAMESPACE+'Account__c';
        relatedInvestments.Field__c = NAMESPACE+'Finaccount__c';
        relatedInvestments.Filter__c = NAMESPACE+'Account__c = \'parentId\'';
        relatedInvestments.Label__c = 'Investment';
        relatedInvestments.Object__c = NAMESPACE+'Finaccount__c';
        relatedInvestments.Type__c = 'Multipicklist';
        smartWidgets.add(relatedInvestments);
        insert relatedInvestments;

//        insert smartWidgets;
        //Contact_ManagePermissions_Alert
//        Permission_Configuration__mdt permissionConfig = new Permission_Configuration__mdt();
//        permissionConfig.DeveloperName = 'Contact_ManagePermissions_Alert';
//        permissionConfig.Header_Angle__c = 45;
//        permissionConfig.Label = 'Contact_ManagePermissions_Alert';
//        permissionConfig.Parent_Field__c ='AccountId';
//        permissionConfig.Primary_Junction_Object_Type__c = 'Contact';
//        permissionConfig.Related_Object_Widgets__c = 'Permission_RelatedContacts;Permission_RelatedInvestment';
//        permissionConfig.Columns__c = 'Contact__c;Investment__c; Account_Vehicle__c; Fund__c';
//        permissionConfig.Headers__c = 'Contact;Investment; Investment Vehicle; Fund';
//        permissionConfig.Display_Alert_Icons__c = true;
//        permissionConfig.Contact_Security_Field__c = 'Group_Name_Text__c';
//        permissionConfig.Permission_Security_Field__c = 'Fund__r.Migration_Source__c';
//        permissionConfig.Save_Mode__c = 'All';
//        insert permissionConfig;

        //Create permission types
        List<Permission_Type__c> permissionTypes = new List<Permission_Type__c>();
        Permission_Type__c dist = new Permission_Type__c();
        dist.Name = 'Distribution';
        dist.Default_Active__c = true;
        dist.Default_Alert__c = false;
        permissionTypes.add(dist);

        Permission_Type__c legal = new Permission_Type__c();
        legal.Name = 'Legal';
        legal.Default_Active__c = false;
        legal.Default_Alert__c = false;
        permissionTypes.add(legal);

        Permission_Type__c dm = new Permission_Type__c();
        dm.name = 'DM';
        DM.Default_Active__c = false;
        DM.Default_Alert__c = false;
        permissionTypes.add(dm);

        Permission_Type__c cp = new Permission_Type__c();
        cp.Name = 'CP';
        cp.Default_Active__c = true;
        cp.Default_Alert__c = true;
        permissionTypes.add(cp);

        Permission_Type__c so = new Permission_Type__c();
        so.Name = 'SO';
        so.Default_Active__c = false;
        so.Default_Alert__c = false;
        permissionTypes.add(so);

        insert permissionTypes;
        //Create account
        List<Account> accounts = new List<Account>();

        Account acme = new Account();
        acme.Name = 'Acme';
        Accounts.add(acme);

        insert Accounts;

        //Create Contact
        List<Contact> contacts = new List<Contact>();
        Contact Bob = new Contact();
        Bob.FirstName = 'Bob';
        Bob.LastName = 'TestingRelatedSelect';
        Bob.AccountId = acme.Id;
        contacts.add(bob);
        insert contacts;
        //Create Fund
//        List<Fund__c> funds = new List<Fund__c>();
        Investment_Vehicle__c f = new Investment_Vehicle__c();
        f.Name = 'Test FUN';
        insert f;
//        insert funds;
        //Create Investment
        Finaccount__c fin = new Finaccount__c();
        fin.Account__c = acme.Id;
        fin.Investment_Vehicle__c = f.Id;
        insert fin;
    }

    @IsTest
    static void testQuery(){
        SmartWidget__c widget = [SELECT Id,
                AutoComplete_Target_Field__c,
                AutoComplete_Target_Object__c,
                AutoComplete_Search_Object__c,
                AutoComplete_Target_Parent_Field__c,
                AutoComplete_Search_Filter__c,
                Field__c,
                Filter__c,
                Label__c,
                Object__c,
                Type__c
                FROM SmartWidget__c
                WHERE Name='PermissionExample_RelatedContacts' LIMIT 1];
        String parentID = [SELECT Id FROM Account WHERE Name='Acme'].Id;
        String childId = [select id from Contact where Name='Bob TestingRelatedSelect'].Id;

        RelatedMultiSelect.queryRecordsFromWidget(JSON.serialize(widget),parentId,childId, false, new List<String>());
    }
    @IsTest
    static void testSearch(){
        SmartWidget__c widget = [SELECT Id,
                AutoComplete_Target_Field__c,
                AutoComplete_Target_Object__c,
                AutoComplete_Search_Object__c,
                AutoComplete_Target_Parent_Field__c,
                AutoComplete_Search_Filter__c,
                Field__c,
                Filter__c,
                Label__c,
                Object__c,
                Type__c
        FROM SmartWidget__c
        WHERE Name='PermissionExample_RelatedContacts' LIMIT 1];

        String searchText = 'Bob';

        RelatedMultiSelect.search(JSON.serialize(widget),searchText,false, new List<String>());
    }
}