WMG112519/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/DX_Integration__c.field-meta.xml
<CustomField>
    <fullName>DX_Integration__c</fullName>
    <label>DX Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission__c/Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <displayFormat>PM-{000000000}</displayFormat>
        <label>Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Permission_Type__c.field-meta.xml
<CustomField>
    <fullName>Permission_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Type</label>
    <referenceTo>Permission_Type__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Event__e/Permission_Event__e.object-meta.xml
<CustomObject>
    <label>Permission Platform Event</label>
    <pluralLabel>Permission Platform Events</pluralLabel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Permission_Event__e/fields/Fund_Id__c.field-meta.xml
<CustomField>
    <fullName>Fund_Id__c</fullName>
    <label>Fund Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Event__e/fields/Investment_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Investment_Account_Id__c</fullName>
    <label>Investment Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Event__e/fields/Investment_Id__c.field-meta.xml
<CustomField>
    <fullName>Investment_Id__c</fullName>
    <label>Investment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Event__e/fields/Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>Permission_Id__c</fullName>
    <label>Permission Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Event__e/fields/Permission_Type__c.field-meta.xml
<CustomField>
    <fullName>Permission_Type__c</fullName>
    <label>Permission Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Type__c/Permission_Type__c.object-meta.xml
<CustomObject>
    <label>Permission Type</label>
    <nameField>
        <label>Permission Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/classes/Permission_Handler.cls
public with sharing class Permission_Handler {
    private static Set<Id> setFiredIds = new Set<Id>();

    public void createPlatformEvents(List<Permission__c> lstPermissions) {
        system.debug('setFiredIds: ' + setFiredIds);
        Set<Id> setPermissionIds = new Set<Id>();
        List<Permission_Event__e> lstPermissionPlatformEvents = new List<Permission_Event__e>();
        for (Permission__c permission : lstPermissions) {
            if (!setFiredIds.contains(permission.Id)) {
                setPermissionIds.add(permission.Id);
                setFiredIds.add(permission.Id);
            }
        }
        if (setPermissionIds.size() > 0) {
            for (Permission__c permission : [select Id, Contact__c, Contact__r.Email, Fund__c, Permission_Type__c,Fund__r.DX_Integration__c from Permission__c where Id in :setPermissionIds
                                            						and Fund__r.DX_Integration__c IN: new List<String>{'Active','Planned'}]) {
                lstPermissionPlatformEvents.add(new Permission_Event__e(
                        Contact_Email__c = permission.Contact__r.Email,
                        Contact_Id__c = permission.Contact__c,
                        Fund_Id__c = permission.Fund__c,
                        Investment_Account_Id__c = '',
                        Investment_Id__c = '',
                        Permission_Id__c = permission.Id,
                        Permission_Type__c = permission.Permission_Type__c
                ));
            }

            if (lstPermissionPlatformEvents.size() > 0) {
                // Call method to publish events
                List<Database.SaveResult> results = EventBus.publish(lstPermissionPlatformEvents);

                // Inspect publishing result for each event
                for (Database.SaveResult sr : results) {
                    if (sr.isSuccess()) {
                        System.debug('Successfully published event.');
                    } else {
                        for (Database.Error err : sr.getErrors()) {
                            System.debug('Error returned: ' +
                                    err.getStatusCode() +
                                    ' - ' +
                                    err.getMessage());
                        }
                    }
                }
            }
        }
    }
}