WMG112519/force-app/main/default/objects/ConfigSettings__c/ConfigSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ConfigSettings</label>
</CustomObject>

WMG112519/force-app/main/default/objects/ConfigSettings__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/Service_Level_Defaults__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Service Level Defaults</label>
</CustomObject>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Num_Days_Ahead_On_Target__c.field-meta.xml
<CustomField>
    <fullName>Num_Days_Ahead_On_Target__c</fullName>
    <inlineHelpText>The number days until a next call/meeting that is considered &quot;green&quot; or on- target</inlineHelpText>
    <label>Num Days Ahead - On Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_A_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_A_In_Person_Meetings_Year__c</fullName>
    <label>Tier A - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_A_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_A_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier A client</inlineHelpText>
    <label>Tier A - Relationship Calls/Year</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_B_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_B_In_Person_Meetings_Year__c</fullName>
    <label>Tier B - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_B_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_B_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier B client</inlineHelpText>
    <label>Tier B - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_C_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_C_In_Person_Meetings_Year__c</fullName>
    <inlineHelpText>Default number of In-Person Meetings/Year for a Tier C client</inlineHelpText>
    <label>Tier C - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_C_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_C_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier C client</inlineHelpText>
    <label>Tier C - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_D_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_D_In_Person_Meetings_Year__c</fullName>
    <inlineHelpText>Default number of In-Person Meetings/Year for a Tier D client</inlineHelpText>
    <label>Tier D - In-Person Meetings/Year</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_D_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_D_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier D client</inlineHelpText>
    <label>Tier D - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_E_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_E_In_Person_Meetings_Year__c</fullName>
    <inlineHelpText>Default number of In-Person Meetings/Year for a Tier E client</inlineHelpText>
    <label>Tier E - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_E_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_E_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier E client</inlineHelpText>
    <label>Tier E - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/classes/testMethod_manageServiceLevelDefaults.cls
@isTest(SeeAllData=False)
private class testMethod_manageServiceLevelDefaults {
    
    static testMethod void manageServiceLevelDefaults_Test () 
    {
        CreateData (false);
        Test.StartTest();
        manageServiceLevelDefaultsExtension myCon = new manageServiceLevelDefaultsExtension ();
        
        myCon.Tier_A_In_Person_Meetings_Year = 2;
        myCon.OverrideSave();
        myCon.Cancel() ;
        test.stopTest();
    }
    static testMethod void manageServiceLevelDefaults_NoRecord_Test () 
    {
        CreateData (true);
        PageReference pageRef = Page.manageServiceLevelDefaults;
        Test.setCurrentPageReference(pageref);
        ApexPages.currentPage().getParameters().put('retUrl','1234');
        
        Test.StartTest();
        manageServiceLevelDefaultsExtension myCon = new manageServiceLevelDefaultsExtension ();
        myCon.Tier_A_In_Person_Meetings_Year = 2;
        myCon.OverrideSave();
        myCon.Cancel() ;
        test.stopTest();
    }
    private static void CreateData (boolean CreateOrg)
    {
        ConfigSettings__c config = new ConfigSettings__c ();
        config.Name = 'DefaultSvcConfigEmail' ;
        config.Value__c = 'test@test.com';
        insert config ;
        
        Service_Level_Defaults__c sfd = Service_Level_Defaults__c.getInstance ();
        if (CreateOrg)
            sfd.SetupOwnerId = UserInfo.getOrganizationId();
        sfd.Tier_A_In_Person_Meetings_Year__c = 1;
        sfd.Tier_B_In_Person_Meetings_Year__c = 1;
        sfd.Tier_C_In_Person_Meetings_Year__c = 1;
        sfd.Tier_D_In_Person_Meetings_Year__c = 1;
        sfd.Tier_E_In_Person_Meetings_Year__c = 1;
        sfd.Tier_A_Relationship_Calls_Year__c =1;
        sfd.Tier_B_Relationship_Calls_Year__c =1;
        sfd.Tier_C_Relationship_Calls_Year__c =1;
        sfd.Tier_D_Relationship_Calls_Year__c =1;
        sfd.Tier_E_Relationship_Calls_Year__c =1;
        sfd.Num_Days_Ahead_On_Target__c = 30;
        insert sfd;
        System.Debug('****: ' + Service_Level_Defaults__c.getInstance () ) ;
        
    }
    
}