WMG112519/force-app/main/default/objects/ConfigSettings__c/ConfigSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ConfigSettings</label>
</CustomObject>

WMG112519/force-app/main/default/objects/ConfigSettings__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

WMG112519/force-app/main/default/objects/SecurityDefaultQueue__c/SecurityDefaultQueue__c.object-meta.xml
<CustomObject>
    <label>SecurityDefaultQueue</label>
    <nameField>
        <label>SecurityDefaultQueue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SecurityDefaultQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WMG112519/force-app/main/default/objects/SecurityDefaultQueue__c/fields/UserData__c.field-meta.xml
<CustomField>
    <fullName>UserData__c</fullName>
    <label>UserData</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/Service_Level_Defaults__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Service Level Defaults</label>
</CustomObject>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Num_Days_Ahead_On_Target__c.field-meta.xml
<CustomField>
    <fullName>Num_Days_Ahead_On_Target__c</fullName>
    <inlineHelpText>The number days until a next call/meeting that is considered &quot;green&quot; or on- target</inlineHelpText>
    <label>Num Days Ahead - On Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Num_Days_Ahead_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Num_Days_Ahead_Overdue__c</fullName>
    <inlineHelpText>Number of days ahead for a call to be &quot;red&quot; or &quot;overdue&quot;. For consistency with the other fields, this is stored as number of days ahead, even though it may be set as days *after*. In this case, set as a negative number.</inlineHelpText>
    <label>Num Days Ahead - Overdue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_A_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_A_In_Person_Meetings_Year__c</fullName>
    <label>Tier A - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_A_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_A_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier A client</inlineHelpText>
    <label>Tier A - Relationship Calls/Year</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_B_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_B_In_Person_Meetings_Year__c</fullName>
    <label>Tier B - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_B_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_B_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier B client</inlineHelpText>
    <label>Tier B - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_C_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_C_In_Person_Meetings_Year__c</fullName>
    <inlineHelpText>Default number of In-Person Meetings/Year for a Tier C client</inlineHelpText>
    <label>Tier C - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_C_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_C_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier C client</inlineHelpText>
    <label>Tier C - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_D_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_D_In_Person_Meetings_Year__c</fullName>
    <inlineHelpText>Default number of In-Person Meetings/Year for a Tier D client</inlineHelpText>
    <label>Tier D - In-Person Meetings/Year</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_D_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_D_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier D client</inlineHelpText>
    <label>Tier D - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_E_In_Person_Meetings_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_E_In_Person_Meetings_Year__c</fullName>
    <inlineHelpText>Default number of In-Person Meetings/Year for a Tier E client</inlineHelpText>
    <label>Tier E - In-Person Meetings/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/force-app/main/default/objects/Service_Level_Defaults__c/fields/Tier_E_Relationship_Calls_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_E_Relationship_Calls_Year__c</fullName>
    <inlineHelpText>Default number of Relationship Calls/Year for a Tier E client</inlineHelpText>
    <label>Tier E - Relationship Calls/Year</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WMG112519/WMG112519/force-app/main/default/classes/manageServiceLevelDefaultsExtension.cls
public  with sharing class manageServiceLevelDefaultsExtension 
{
    //public Service_Level_Defaults__c defaults {get;set;}
    private boolean isUserConfing = false;
    private string retUrl = '';
    public decimal Tier_A_Relationship_Calls_Year {get;set;}
    public decimal Tier_B_Relationship_Calls_Year {get;set;}
    public decimal Tier_C_Relationship_Calls_Year {get;set;}
    public decimal Tier_D_Relationship_Calls_Year {get;set;}
    public decimal Tier_E_Relationship_Calls_Year {get;set;}
    
    public decimal Tier_A_In_Person_Meetings_Year {get;set;}
    public decimal Tier_B_In_Person_Meetings_Year {get;set;}
    public decimal Tier_C_In_Person_Meetings_Year {get;set;}
    public decimal Tier_D_In_Person_Meetings_Year {get;set;}
    public decimal Tier_E_In_Person_Meetings_Year {get;set;}
    
    public decimal Tier_A_Portfolio_Review_Year {get;set;}
    public decimal Tier_B_Portfolio_Review_Year {get;set;}
    public decimal Tier_C_Portfolio_Review_Year {get;set;}
    public decimal Tier_D_Portfolio_Review_Year {get;set;}
    public decimal Tier_E_Portfolio_Review_Year {get;set;}
    
    public decimal Num_Days_Ahead_On_Target {get;set;}
    public decimal Num_Days_Ahead_Overdue {get;set;}
    
    private string recordId ;
    
    //public manageServiceLevelDefaultsExtension(ApexPages.StandardController stdController)
    public manageServiceLevelDefaultsExtension()
    {
        retUrl =  ApexPages.currentPage().getParameters().get('retUrl');
        Service_Level_Defaults__c userDefaults = Service_Level_Defaults__c.getInstance (Userinfo.getUserId());
        Service_Level_Defaults__c Defaults  ;   
        if (userDefaults.id == null)
        {
            defaults = Service_Level_Defaults__c.getInstance();
            isUserConfing = false;
        }
        else
        {
            defaults = userDefaults;
            isUserConfing = true;
        }
        recordId = defaults.id;
        
        Tier_A_Relationship_Calls_Year = defaults.Tier_A_Relationship_Calls_Year__c;
        Tier_B_Relationship_Calls_Year = defaults.Tier_B_Relationship_Calls_Year__c;
        Tier_C_Relationship_Calls_Year = defaults.Tier_C_Relationship_Calls_Year__c;
        Tier_D_Relationship_Calls_Year = defaults.Tier_D_Relationship_Calls_Year__c;
        Tier_E_Relationship_Calls_Year = defaults.Tier_E_Relationship_Calls_Year__c;
        
        Tier_A_In_Person_Meetings_Year = defaults.Tier_A_In_Person_Meetings_Year__c;
        Tier_B_In_Person_Meetings_Year = defaults.Tier_B_In_Person_Meetings_Year__c;
        Tier_C_In_Person_Meetings_Year = defaults.Tier_C_In_Person_Meetings_Year__c;
        Tier_D_In_Person_Meetings_Year = defaults.Tier_D_In_Person_Meetings_Year__c;
        Tier_E_In_Person_Meetings_Year = defaults.Tier_E_In_Person_Meetings_Year__c;
        
            
        Num_Days_Ahead_On_Target = defaults.Num_Days_Ahead_On_Target__c;
        Num_Days_Ahead_Overdue = defaults.Num_Days_Ahead_Overdue__c;
        
        
    }
    public PageReference OverrideSave()
    {
        //upsert defaults;
        //Add the Data to to the queue objects and send email to trigger.
        Service_Level_Defaults__c Defaults =  new   Service_Level_Defaults__c ();
        defaults.id = recordId;
        
        defaults.Tier_A_Relationship_Calls_Year__c = Tier_A_Relationship_Calls_Year ;
        defaults.Tier_B_Relationship_Calls_Year__c = Tier_B_Relationship_Calls_Year ;
        defaults.Tier_C_Relationship_Calls_Year__c = Tier_C_Relationship_Calls_Year ;
        defaults.Tier_D_Relationship_Calls_Year__c = Tier_D_Relationship_Calls_Year ;
        defaults.Tier_E_Relationship_Calls_Year__c = Tier_E_Relationship_Calls_Year ;
        
        defaults.Tier_A_In_Person_Meetings_Year__c = Tier_A_In_Person_Meetings_Year ;
        defaults.Tier_B_In_Person_Meetings_Year__c = Tier_B_In_Person_Meetings_Year ;
        defaults.Tier_C_In_Person_Meetings_Year__c = Tier_C_In_Person_Meetings_Year ;
        defaults.Tier_D_In_Person_Meetings_Year__c = Tier_D_In_Person_Meetings_Year ;
        defaults.Tier_E_In_Person_Meetings_Year__c = Tier_E_In_Person_Meetings_Year ;
        
              
        defaults.Num_Days_Ahead_On_Target__c = Num_Days_Ahead_On_Target ;
        defaults.Num_Days_Ahead_Overdue__c = Num_Days_Ahead_Overdue;
        
        SecurityDefaultQueue__c q = new SecurityDefaultQueue__c();
    //  if (defaults.SetupOwnerId != UserInfo.getUserId())
        defaults.SetupOwnerId = UserInfo.getUserId() ;
        q.UserData__c = JSON.serialize(defaults)  ;
        insert q ;
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        List<string> theToAddess = new List<string>();
        theToAddess.add( ConfigSettings__c.getValues('DefaultSvcConfigEmail').Value__c );
        email.setToAddresses(theToAddess);
        email.setPlainTextBody('');
        Messaging.SendEmailResult [] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});  
        return new PageReference('/' + retUrl);
    }
    public Pagereference Cancel ()
    {
        if (returl != null)
            return new PageReference('/' + retUrl);
        else
            return new PageReference('/');
    }
}