PROD_10-24-19/force-app/main/default/objects/Permission__c/Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <displayFormat>PM-{000000000}</displayFormat>
        <label>Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/TEST_PlatformEvent.cls
@isTest(SeeAllData=false)
public with sharing class TEST_PlatformEvent {
    private static testMethod void Test_Permission() {
        Contact contact = new Contact(FirstName='FirstName', LastName='Test Contact');
        insert contact;

        Test.startTest();

        Permission__c permission = new Permission__c(Contact__c=contact.Id);
        insert permission;

        Test.getEventBus().deliver();

        update permission;

        Test.getEventBus().deliver();

        Test.stopTest();
    }
}