PROD-9-26-19/force-app/main/default/objects/Investment_Vehicle_Close_Date__c/Investment_Vehicle_Close_Date__c.object-meta.xml
<CustomObject>
    <description>BF-26: Investment Vehicle Close Dates</description>
    <label>Investment Vehicle Close Date</label>
    <nameField>
        <label>Close Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicle Close Dates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle_Close_Date__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>BF-26: The close date</description>
    <inlineHelpText>The close date</inlineHelpText>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle_Close_Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select a fund close date by searching by Fund Short Name</description>
    <inlineHelpText>Select a fund close date by searching by Fund Short Name</inlineHelpText>
    <label>Fund Close Type and Date</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>$Source.Investment_Vehicle__c</field>
            <operation>equals</operation>
            <valueField>Investment_Vehicle_Close_Date__c.Investment_Vehicle__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Investment_Vehicle__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle_Close_Date__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Search by Entering Fund Short Name</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle_Close_Date__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12120/force-app/main/default/classes/CSL_Handler_InvestmentVehicle.cls
public class CSL_Handler_InvestmentVehicle {

    /**
      * BF-27: Update the close date field on any opportunities that are related to an investment vehicle close date where the date has changed
      */
    public static void updateCloseDates(List<Investment_Vehicle_Close_Date__c> invCloseDateList, Map<Id, Investment_Vehicle_Close_Date__c> oldMap) {
        // Build a unique set of invoice close date ids where the close date has changed
        Map<Id, Investment_Vehicle_Close_Date__c> invCloseDateUpdateMap = new Map<Id, Investment_Vehicle_Close_Date__c>();
        for(Investment_Vehicle_Close_Date__c invCloseDate : invCloseDateList) {
            // Ensure the close date is not blank and it has changed
            if(oldMap != null && oldMap.containsKey(invCloseDate.Id) &&
               null != invCloseDate.Close_Date__c &&
               oldMap.get(invCloseDate.Id).Close_Date__c != invCloseDate.Close_Date__c) {
               invCloseDateUpdateMap.put(invCloseDate.Id, invCloseDate);
            }
        }
        system.debug(LoggingLevel.DEBUG, 'CSL_Handler_InvestmentVehicle :: updateCloseDate :: invCloseDateUpdateMap= ' + invCloseDateUpdateMap);

        if(invCloseDateUpdateMap.size() > 0) {
            try {
                // Query opportunitiy for any oppty's linked to close dates
                List<Opportunity> oppList = [SELECT Id, Investment_Vehicle_Close_Date__c
                                             FROM Opportunity
                                             WHERE Investment_Vehicle_Close_Date__c IN :invCloseDateUpdateMap.keySet()];
                system.debug(LoggingLevel.DEBUG, 'CSL_Handler_InvestmentVehicle :: updateCloseDate :: oppList= ' + oppList);

                // Iterate through the opportunities and update the close dates
                for(Opportunity opp : oppList) {
                    Investment_Vehicle_Close_Date__c closeDate = invCloseDateUpdateMap.get(opp.Investment_Vehicle_Close_Date__c);
                    opp.CloseDate = closeDate.Close_Date__c;
                }

                update oppList;
            }   catch (Exception e) {
                system.debug(LoggingLevel.ERROR, 'CSL_Handler_InvestmentVehicle :: updateCloseDate :: invCloseDateUpdateMap.keySet() = ' + invCloseDateUpdateMap.keySet());
                system.debug(LoggingLevel.ERROR, 'CSL_Handler_InvestmentVehicle :: updateCloseDate :: e.getMessage() ' + e.getMessage());
            }
        }

    }

    /**
      * BF-27: Ensure there are no related opportunities before a deletion is allowed to occur
      */
    public static void validateDeletion(List<Investment_Vehicle_Close_Date__c> invCloseDateList) {
        // Build a unique set of invoice close date ids
        Set<Id> invCloseDateIds = new Set<Id>();
        for(Investment_Vehicle_Close_Date__c invCloseDate : invCloseDateList) {
            invCloseDateIds.add(invCloseDate.Id);
        }
        system.debug(LoggingLevel.DEBUG, 'CSL_Handler_InvestmentVehicle :: validateDeletion :: invCloseDateIds= ' + invCloseDateIds);

        try {
            // Query opportunitiy for any oppty's linked to close dates
            List<Opportunity> oppList = [SELECT Id, Investment_Vehicle_Close_Date__c
                                         FROM Opportunity
                                         WHERE Investment_Vehicle_Close_Date__c IN :invCloseDateIds];
            system.debug(LoggingLevel.DEBUG, 'CSL_Handler_InvestmentVehicle :: validateDeletion :: oppList= ' + oppList);

            // For the dates that had related opportunities add an error
            List<Investment_Vehicle_Close_Date__c> preventDeletes = new List<Investment_Vehicle_Close_Date__c>();
            for(Investment_Vehicle_Close_Date__c invCloseDate : invCloseDateList) {
                for(Opportunity opp : oppList) {
                    if(opp.Investment_Vehicle_Close_Date__c != null &&
                       opp.Investment_Vehicle_Close_Date__c == invCloseDate.Id) {
                       invCloseDate.addError(Label.Investment_Close_Date_Delete_Validation);
                       break;
                    }
                }
            }

        }   catch (Exception ex) {
            system.debug(LoggingLevel.ERROR, 'CSL_Handler_InvestmentVehicle :: validateDeletion :: No related opportunities found for these close dates: ' + invCloseDateIds);
            system.debug(LoggingLevel.ERROR, 'CSL_Handler_InvestmentVehicle :: validateDeletion :: ex.getMessage() ' + ex.getMessage());
        }
    }

}