PROD-9-26-19/force-app/main/default/objects/Compliance__c/Compliance__c.object-meta.xml
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <displayFormat>C - {0}</displayFormat>
        <label>Compliance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Compliance__c/fields/Prospect_Name__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Name__c</fullName>
    <label>Prospect Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>KYC_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PROD-9-26-19/force-app/main/default/classes/BatchBlankUpdateComplianceTest.cls
@isTest
Private class BatchBlankUpdateComplianceTest {
    @testSetup
    Static void setup(){
        Account acc = new Account (name = 'Test Account'); 
        insert acc;
        
        Id RecordTypeIdCompliance = Schema.SObjectType.Compliance__c.getRecordTypeInfosByName().get('PSG').getRecordTypeId();
      
        // find the account just inserted. add compliance for the account
        List<Compliance__c> Compliance = new List<Compliance__c>();
        //insert 10 compliances 
        for (Integer i=0;i<10;i++) {
            Compliance.add(new Compliance__c (Prospect_Name__c=acc.Id,recordtypeid=RecordTypeIdCompliance)); 
            
        }
        insert Compliance;
    }

    static testmethod void test() { 
        Test.startTest();
        BatchBlankUpdateCompliance bupComp = new BatchBlankUpdateCompliance ();
        Id batchId = Database.executeBatch(bupComp);
        
        Test.stopTest();
        System.assertEquals(10,[select count() from Compliance__c]);
    }
}