PROD-12-18-19/force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant Relationship</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Consultant Rel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultant Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Consultant__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Group</valueSetName>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Consultant__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consultants</relationshipLabel>
    <relationshipName>Consultant_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Consultant_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>No longer with Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Fund Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Corporate Credit</fullName>
            </value>
            <value>
                <fullName>Corporate High Yield</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Opportunities</fullName>
            </value>
            <value>
                <fullName>Energy Infrastructure</fullName>
            </value>
            <value>
                <fullName>Equity Opportunities</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
            <value>
                <fullName>Investments</fullName>
            </value>
            <value>
                <fullName>Opportunistic MBS</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Real Asset Debt</fullName>
            </value>
            <value>
                <fullName>Real Asset Solutions</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Securitized Credit</fullName>
            </value>
            <value>
                <fullName>Specialty Funds</fullName>
            </value>
            <value>
                <fullName>Strategic Income</fullName>
            </value>
            <value>
                <fullName>Timberland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Short Listed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>General Interest</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Pre-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Fully Divested</fullName>
            </value>
            <value>
                <fullName>Wound Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Office__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Office</relationshipLabel>
    <relationshipName>Office</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</description>
    <inlineHelpText>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</inlineHelpText>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advised Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Field_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Field_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Consultant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Consultant__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Field Consultant)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Research_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Research_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Consultant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Research Consultant)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/recordTypes/PFG.recordType-meta.xml
<RecordType>
    <fullName>PFG</fullName>
    <active>true</active>
    <businessProcess>PFG</businessProcess>
    <description>Private Funds Default Opportunity Type</description>
    <label>PFG</label>
</RecordType>

PROD-9-26-19/force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Relationship__c/fields/Field_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Field_Consultant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Field Consultant</label>
    <type>Checkbox</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Relationship__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Relationship__c/fields/Related_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RelatedTo (Account)</relationshipLabel>
    <relationshipName>RelatedToAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Relationship__c/recordTypes/Consultant.recordType-meta.xml
<RecordType>
    <fullName>Consultant</fullName>
    <active>true</active>
    <description>Account to Account relationships between Consultant Accounts and Client Accounts</description>
    <label>Consultant</label>
</RecordType>

PROD-12-18-19/force-app/main/default/globalValueSets/Business_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Private Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate High Yield</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Opportunities</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Equity Opportunities</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Investments</fullName>
    </customValue>
    <customValue>
        <fullName>Opportunistic MBS</fullName>
    </customValue>
    <customValue>
        <fullName>Power</fullName>
    </customValue>
    <customValue>
        <fullName>Property</fullName>
    </customValue>
    <customValue>
        <fullName>Real Asset Debt</fullName>
    </customValue>
    <customValue>
        <fullName>Real Asset Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Securitized Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Specialty Funds</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic Income</fullName>
    </customValue>
    <customValue>
        <fullName>Timberland</fullName>
    </customValue>
    <masterLabel>Business Group</masterLabel>
</GlobalValueSet>

PROD-12-18-19/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

PROD-12120/force-app/main/default/classes/Opportunity_Handler.cls
public with sharing class Opportunity_Handler {
    private Map<String, Id> mapRecordType;
    public void createConsultantRelationship(List<Opportunity> records) {
        populateRecordTypeMap();
        Set<Id> psgRecordTypes = new Set<Id>();
        for (String recordTypeDeveloperName : mapRecordType.keySet()) {
            if (recordTypeDeveloperName.contains('PSG')) {
                psgRecordTypes.add(mapRecordType.get(recordTypeDeveloperName));
            }
        }

        Set<Id> setConsultantIds = new Set<Id>();
        Set<Id> setAccountIds = new Set<Id>();
        Set<Id> setInvestmentVehicleIds = new Set<Id>();
        List<Opportunity> lstReleventRecords = new List<Opportunity>();
        system.debug('psgRecordTypes: ' + psgRecordTypes);
        for (Opportunity o : records) {
            if (psgRecordTypes.contains(o.RecordTypeId) && String.isNotBlank(o.Consultant__c)) {
                setConsultantIds.add(o.Consultant__c);
                setAccountIds.add(o.AccountId);
                setInvestmentVehicleIds.add(o.Investment_Vehicle__c);
                lstReleventRecords.add(o);
            }
        }

        if (setConsultantIds.size() > 0) {
            Map<Id, Investment_Vehicle__c> mapRelatedInvestmentVehicles = new Map<Id, Investment_Vehicle__c>([select Id, Platform__c from Investment_Vehicle__c where Id in :setInvestmentVehicleIds]);

            Set<String> setConsultantKey = new Set<String>();
            for (Consultant__c c : [select Id, Client__c, Consultant__c, Asset_Class__c from Consultant__c where Client__c in :setAccountIds and Consultant__c in :setConsultantIds]) {
                setConsultantKey.add(c.Client__c + '_' + c.Consultant__c + '_' + c.Asset_Class__c);
            }

            List<Consultant__c> lstConsultantForInsert = new List<Consultant__c>();
            for (Opportunity o : lstReleventRecords) {
                if (!setConsultantKey.contains(o.AccountId + '_' + o.Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c)) {
                    lstConsultantForInsert.add(new Consultant__c(Client__c=o.AccountId, Consultant__c=o.Consultant__c, Status__c='Active', Asset_Class__c=mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c));
                    setConsultantKey.add(o.AccountId + '_' + o.Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c);
                }
            }

            insert lstConsultantForInsert;
        }
    }

    public void createFieldConsultantRelationship(List<Opportunity> records) {
        populateRecordTypeMap();
        Set<Id> setFieldConsultantIds = new Set<Id>();
        Set<Id> setAccountIds = new Set<Id>();
        Set<Id> setInvestmentVehicleIds = new Set<Id>();
        List<Opportunity> lstReleventRecords = new List<Opportunity>();
        for (Opportunity o : records) {
            if (String.isNotBlank(o.Field_Consultant__c)) {
                setFieldConsultantIds.add(o.Field_Consultant__c);
                setAccountIds.add(o.AccountId);
                setInvestmentVehicleIds.add(o.Investment_Vehicle__c);
                lstReleventRecords.add(o);
            }
        }

        if (setFieldConsultantIds.size() > 0) {
            Map<Id, Contact> mapRelatedFieldConsultants = new Map<Id, Contact>([select Id, AccountId, Office__c from Contact where Id in :setFieldConsultantIds]);
            Map<Id, Investment_Vehicle__c> mapRelatedInvestmentVehicles = new Map<Id, Investment_Vehicle__c>([select Id, Platform__c from Investment_Vehicle__c where Id in :setInvestmentVehicleIds]);

            Map<String, Relationship__c> mapRelationship = new Map<String, Relationship__c>();
            for (Relationship__c r : [select Id, Account__c, Contact__c, Related_To_Account__c, Office__c, Asset_Class__c, Status__c, Field_Consultant__c from Relationship__c where Account__c in :setAccountIds and Contact__c in :setFieldConsultantIds]) {
                mapRelationship.put(r.Account__c + '_' + r.Contact__c + '_' + r.Asset_Class__c + '_' + r.Field_Consultant__c, r);
            }

            List<Relationship__c> lstRelationshipForInsert = new List<Relationship__c>();
            List<OpportunityContactRole> lstContactRolesForInsert = new List<OpportunityContactRole>();
            Set<Id> updatedIds = new Set<Id>();
            for (Opportunity o : lstReleventRecords) {
                if (mapRelationship.get(o.AccountId + '_' + o.Field_Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c + '_' + true) == null) {
                    lstRelationshipForInsert.add(
                            new Relationship__c(
                                    Account__c=o.AccountId,
                                    Contact__c=o.Field_Consultant__c,
                                    Related_To_Account__c=mapRelatedFieldConsultants.get(o.Field_Consultant__c).AccountId,
                                    Office__c=mapRelatedFieldConsultants.get(o.Field_Consultant__c).Office__c,
                                    Asset_Class__c=mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c,
                                    Status__c='Active',
                                    Field_Consultant__c=true
                            )
                    );
                    lstContactRolesForInsert.add(new OpportunityContactRole(OpportunityId=o.Id, ContactId=o.Field_Consultant__c, Role='Field Consultant'));
                    mapRelationship.put(o.AccountId + '_' + o.Field_Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c + '_' + true, new Relationship__c());
                } else {
                    Id relationshipId = mapRelationship.get(o.AccountId + '_' + o.Field_Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c + '_' + true).Id;
                    if (!updatedIds.contains(relationshipId)) {
                        lstRelationshipForInsert.add(new Relationship__c(Id=relationshipId, Status__c='Active'));
                        updatedIds.add(relationshipId);
                    }
                }
            }

            upsert lstRelationshipForInsert;
            insert lstContactRolesForInsert;
        }
    }

    public void createResearchConsultantRelationship(List<Opportunity> records) {
        populateRecordTypeMap();
        Set<Id> pfgRecordTypes = new Set<Id>();
        Set<Id> psgRecordTypes = new Set<Id>();
        for (String recordTypeDeveloperName : mapRecordType.keySet()) {
            if (recordTypeDeveloperName.contains('PFG')) {
                pfgRecordTypes.add(mapRecordType.get(recordTypeDeveloperName));
            }
            if (recordTypeDeveloperName.contains('PSG')) {
                psgRecordTypes.add(mapRecordType.get(recordTypeDeveloperName));
            }
        }
        Set<Id> setResearchConsultantIds = new Set<Id>();
        Set<Id> setAccountIds = new Set<Id>();
        Set<Id> setInvestmentVehicleIds = new Set<Id>();
        List<Opportunity> lstReleventRecords = new List<Opportunity>();
        for (Opportunity o : records) {
            if (String.isNotBlank(o.Research_Consultant__c)) {
                setResearchConsultantIds.add(o.Research_Consultant__c);
                setAccountIds.add(o.AccountId);
                setInvestmentVehicleIds.add(o.Investment_Vehicle__c);
                lstReleventRecords.add(o);
            }
        }

        if (setResearchConsultantIds.size() > 0) {
            Map<Id, Contact> mapRelatedResearchConsultants = new Map<Id, Contact>([select Id, AccountId, Office__c from Contact where Id in :setResearchConsultantIds]);
            Map<Id, Investment_Vehicle__c> mapRelatedInvestmentVehicles = new Map<Id, Investment_Vehicle__c>([select Id, Platform__c from Investment_Vehicle__c where Id in :setInvestmentVehicleIds]);

            Map<String, Relationship__c> mapRelationship = new Map<String, Relationship__c>();
            for (Relationship__c r : [select Id, Account__c, Contact__c, Related_To_Account__c, Office__c, Asset_Class__c, Status__c, Researcher__c from Relationship__c where Account__c in :setAccountIds and Contact__c in :setResearchConsultantIds]) {
                mapRelationship.put(r.Account__c + '_' + r.Contact__c + '_' + r.Asset_Class__c + '_' + r.Researcher__c, r);
            }

            List<Relationship__c> lstRelationshipForInsert = new List<Relationship__c>();
            List<OpportunityContactRole> lstContactRolesForInsert = new List<OpportunityContactRole>();
            Set<Id> updatedIds = new Set<Id>();
            for (Opportunity o : lstReleventRecords) {
                if (mapRelationship.get(o.AccountId + '_' + o.Research_Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c + '_' + true) == null) {
                    Relationship__c newRelationship = new Relationship__c(
                            Account__c=o.AccountId,
                            Contact__c=o.Research_Consultant__c,
                            Related_To_Account__c=mapRelatedResearchConsultants.get(o.Research_Consultant__c).AccountId,
                            Office__c=mapRelatedResearchConsultants.get(o.Research_Consultant__c).Office__c,
                            Asset_Class__c=mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c,
                            Status__c='Active',
                            Researcher__c=true
                    );
                    if (psgRecordTypes.contains(o.RecordTypeId)) {
                        newRelationship.PSG__c = true;
                    }
                    if (pfgRecordTypes.contains(o.RecordTypeId)) {
                        newRelationship.PFG__c = true;
                    }
                    lstRelationshipForInsert.add(newRelationship);
                    lstContactRolesForInsert.add(new OpportunityContactRole(OpportunityId=o.Id, ContactId=o.Research_Consultant__c, Role='Primary Research Consultant'));
                    mapRelationship.put(o.AccountId + '_' + o.Research_Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c + '_' + true, new Relationship__c());
                } else {
                    Id relationshipId = mapRelationship.get(o.AccountId + '_' + o.Research_Consultant__c + '_' + mapRelatedInvestmentVehicles.get(o.Investment_Vehicle__c).Platform__c + '_' + true).Id;
                    if (!updatedIds.contains(relationshipId)) {
                        lstRelationshipForInsert.add(new Relationship__c(Id=relationshipId, Status__c='Active'));
                        updatedIds.add(relationshipId);
                    }
                }
            }

            upsert lstRelationshipForInsert;
            insert lstContactRolesForInsert;
        }
    }

    private void populateRecordTypeMap() {
        if (mapRecordType == null) {
            mapRecordType = new Map<String, Id>();
            for (RecordType rt : [select Id, Name, DeveloperName from RecordType where SobjectType='Opportunity']) {
                mapRecordType.put(rt.DeveloperName, rt.Id);
                mapRecordType.put(rt.Name, rt.Id);
            }
        }
    }
}