PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Office_Country__c.field-meta.xml
<CustomField>
    <fullName>Office_Country__c</fullName>
    <label>Office Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the Opportunity as Private making it visible to only the Opportunity Owner and Opportunity Team Members</description>
    <inlineHelpText>Check this box to make it private to all users except the Opportunity Owner and the Opportunity Team Members</inlineHelpText>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD_10-24-19/force-app/main/default/classes/Test_AddDefaultTeamButtonFunctionality.cls
@isTest(SeeAllData=true)
private class Test_AddDefaultTeamButtonFunctionality
{
 static testMethod void AddDefaultTeam()
 {
   
   
   Account objAcc = TestFactory.buildTestAcc(1, UserInfo.getUserId());
    insert objAcc;
    
    Opportunity  objOpp = new Opportunity (Name='Test Opp', private__c=false, AccountId=objAcc.Id,Office_Country__c='India',StageName='New', CloseDate=system.today());
    insert objOpp;
    user objUser = [select id from user where id!=:userInfo.getuserid() limit 1];
    AddDefaultTeamButtonFunctionality.addDefaultTeam(null, objUser.Id );
    
    AddDefaultTeamButtonFunctionality.addDefaultTeam(objOpp.Id, userInfo.getuserid());
  
 }


}