PROD-9-26-19/force-app/main/default/objects/Opportunity/fields/Office_Country__c.field-meta.xml
<CustomField>
    <fullName>Office_Country__c</fullName>
    <label>Office Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the Opportunity as Private making it visible to only the Opportunity Owner and Opportunity Team Members</description>
    <inlineHelpText>Check this box to make it private to all users except the Opportunity Owner and the Opportunity Team Members</inlineHelpText>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

PROD-9-26-19/force-app/main/default/classes/Test_SendNote.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class Test_SendNote {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
    Account objAcc = TestFactory.buildTestAcc(1, UserInfo.getUserId());
    insert objAcc;
    
    Opportunity  objOpp = new Opportunity (Name='Test Opp', private__c=false, AccountId=objAcc.Id,Office_Country__c='India',StageName='New', CloseDate=system.today());
    insert objOpp;
   
    Contact[] testContactList = new Contact[]{};    
    testContactList.add(new Contact(FirstName='New',lastname='test_contact', Title='Chef',  accountId = objAcc.Id));        
    insert testContactList;
      
     List<Task> tasks = new List<Task>();
    tasks.add(new Task(
    ActivityDate = Date.today().addDays(7),
    Subject='Sample Task',
    WhatId = objOpp.Id,
    whoid = testContactList[0].id,
    OwnerId = UserInfo.getUserId(),
    Status='In Progress'));
     insert tasks;
     
      ApexPages.CurrentPage().getparameters().put('Id', tasks[0].id);
      ApexPages.StandardController sc = new ApexPages.standardController(tasks[0]);
      SendNote sic = new SendNote(sc);
      list< SendNote.UsersRowItem> lstU = new  list<SendNote.UsersRowItem>();
      sic.getlistUsers();
      set<Id> usrId = new set<Id>();
      for(user u:[select id from user where  Profile.Name =:'System Administrator' limit 30])
      {
        SendNote.UsersRowItem obj = new SendNote.UsersRowItem(u,true);
        lstU.add(obj);
        usrId.add(u.Id);
      }
      sic.usersName ='New test_contact';
      sic.listUsers = lstU;
      //sic.selectDeselectRows();
      sic.selectedUserIds = usrId;
      sic.doSendEmail();
       sic.sendAttachment = true;
      sic.doSendEmail();
     // sic.selectDeselectRows();
      sic.getlistUsers();
      sic.searchUser();
      sic.strUseFullName = 'test';
      sic.searchUser();
      sic.doSelectItem();
      sic.getlistUsers();
      sic.doDeselectItem();
      sic.getSelectedCount();
      sic.doNext();
      sic.doPrevious();
      
      sic.getHasPrevious();
      sic.getHasNext();
      sic.getPageNumber();
      sic.doSendEmail();
     
      sic.getlistUsers();
      sic.getTotalPages();

      // BF-9: Added as a part of code coverage
      sic.getRoles();

      UserRole ur = [SELECT ID, Name FROM UserRole WHERE Name = 'SMP'];
      sic.IsAddSubordinate = true;
      sic.roleId = ur.Id;
      sic.searchUser();
    }
}