WMG112519/force-app/main/default/objects/ObjectFieldMapping__c/ObjectFieldMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ObjectFieldMapping</label>
</CustomObject>

WMG112519/force-app/main/default/objects/ObjectFieldMapping__c/fields/Functionality_Type__c.field-meta.xml
<CustomField>
    <fullName>Functionality_Type__c</fullName>
    <description>If you are adding more condition for one Functionality then please add into the same Functionality Type</description>
    <label>Functionality Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WMG112519/WMG112519/force-app/main/default/classes/ActivityHelper.cls
public class ActivityHelper {
    public static list<ObjectFieldMapping__c> getObjectFieldMappingInfo(string sFunctionalityType,string sObjectName){
        list<ObjectFieldMapping__c> lstObjectFieldMapping=new list<ObjectFieldMapping__c>();
        list<ObjectFieldMapping__c> lstObjectFieldMappingInfo= ObjectFieldMapping__c.getAll().values();
        System.debug('+++ lstObjectFieldMappingInfo +++' + lstObjectFieldMappingInfo.size());
        if(lstObjectFieldMappingInfo != null && !lstObjectFieldMappingInfo.isEmpty()){
            for(ObjectFieldMapping__c objFieldMapping : lstObjectFieldMappingInfo){
                if(objFieldMapping.Functionality_Type__c != null && objFieldMapping.Functionality_Type__c.equals(sFunctionalityType) && objFieldMapping.Object_API_Name__c.equals(sObjectName)){
                    lstObjectFieldMapping.add(objFieldMapping);
                }
            }
        }
        return lstObjectFieldMapping;
    }
}