PROD_10-24-19/force-app/main/default/objects/Account/fields/Asset_Lending__c.field-meta.xml
<CustomField>
    <fullName>Asset_Lending__c</fullName>
    <label>Asset Lending</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Current_Commitments_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Commitments_USD__c</fullName>
    <inlineHelpText>Roll up from most recent Investor Position records totalling the Current Commitments in the Fund in USD.

Current commitment is how much has been currently invested + available for drawndown left.</inlineHelpText>
    <label>Current Commitments - USD</label>
    <summarizedField>Investor_Position__c.Current_Commitments_USD__c</summarizedField>
    <summaryFilterItems>
        <field>Investor_Position__c.Is_Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Investor_Position__c.Investment_Vehicle__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/Investor_Position__c.object-meta.xml
<CustomObject>
    <label>Investor Position</label>
    <nameField>
        <label>Investor Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investor Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investor_Position__c/fields/AUM_Number__c.field-meta.xml
<CustomField>
    <fullName>AUM_Number__c</fullName>
    <label>AUM Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Current_Commitments_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Commitments_USD__c</fullName>
    <inlineHelpText>Imported field of Current Commitments in the Fund in USD. 

Current commitment is how much has been currently invested + available for drawdown.</inlineHelpText>
    <label>Current Commitments - USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investor_Position__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle</value>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please DO NOT Create Investor Position for Inactive, Discontinued, Closed Vehicles</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Investor_Position_Account__c.field-meta.xml
<CustomField>
    <fullName>Investor_Position_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Investor Account record</description>
    <inlineHelpText>New Investor Account record</inlineHelpText>
    <label>Investor Position Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investor Positions (All)</relationshipLabel>
    <relationshipName>Investor_Positions2</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copied from originating opportunity. Populates automatically.</inlineHelpText>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/Trigger_Rollup_Rule__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Rollup Rule</label>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/Child_Field__c.field-meta.xml
<CustomField>
    <fullName>Child_Field__c</fullName>
    <label>Child Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/Child_Parent_Field__c.field-meta.xml
<CustomField>
    <fullName>Child_Parent_Field__c</fullName>
    <label>Child Parent Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/Child_Query_Group__c.field-meta.xml
<CustomField>
    <fullName>Child_Query_Group__c</fullName>
    <label>Child Query Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/Child_Query_Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Child_Query_Where_Clause__c</fullName>
    <label>Child Query Where Clause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/DelimitedList_Delimiter__c.field-meta.xml
<CustomField>
    <fullName>DelimitedList_Delimiter__c</fullName>
    <label>Delimiter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/Field_RTF__c.field-meta.xml
<CustomField>
    <fullName>Field_RTF__c</fullName>
    <label>Field RTF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/Number_Rollup_Type__c.field-meta.xml
<CustomField>
    <fullName>Number_Rollup_Type__c</fullName>
    <label>Number Rollup Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Trigger_Rollup_Rule__c/fields/Unique_Values__c.field-meta.xml
<CustomField>
    <fullName>Unique_Values__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Should values be added once? Only applies to delimited list type rollups.</inlineHelpText>
    <label>Unique Values</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/TEST_Trigger_RollUp.cls
@isTest(SeeAllData=false)
private with sharing class TEST_Trigger_RollUp {
    static testMethod void Test_Trigger_Rollup_MaxMin() {
        Trigger_Rollup_Rule__c customSetting = new Trigger_Rollup_Rule__c();
        customSetting.Name = 'Test Max Min Rollup';
        customSetting.Object__c = 'Account';
        customSetting.Child_Object__c = 'Opportunity';
        customSetting.Child_Field__c = 'Amount';
        customSetting.Child_Parent_Field__c = 'AccountId';
        customSetting.Field__c = 'Description';
        customSetting.Type__c = 'Max';
        customSetting.Child_Query_Group__c = 'Amount';
        customSetting.Child_Query_Where_Clause__c = 'StageName=\'test\'';
        insert customSetting;

        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Investment_Vehicle__c inv = new Investment_Vehicle__c(Name='Test Invesment Vehicle');
        insert inv;

        List<Opportunity> testProjects = new List<Opportunity>();
        testProjects.add(new Opportunity(Name = 'Project 1', Amount = 2000, AccountId = testAccount.Id, Investment_Vehicle__c=inv.Id, StageName='test', CloseDate=System.today()));
        testProjects.add(new Opportunity(Name = 'Project 2', Amount = 3000, AccountId = testAccount.Id, Investment_Vehicle__c=inv.Id, StageName='test', CloseDate=System.today()));

        Test.startTest();
        insert testProjects;
        testAccount.Description = 'Hello World';
        update testAccount;

        testAccount = [SELECT Id, Description FROM Account WHERE Id = :testAccount.Id];
        System.assertNotEquals(null, testAccount.Description);
        Test.stopTest();
    }

    static testMethod void Test_Trigger_Rollup_Lookup() {
        Trigger_Rollup_Rule__c customSetting = new Trigger_Rollup_Rule__c();
        customSetting.Name = 'Project TeamMember';
        customSetting.Object__c = 'Account';
        customSetting.Child_Object__c = 'Contact';
        customSetting.Child_Field__c = 'Account.Name';
        customSetting.Child_Parent_Field__c = 'AccountId';
        customSetting.Field__c = 'Description';
        customSetting.Field_RTF__c = 'SicDesc';
        customSetting.DelimitedList_Delimiter__c = 'testDelimiter';
        customSetting.Type__c = 'DelimitedList';

        insert customSetting;

        Account account1 = new Account();
        account1.Name = 'Test Account';
        insert account1;

        Contact contact1 = new Contact();
        contact1.FirstName = 'Test';
        contact1.LastName = 'Contact';
        contact1.AccountId = account1.Id;
        insert contact1;

        update account1;

        Account updatedAccount = [select Id, Description, SicDesc from Account where Id=:account1.Id limit 1];
        system.assertEquals('Test Account', updatedAccount.Description);
        system.debug('Log 1: ' + updatedAccount.Description);
        system.debug('Log 2: ' + updatedAccount.SicDesc);

        Contact contact2 = new Contact();
        contact2.FirstName = 'Test2';
        contact2.LastName = 'NewContact';
        contact2.AccountId = account1.Id;
        insert contact2;

        update account1;

        updatedAccount = [select Id, Description, SicDesc from Account where Id=:account1.Id limit 1];
        system.debug('Log 3: ' + updatedAccount.Description);
        system.debug('Log 4: ' + updatedAccount.SicDesc);
    }

    static testMethod void Test_Trigger_Rollup_NoLookup() {
        Trigger_Rollup_Rule__c customSetting = new Trigger_Rollup_Rule__c();
        customSetting.Name = 'Project TeamMember';
        customSetting.Object__c = 'Account';
        customSetting.Child_Object__c = 'Contact';
        customSetting.Child_Field__c = 'Id';
        customSetting.Child_Parent_Field__c = 'AccountId';
        customSetting.Field__c = 'Description';
        customSetting.Field_RTF__c = 'SicDesc';
        customSetting.DelimitedList_Delimiter__c = 'testDelimiter';
        customSetting.Type__c = 'DelimitedList';
        customSetting.Unique_Values__c = true;

        insert customSetting;

        Account account1 = new Account();
        account1.Name = 'Test Account';
        insert account1;

        Test.startTest();
        Contact contact1 = new Contact();
        contact1.FirstName = 'Test';
        contact1.LastName = 'Contact';
        contact1.AccountId = account1.Id;
        insert contact1;

        update account1;

        Account updatedAccount = [select Id, Description, SicDesc from Account where Id=:account1.Id limit 1];
        system.assertEquals(contact1.Id, updatedAccount.Description);
        system.debug('Log 1: ' + updatedAccount.Description);
        system.debug('Log 2: ' + updatedAccount.SicDesc);

        Contact contact2 = new Contact();
        contact2.FirstName = 'Test2';
        contact2.LastName = 'NewContact';
        contact2.AccountId = account1.Id;
        insert contact2;

        update account1;

        Test.stopTest();

        updatedAccount = [select Id, Description, SicDesc from Account where Id=:account1.Id limit 1];
        system.debug('Log 3: ' + updatedAccount.Description);
        system.debug('Log 4: ' + updatedAccount.SicDesc);
    }

    static testMethod void Test_Trigger_Rollup_NumberRollup() {
        Trigger_Rollup_Rule__c customSetting = new Trigger_Rollup_Rule__c();
        customSetting.Name = 'Account Vehicle - Total Finaccount Am';
        customSetting.Object__c = 'Account';
        customSetting.Child_Object__c = 'Investor_Position__c';
        customSetting.Child_Field__c = 'AUM_Number__c';
        customSetting.Child_Parent_Field__c = 'Investor_Position_Account__c';
        customSetting.Field__c = 'Asset_Lending__c';
        customSetting.Type__c = 'NumberRollup';
        customSetting.Number_Rollup_Type__c = 'SUM';

        insert customSetting;

        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Investment_Vehicle__c inv = new Investment_Vehicle__c(Name='Test Invesment Vehicle');
        insert inv;
        Opportunity o = new Opportunity(Name='Test Opp', StageName='test', CloseDate=system.today(), Investment_Vehicle__c=inv.Id, AccountId=testAccount.Id);
        insert o;

        List<Investor_Position__c> testProjects = new List<Investor_Position__c>();
        testProjects.add(new Investor_Position__c(Name = 'Project 1', AUM_Number__c = 2000, Investor_Position_Account__c = testAccount.Id, Investment_Vehicle__c=inv.Id, Current_Commitments_USD__c=10, Opportunity_Name__c=o.Id));
        testProjects.add(new Investor_Position__c(Name = 'Project 2', AUM_Number__c = 3000, Investor_Position_Account__c = testAccount.Id, Investment_Vehicle__c=inv.Id, Current_Commitments_USD__c=11, Opportunity_Name__c=o.Id));

        Test.startTest();
        insert testProjects;
        testAccount.Description = 'Hello World';
        update testAccount;

        testAccount = [SELECT Id, NumberOfEmployees FROM Account WHERE Id = :testAccount.Id];
        Test.stopTest();
    }
}