PROD_10-24-19/force-app/main/default/objects/Account/fields/BAM_Units_Shares__c.field-meta.xml
<CustomField>
    <fullName>BAM_Units_Shares__c</fullName>
    <label>BAM # Units / Shares</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/BEP_Units_Shares__c.field-meta.xml
<CustomField>
    <fullName>BEP_Units_Shares__c</fullName>
    <label>BEP # Units / Shares</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/BIM_Total_AUM__c.field-meta.xml
<CustomField>
    <fullName>BIM_Total_AUM__c</fullName>
    <label>PSG Total AUM</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account/fields/BIP_Units_Shares__c.field-meta.xml
<CustomField>
    <fullName>BIP_Units_Shares__c</fullName>
    <label>BIP # Units / Shares</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Account/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <label>Consultant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <description>This field was created originally for the Spotlight summary, to ensure it is kept in SF for future use.  This will also be used for PMRs as needed.</description>
    <inlineHelpText>Used for Splotlight and PMRs.  Please ensure when entering text, that it is short and concise.</inlineHelpText>
    <label>Investor Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Configurable_RollUp_Setting__c/Configurable_RollUp_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Configurable RollUp Setting</label>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Configurable_RollUp_Setting__c/fields/Relationship_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field_API_Name__c</fullName>
    <description>API name of related object (parent object) to which rollup will be saved</description>
    <inlineHelpText>API name of related object (parent object) to which rollup will be saved</inlineHelpText>
    <label>Relationship Field API Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Configurable_RollUp_Setting__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Configurable_RollUp_Setting__c/fields/Source_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Name__c</fullName>
    <label>Source Object Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Configurable_RollUp_Setting__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Action name, which will perform on the field.</description>
    <inlineHelpText>Action name, which will perform on the field.</inlineHelpText>
    <label>Sum</label>
    <type>Checkbox</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Configurable_RollUp_Setting__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant Relationship</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Consultant Rel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultant Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Consultant__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Consultant_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Fund Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Ticker__c.field-meta.xml
<CustomField>
    <fullName>Ticker__c</fullName>
    <label>Ticker</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investment_Vehicle__c/recordTypes/Public_Securities.recordType-meta.xml
<RecordType>
    <fullName>Public_Securities</fullName>
    <active>true</active>
    <description>PSG Strategy</description>
    <label>Public Securities</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/Investor_Position__c.object-meta.xml
<CustomObject>
    <label>Investor Position</label>
    <nameField>
        <label>Investor Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investor Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/BAM_Units_Shares_RU_Filter__c.field-meta.xml
<CustomField>
    <fullName>BAM_Units_Shares_RU_Filter__c</fullName>
    <formula>IF(AND(Is_Active__c = true,  ISPICKVAL(Ticker__c, &#39;BAM&#39;), RecordType.Name =&#39;Listed Issuers&#39;), Units_Shares__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BAM # Units / Shares_RU_Filter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/BEP_Units_Shares_RU_Filter__c.field-meta.xml
<CustomField>
    <fullName>BEP_Units_Shares_RU_Filter__c</fullName>
    <formula>IF(AND(Is_Active__c = True,  ISPICKVAL(Ticker__c, &#39;BEP&#39;),  RecordType.Name =&#39;Listed Issuers&#39;), Units_Shares__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BEP # Units / Shares RU Filter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/BIM_Total_AUM_RU_Filter__c.field-meta.xml
<CustomField>
    <fullName>BIM_Total_AUM_RU_Filter__c</fullName>
    <formula>IF(AND(Is_Active__c = true, RecordType.Name =&#39;Public Securities&#39;), Market_Value_AUM_Quarter__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSG Total AUM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investor_Position__c/fields/BIP_Units_Shares_RU_Filter__c.field-meta.xml
<CustomField>
    <fullName>BIP_Units_Shares_RU_Filter__c</fullName>
    <formula>IF(AND(Is_Active__c = true, ISPICKVAL(Ticker__c, &#39;BIP&#39;),  RecordType.Name =&#39;Listed Issuers&#39;), Units_Shares__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BIP # Units / Shares</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advised Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions_Consultant</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investor_Position__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle</value>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please DO NOT Create Investor Position for Inactive, Discontinued, Closed Vehicles</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>DO NOT USE New Investor Account record</description>
    <inlineHelpText>DO NOT USE New Investor Account record</inlineHelpText>
    <label>xAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investor Positions (Account)</relationshipLabel>
    <relationshipName>Investor_Positions1</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Investor_Position_Account__c.field-meta.xml
<CustomField>
    <fullName>Investor_Position_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Investor Account record</description>
    <inlineHelpText>New Investor Account record</inlineHelpText>
    <label>Investor Position Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investor Positions (All)</relationshipLabel>
    <relationshipName>Investor_Positions2</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Investor_Position__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copied from originating opportunity. Populates automatically.</inlineHelpText>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Investor Positions</relationshipLabel>
    <relationshipName>Investor_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/fields/Ticker__c.field-meta.xml
<CustomField>
    <fullName>Ticker__c</fullName>
    <label>Ticker</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BIP</fullName>
            </value>
            <value>
                <fullName>BPY</fullName>
            </value>
            <value>
                <fullName>BEP</fullName>
            </value>
            <value>
                <fullName>BPO</fullName>
            </value>
            <value>
                <fullName>BOX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Investor_Position__c/recordTypes/Public_Securities.recordType-meta.xml
<RecordType>
    <fullName>Public_Securities</fullName>
    <active>true</active>
    <description>PSG Strategy</description>
    <label>Parent Public Securities</label>
</RecordType>

PROD_10-24-19/force-app/main/default/objects/Opportunity/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</description>
    <inlineHelpText>Enter related/known consultant(s) relationships (if applicable) by using the lookup function</inlineHelpText>
    <label>Consultant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advised Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Opportunity/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</description>
    <inlineHelpText>Investment vehicle (e.g., the fund or co-investment) name by using the lookup function</inlineHelpText>
    <label>Investment Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Vehicle__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Discontinued, Closed</value>
        </filterItems>
        <filterItems>
            <field>Investment_Vehicle__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Archived and Deactivated Investment Vehicle, Inactive Record Type</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Id</field>
            <operation>equals</operation>
            <valueField>$User.UserRoleId</valueField>
        </filterItems>
        <infoMessage>Filtered by Funds in the Market. Click SHOW ALL to expand the list. Please don&#39;t create Opportunities for inactive or closed Vehicles.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Opportunity/recordTypes/BAM.recordType-meta.xml
<RecordType>
    <fullName>BAM</fullName>
    <active>true</active>
    <businessProcess>BAM</businessProcess>
    <description>Brookfield Asset Management Default Opportunity Type</description>
    <label>BAM</label>
</RecordType>

PROD_10-24-19/force-app/main/default/classes/ConfigurableRollupTest.cls
@isTest
private class ConfigurableRollupTest {
    
    static testMethod void rollupTestBAMUnitsSharesRUFilterInsertUpdate() {
        test.startTest();
        Configurable_RollUp_Setting__c crs = new Configurable_RollUp_Setting__c(name = 'configurableRollUpSetting',Relationship_Field_API_Name__c = 'Investor_Position_Account__c',Source_Field__c = 'BAM_Units_Shares_RU_Filter__c',Source_Object_Name__c = 'Investor_Position__c',Sum__c = true,Target_Field__c = 'BAM_Units_Shares__c');
        insert crs;
        
        Account ac = new Account(Name = 'TestAccount');
        insert ac;
        
        String recType = [Select Id from RecordType where Name = 'Listed Issuers' And SobjectType ='Investor_Position__c' limit 1].id; 
        
        Investment_Vehicle__c iv = new Investment_Vehicle__c(Name = 'InvestmentVehicleName'); 
        insert iv;
        

        //SS: 7/18/18 added following line of code for code coverage
        Opportunity opt = new Opportunity(Name = 'NewTestOpportunity', StageName ='2 - Initiated General Contact', CloseDate = system.today() , Investment_Vehicle__c = iv.id, AccountId = ac.id,  Consultant__c = ac.id  );
        insert opt; 

        //SS: 7/18/18 updated following line of code for code coverage
        Investor_Position__c ip = new Investor_Position__c(Is_Active__c = true,Ticker__c = 'BAM',RecordTypeId = recType,Investment_Vehicle__c = iv.id ,Investor__c = ac.id,Investor_Position_Account__c = ac.id, Opportunity_Name__c = opt.id);
        insert ip;
        
        Account account = [select Id, Name , BAM_Units_Shares__c from account where id =:ac.id];
        system.assertEquals(0.0,account.BAM_Units_Shares__c);
        
        //SS: 7/18/18 updated following line of code for code coverage
        Investor_Position__c ip1 = new Investor_Position__c(id = ip.id, Is_Active__c = false,Ticker__c = 'BAM',RecordTypeId = recType,Investment_Vehicle__c = iv.id ,Investor__c = ac.id,Investor_Position_Account__c = ac.id, Opportunity_Name__c = opt.id);
        update ip1;
        
        Account account1 = [select Id, Name , BAM_Units_Shares__c from account where id =:ac.id];
        system.assertEquals(0.0,account1.BAM_Units_Shares__c);
        
        test.stopTest(); 
    }
    
    static testMethod void rollupTestBEPUnitsSharesRUFilter() {
        test.startTest();
        Configurable_RollUp_Setting__c crs = new Configurable_RollUp_Setting__c(name = 'configurableRollUpSetting1',Relationship_Field_API_Name__c = 'Investor_Position_Account__c',Source_Field__c = 'BEP_Units_Shares_RU_Filter__c',Source_Object_Name__c = 'Investor_Position__c',Sum__c = true,Target_Field__c = 'BEP_Units_Shares__c');
        insert crs;
        
        Account ac = new Account(Name = 'TestAccount');
        insert ac;
        
        String recType = [Select Id from RecordType where Name = 'Listed Issuers' And SobjectType ='Investor_Position__c' limit 1].id; 
        
        Investment_Vehicle__c iv = new Investment_Vehicle__c(Name = 'InvestmentVehicleName'); 
        insert iv;
        
        //SS: 7/18/18 added following line of code for code coverage
        Opportunity opt = new Opportunity(Name = 'NewTestOpportunity', StageName ='2 - Initiated General Contact', CloseDate = system.today() , Investment_Vehicle__c = iv.id, AccountId = ac.id,  Consultant__c = ac.id  );
        insert opt; 

        //SS: 7/18/18 updated following line of code for code coverage
        Investor_Position__c ip = new Investor_Position__c(Is_Active__c = true,Ticker__c = 'BEP',RecordTypeId = recType,Investment_Vehicle__c = iv.id ,Investor__c = ac.id,Investor_Position_Account__c = ac.id, Opportunity_Name__c = opt.id);
        insert ip;
        
        Account account = [select Id, Name , BEP_Units_Shares__c from account where id =:ac.id];
        
        test.stopTest();
        system.assertEquals(0.0,account.BEP_Units_Shares__c);
    }

    static testMethod void rollupTestBIMTotalAUMRUFilter(){
        test.startTest();
        Configurable_RollUp_Setting__c crs = new Configurable_RollUp_Setting__c(name = 'configurableRollUpSetting2',Relationship_Field_API_Name__c = 'Investor_Position_Account__c',Source_Field__c = 'BIM_Total_AUM_RU_Filter__c',Source_Object_Name__c = 'Investor_Position__c',Sum__c = true,Target_Field__c = 'BIM_Total_AUM__c');
        insert crs;
        
        Account ac = new Account(Name = 'TestAccount');
        insert ac;
        
        String recType = [Select Id from RecordType where DeveloperName = 'Public_Securities' And SobjectType ='Investor_Position__c' limit 1].id; 
        
        Investment_Vehicle__c iv = new Investment_Vehicle__c(Name = 'InvestmentVehicleName'); 
        insert iv;
        
        //SS: 7/18/18 added following line of code for code coverage
        Opportunity opt = new Opportunity(Name = 'NewTestOpportunity', StageName ='2 - Initiated General Contact (PSG)', CloseDate = system.today() , Investment_Vehicle__c = iv.id, AccountId = ac.id,  Consultant__c = ac.id  );
        insert opt; 

        //SS: 7/18/18 updated following line of code for code coverage
        Investor_Position__c ip = new Investor_Position__c(Is_Active__c = true,RecordTypeId = recType,Investment_Vehicle__c = iv.id ,Investor__c = ac.id,Investor_Position_Account__c = ac.id, Opportunity_Name__c = opt.id);
        insert ip;
        
        Account account = [select Id, Name , BIM_Total_AUM__c from account where id =:ac.id];
        
        test.stopTest();
        system.assertEquals(0.0,account.BIM_Total_AUM__c);
    }

    static testMethod void rollupTestBIPUnitsSharesRUFilter(){
        test.startTest();
        Configurable_RollUp_Setting__c crs = new Configurable_RollUp_Setting__c(name = 'configurableRollUpSetting3',Relationship_Field_API_Name__c = 'Investor_Position_Account__c',Source_Field__c = 'BIP_Units_Shares_RU_Filter__c',Source_Object_Name__c = 'Investor_Position__c',Sum__c = true,Target_Field__c = 'BIP_Units_Shares__c');
        insert crs;
        
        Account ac = new Account(Name = 'TestAccount');
        insert ac;
        
        String recType = [Select Id from RecordType where Name = 'Listed Issuers' And SobjectType ='Investor_Position__c' limit 1].id; 
        
        Investment_Vehicle__c iv = new Investment_Vehicle__c(Name = 'InvestmentVehicleName'); 
        insert iv;
        
        //SS: 7/18/18 added following line of code for code coverage
        Opportunity opt = new Opportunity(Name = 'NewTestOpportunity', StageName ='2 - Initiated General Contact', CloseDate = system.today() , Investment_Vehicle__c = iv.id, AccountId = ac.id,  Consultant__c = ac.id  );
        insert opt; 

        //SS: 7/18/18 updated following line of code for code coverage
        Investor_Position__c ip = new Investor_Position__c(Is_Active__c = true, Ticker__c = 'BIP',RecordTypeId = recType,Investment_Vehicle__c = iv.id ,Investor__c = ac.id,Investor_Position_Account__c = ac.id, Opportunity_Name__c = opt.id);
        insert ip;
        
        Account account = [select Id, Name , BIP_Units_Shares__c from account where id =:ac.id];
        
        test.stopTest();
        system.assertEquals(0.0,account.BIP_Units_Shares__c);
    }
}