PROD_10-24-19/force-app/main/default/objects/Account/fields/Company_Background__c.field-meta.xml
<CustomField>
    <fullName>Company_Background__c</fullName>
    <description>Historical information about the account</description>
    <inlineHelpText>Historical information about the account</inlineHelpText>
    <label>Firm Background</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Account/fields/QI_Status_Notes__c.field-meta.xml
<CustomField>
    <fullName>QI_Status_Notes__c</fullName>
    <label>QI Status Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Compliance__c/Compliance__c.object-meta.xml
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <displayFormat>C - {0}</displayFormat>
        <label>Compliance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-9-26-19/force-app/main/default/objects/Compliance__c/fields/Company_Background__c.field-meta.xml
<CustomField>
    <fullName>Company_Background__c</fullName>
    <label>Company Background</label>
    <type>TextArea</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Compliance__c/fields/Prospect_Name__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Name__c</fullName>
    <label>Prospect Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>KYC_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PROD-12120/force-app/main/default/classes/Test_UpdateCompanyBackground.cls
@isTest

public class Test_UpdateCompanyBackground {
       
    public static testMethod void createNewAccount() {        
    Account TestAccount = new Account();
    TestAccount.Name = 'Test Account for Testing';
    TestAccount.Company_Background__c = 'Initial Company background';
    TestAccount.QI_Status_Notes__c = 'Initial QI Status Note';      
    insert TestAccount;
        
    Compliance__c TestCompliance = new Compliance__c();
    TestCompliance.Prospect_Name__c = TestAccount.Id;
    TestCompliance.Company_Background__c = '';    
    insert TestCompliance;
    
    TestAccount.Company_Background__c = 'Updated Company Background'; 
    TestAccount.QI_Status_Notes__c = 'Updated QI Status Note';
    update TestAccount; 
    }   
    }