PROD_10-24-19/force-app/main/default/objects/Account/fields/Top_Account__c.field-meta.xml
<CustomField>
    <fullName>Top_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Key Account</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account_Summary__c/Account_Summary__c.object-meta.xml
<CustomObject>
    <label>Property Enquiries</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Property Inquiries ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Account_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-9-26-19/force-app/main/default/objects/Account_Summary__c/fields/Account_Summary__c.field-meta.xml
<CustomField>
    <fullName>Account_Summary__c</fullName>
    <label>Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Account_Summary__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Account_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/classes/Test_AccountSummaryReportController.cls
/******************************************
Test Class Name - Test_AccountSummaryReportController
Created by - Samir Khan
Description - This test class is written for AccountSummaryReportController 
******************************************/
@isTest(seeAllData = false)
public class Test_AccountSummaryReportController {

    public static testMethod void testRunAs() {
        
        Account acct = new Account(Name = 'Apex Test', Top_Account__c = true);
        insert acct;
        
        Property__c objProperty = new Property__c(name = 'Apex Test');
        insert objProperty;
    
        Account_Summary__c accSumm = new Account_Summary__c (Account_Summary__c = 'Testing', Country__c = 'IN', Property__c = objProperty.id, Account__c = acct.id);
        insert accSumm;
        
        AccountSummaryReportController test = new AccountSummaryReportController();
        test.loadKeyAccounts();
        test.renderAsPdf();
        
        AccountSummaryReportControllerByAccounts test1 = new AccountSummaryReportControllerByAccounts();
        test1.loadKeyAccounts();
        test1.renderAsPdf();
        
        GroupByAccountsController  test2 = new GroupByAccountsController ();
        test2.loadKeyAccounts();
        test2.renderAsPdf(); 
    }

    /**
      * BF-1: Improving Code Coverage
      */
    public static testMethod void AccountSummaryWithLocation() {
        Account acct = new Account(Name = 'Apex Test', Top_Account__c = true);
        insert acct;
        
        Property__c objProperty = new Property__c(name = 'Apex Test');
        Property__c objProperty2 = new Property__c(name = 'Apex Test2');
        List<Property__c> propertyList = new List<Property__c>{objProperty, objProperty2};
        insert propertyList;
    
        Account_Summary__c accSumm = new Account_Summary__c (Account_Summary__c = 'Testing', Country__c = 'IN', Property__c = objProperty.id, Account__c = acct.id);
        Account_Summary__c accSumm2 = new Account_Summary__c (Account_Summary__c = 'Testing2', Country__c = 'IN', Property__c = objProperty.id, Account__c = acct.id);
        Account_Summary__c accSumm3 = new Account_Summary__c (Account_Summary__c = 'Testing3', Country__c = 'IN', Property__c = objProperty2.id, Account__c = acct.id);
        List<Account_Summary__c> asList = new List<Account_Summary__c>{accSumm, accSumm2, accSumm3};
        insert asList;
        
        AccountSummaryReportController test = new AccountSummaryReportController();
        test.loadKeyAccounts();
        test.renderAsPdf();
    }
}