PROD-12-18-19/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>No longer with Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WMG112519/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Short Listed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>General Interest</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Pre-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Fully Divested</fullName>
            </value>
            <value>
                <fullName>Wound Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission__c/Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <displayFormat>PM-{000000000}</displayFormat>
        <label>Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Account_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Account_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Account_Vehicle__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Finaccount__c.field-meta.xml
<CustomField>
    <fullName>Finaccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commitment</label>
    <referenceTo>Finaccount__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Permission_Type__c.field-meta.xml
<CustomField>
    <fullName>Permission_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Type</label>
    <referenceTo>Permission_Type__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Type__c/Permission_Type__c.object-meta.xml
<CustomObject>
    <label>Permission Type</label>
    <nameField>
        <label>Permission Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Permission_Type__c/fields/Default_Active__c.field-meta.xml
<CustomField>
    <fullName>Default_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Active</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Type__c/fields/Default_Alert__c.field-meta.xml
<CustomField>
    <fullName>Default_Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Alert</label>
    <type>Checkbox</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/SmartWidget__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SmartWidget</label>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Related_Field__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Related_Field__c</fullName>
    <label>AutoComplete Related Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Search_Object__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Search_Object__c</fullName>
    <label>AutoComplete Search Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Target_Field__c</fullName>
    <label>AutoComplete Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Target_Object__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Target_Object__c</fullName>
    <label>AutoComplete Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/SmartWidget__c/fields/AutoComplete_Target_Parent_Field__c.field-meta.xml
<CustomField>
    <fullName>AutoComplete_Target_Parent_Field__c</fullName>
    <label>AutoComplete Target Parent Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PROD-12-18-19/force-app/main/default/classes/TEST_ManagePermission_Controller.cls
@isTest(SeeAllData=false)
public with sharing class TEST_ManagePermission_Controller {
    private static final String NAMESPACE = '';

    @testSetup
    static void setupTest(){
        //Create PermissionConfig
        //Create SmartWidgets
        List<SmartWidget__c> smartWidgets = new List<SmartWidget__c>();

        SmartWidget__c relatedContacts = new SmartWidget__c();
        relatedContacts.Name = 'Permission_RelatedContacts_Contact';
        relatedContacts.AutoComplete_Target_Field__c = 'Name,Email';
        relatedContacts.AutoComplete_Target_Object__c = NAMESPACE+'Permission__c';
        relatedContacts.AutoComplete_Search_Object__c = 'Contact';
        relatedContacts.AutoComplete_Target_Parent_Field__c = 'AccountId';
        relatedContacts.Field__c = NAMESPACE+'Contact__c';
        relatedContacts.Filter__c = 'AccountId = \'parentId\'';
        relatedContacts.Label__c = 'Contacts';
        relatedContacts.Object__c = 'Contact';
        relatedContacts.Type__c = 'Multipicklist';
        smartWidgets.add(relatedContacts);
        insert relatedContacts;
        SmartWidget__c relatedInvestments = new SmartWidget__c();
        relatedInvestments.Name = 'Permission_RelatedCommitment';
        relatedInvestments.AutoComplete_Search_Object__c = NAMESPACE+'Finaccount__c';
        //relatedInvestments.AutoComplete_Related_Field__c = NAMESPACE+'Account_Vehicle__r.Name,'+NAMESPACE+'Fund__r.Name';
        relatedInvestments.AutoComplete_Target_Object__c = NAMESPACE+'Permission__c';
        relatedInvestments.AutoComplete_Target_Parent_Field__c = NAMESPACE+'Account__c';
        relatedInvestments.Field__c = NAMESPACE+'Finaccount__c';
        relatedInvestments.Filter__c = NAMESPACE+'Account__c = \'parentId\'';
        relatedInvestments.Label__c = 'Investment';
        relatedInvestments.Object__c = NAMESPACE+'Finaccount__c';
        relatedInvestments.Type__c = 'Multipicklist';
        smartWidgets.add(relatedInvestments);
        insert relatedInvestments;

        //Create permission types
        List<Permission_Type__c> permissionTypes = new List<Permission_Type__c>();
        Permission_Type__c dist = new Permission_Type__c();
        dist.Name = 'Distribution';
        dist.Default_Active__c = true;
        dist.Default_Alert__c = false;
        permissionTypes.add(dist);

        Permission_Type__c legal = new Permission_Type__c();
        legal.Name = 'Legal';
        legal.Default_Active__c = false;
        legal.Default_Alert__c = false;
        permissionTypes.add(legal);

        Permission_Type__c dm = new Permission_Type__c();
        dm.name = 'DM';
        DM.Default_Active__c = false;
        DM.Default_Alert__c = false;
        permissionTypes.add(dm);

        Permission_Type__c cp = new Permission_Type__c();
        cp.Name = 'CP';
        cp.Default_Active__c = true;
        cp.Default_Alert__c = true;
        permissionTypes.add(cp);

        Permission_Type__c so = new Permission_Type__c();
        so.Name = 'SO';
        so.Default_Active__c = false;
        so.Default_Alert__c = false;
        permissionTypes.add(so);

        insert permissionTypes;
        //Create account
        List<Account> accounts = new List<Account>();

        Account acme = new Account();
        acme.Name = 'Acme';
        Accounts.add(acme);

        insert Accounts;

        //Create Contact
        List<Contact> contacts = new List<Contact>();
        Contact Bob = new Contact();
        Bob.FirstName = 'Bob';
        Bob.LastName = 'TestingPermissionInit';
        Bob.AccountId = acme.Id;
        contacts.add(bob);
        insert contacts;
        //Create Fund
//        List<Investment_Vehicle__c> funds = new List<Investment_Vehicle__c>();
        Investment_Vehicle__c fun = new Investment_Vehicle__c();
        fun.Name = 'Test FUN';
        insert fun;
//        insert funds;
        //Create Investment
        Finaccount__c fin = new Finaccount__c();
        fin.Account__c = acme.Id;
        fin.Investment_Vehicle__c = fun.Id;
        insert fin;

    }

    @isTest
    static void testInit(){
//        setupTest();
        Map<String,String> params = new Map<String, String>();
        params.put('configurationName','PermissionManager_Contact_Alerts');

        Contact contactRecord = [SELECT Id FROM Contact WHERE LastName='TestingPermissionInit' LIMIT 1];
        Id recordId = contactRecord.Id;
        params.put('recordId',recordId);

        Map<String,String> initResponse = ManagePermission_Controller.initializeComponent(params);
        system.debug('Init Response: '+initResponse);
    }
    @isTest
    static void testSave(){
        Map<String,String> params = new Map<String, String>();
        params.put('configurationName','PermissionManager_Contact_Alerts');

        Contact contactRecord = [SELECT Id FROM Contact WHERE LastName='TestingPermissionInit' LIMIT 1];
        Id recordId = contactRecord.Id;
        params.put('recordId',recordId);
        //params.put('defaultedPermissionTypes',);

        Map<String,String> initResponse = ManagePermission_Controller.initializeComponent(params);


        params = new Map<String,String>();
        List<Permission__c> permissions = new List<Permission__c>();

        String permissionJSON;
        Permission__c p = new Permission__c();
        p.Contact__c = [SELECT Id FROM Contact WHERE LastName='TestingPermissionInit' LIMIT 1].Id;
        p.Status__c = 'Active';
        p.Permission_Type__c = [SELECT Id FROM Permission_Type__c WHERE Name = 'Legal' LIMIT 1].Id;
        p.Fund__c = [SELECT Id FROM Investment_Vehicle__c LIMIT 1].Id;
        permissions.add(p);

        permissionJSON = JSON.serialize(permissions);


        params.put('pmsListJSON',permissionJSON);
        params.put('configJSON', initResponse.get('config'));
        params.put('widgetsJSON', initResponse.get('widgets'));
        Map<String,String> saveResponse = ManagePermission_Controller.savePermissionTable(params);
        system.debug('Save Response: '+saveResponse);
    }
    @isTest
    static void testRestrictedUser(){

    }
}