PROD_10-24-19/force-app/main/default/objects/Contact/fields/DX_Email__c.field-meta.xml
<CustomField>
    <fullName>DX_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>DX Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>No longer with Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WMG112519/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/Investment_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Investment Vehicle</label>
    <nameField>
        <label>Investment Vehicle Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/DX_Integration__c.field-meta.xml
<CustomField>
    <fullName>DX_Integration__c</fullName>
    <label>DX Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Investment_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Investment_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Fund to this co-investment</description>
    <inlineHelpText>Related Fund to this co-investment</inlineHelpText>
    <label>Related Fund</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Co-Investments</relationshipLabel>
    <relationshipName>Investment_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Short Listed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>General Interest</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Pre-Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Fully Divested</fullName>
            </value>
            <value>
                <fullName>Wound Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Investment_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canadian Pooled Fund</fullName>
            </value>
            <value>
                <fullName>Closed End Fund</fullName>
            </value>
            <value>
                <fullName>General Overview</fullName>
            </value>
            <value>
                <fullName>Hedge Fund</fullName>
            </value>
            <value>
                <fullName>Listed Issuers</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Private Fund - Open Ended</fullName>
            </value>
            <value>
                <fullName>Private Fund</fullName>
            </value>
            <value>
                <fullName>Separate Accounts</fullName>
            </value>
            <value>
                <fullName>Separately Managed Account</fullName>
            </value>
            <value>
                <fullName>UCITS</fullName>
            </value>
            <value>
                <fullName>Co-Invest</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Sale of Asset</fullName>
            </value>
            <value>
                <fullName>Private Fund - Closed Ended</fullName>
            </value>
            <value>
                <fullName>SMA</fullName>
            </value>
            <value>
                <fullName>Direct Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PROD_10-24-19/force-app/main/default/objects/Permission__c/Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <displayFormat>PM-{000000000}</displayFormat>
        <label>Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Account_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Account_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Account_Vehicle__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Finaccount__c.field-meta.xml
<CustomField>
    <fullName>Finaccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commitment</label>
    <referenceTo>Finaccount__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Vehicle</label>
    <referenceTo>Investment_Vehicle__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission__c/fields/Permission_Type__c.field-meta.xml
<CustomField>
    <fullName>Permission_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Type</label>
    <referenceTo>Permission_Type__c</referenceTo>
    <relationshipLabel>Permissions</relationshipLabel>
    <relationshipName>Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

PROD-12-18-19/force-app/main/default/objects/Permission_Type__c/Permission_Type__c.object-meta.xml
<CustomObject>
    <label>Permission Type</label>
    <nameField>
        <label>Permission Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PROD-12-18-19/force-app/main/default/classes/Test_VehicleHandler.cls
@isTest(SeeAllData = false)
public class Test_VehicleHandler {
    @testSetup 
  	static void setup(){
       
      	Contact testContact = new Contact(FirstName='Test', LastName='TestlastName',Email='test@test.com',DX_Email__C='test1@test.com');
        insert testContact;
        Account acc = new Account(Name = 'testAcc') ;
        insert acc;
        Permission_Type__c pType = new Permission_Type__c(Name = 'test');
        insert pType;
            
  	}
    
    static testMethod void test_createPlatformEvents(){
        Investment_Vehicle__c testInvestmentVehicle = new Investment_Vehicle__c(Vehicle_Type__c = 'Co-Invest',Name='CoTest', DX_Integration__c ='Planned'); 
         Investment_Vehicle__c testInvestmentVehicle2 = new Investment_Vehicle__c(Vehicle_Type__c = 'Co-Invest',Name='CoTest', DX_Integration__c ='Active');
        Account accObj = [Select id,name from account limit 1];
        
        test.startTest();
        insert testInvestmentVehicle;
        insert testInvestmentVehicle2;
        Investment_Vehicle__c investment_vehicle_Obj = [select Id,DX_Integration__c,Name from Investment_Vehicle__c limit 1];   
          
        Contact contact_Obj =[Select id,Email,Dx_Email__c from Contact limit 1];        
        Permission_Type__c ptypeObj = [select id,name from Permission_Type__c limit 1];
        
        Account_Vehicle__c legalEntity = new Account_Vehicle__c(Name = 'test',Account__c = accObj.id );
        insert legalEntity;
        Account_Vehicle__c legalEntityObj = [Select id,name from Account_Vehicle__c limit 1];
             
        investment_vehicle_Obj.Name = 'Test22';
        update investment_vehicle_Obj;
        
        Finaccount__c testCommitment =  new Finaccount__c(Investment_Vehicle__c = investment_vehicle_Obj.id,Account__c =accObj.id,Account_Vehicle__c =legalEntityObj.id );
        insert testCommitment;
        Finaccount__c testCommitment2 =  new Finaccount__c(Investment_Vehicle__c = investment_vehicle_Obj.id,Account__c =accObj.id,Account_Vehicle__c =legalEntityObj.id );
        insert testCommitment2;
        Finaccount__c finaccount_Obj = [Select Id,Investment_Vehicle__r.id,Account_Vehicle__r.id From Finaccount__c limit 1 ];
        
        List<DX_FundIntegration__e> avEventlst = new List<DX_FundIntegration__e>();  
      	Permission__c permission_Objlst = new Permission__c(Account_Vehicle__c =legalEntityObj.Id, Permission_Type__c=ptypeObj.Id,Finaccount__c = finaccount_Obj.id, Contact__c = contact_Obj.id, Fund__c = investment_vehicle_Obj.id, Status__c = 'Active');
        insert permission_Objlst;
        investment_vehicle_Obj.DX_Integration__c ='Active';
        update investment_vehicle_Obj;
      /*  for(Finaccount__c c : [Select id,name,Investment_Vehicle__r.id,Account_Vehicle__r.id,Account_Vehicle__r.Name,Investment_Vehicle__r.DX_Integration__c,Investment_Vehicle__r.Name from Finaccount__c 
                               					where Account_Vehicle__r.id =:legalEntityObj.Id and Investment_Vehicle__r.DX_Integration__c IN: new List<String>{'Active','Planned'}])
        {              
        DX_FundIntegration__e av_event = new DX_FundIntegration__e(LegalEntity_Id__c 		= legalEntityObj.id,
                                                                       LegalEntity_Name__c 		= legalEntityObj.Name,
                                                                  Fund_Id__c = investment_vehicle_Obj.Id);
        avEventlst.add(av_event); 
        }
        
        Permission__c PermissionLst = [Select id,Permission_Type__c, Finaccount__c,Contact__c,Fund__c from Permission__c limit 1 ];*/
        
        delete legalEntityObj;
        test.stopTest();
        
        
    }
    

}